/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: /Users/andrewm/develop/modelstocode/mtc_source/tools/macosx/tack/lib/application/main.tcl, Revision: 3.8.1
 * Generated on: Fri Jun 23 14:53:53 PDT 2017
 */

#ifndef SIOHARNESS_H_
#define SIOHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void sio_harness_init(void) ;


#endif /* SIOHARNESS_H_ */
