/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: /Users/andrewm/develop/modelstocode/mtc_source/tools/macosx/tack/lib/application/main.tcl, Revision: 3.8.1
 * Generated on: Sun Apr 16 11:21:19 PDT 2017
 */

#ifndef ATCHARNESS_H_
#define ATCHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void atctrl_harness_init(void) ;


#endif /* ATCHARNESS_H_ */
