/*
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
 * Created by: C:/Users/andrewm/Working/modelrealization/modelstocode/mtc_source/tools/windows/pycca.exe/lib/application/pycca.tcl 
 * Created on: Sun Apr 16 10:56:22 PDT 2017
 * This is pycca version 4.3
 * ---------------------------------------------------------------
 */

#include <stdio.h>

#include <stddef.h>
#include <stdbool.h>
#include "mechs.h"

/*
 * The following macros may be used in the code to insulate the naming
 * conventions of "pycca" from the code.
 */
#define ClassRefType(c)             struct c *
#define ThisClassRefType            ClassRefType(THISCLASS__)
#define ClassRefVar(c, v)           struct c *v
#define ThisClassRefVar(v)          ClassRefVar(THISCLASS__, v)
#define ClassConstRefVar(c, v)      struct c const *v
#define ThisClassConstRefVar(v)     ClassConstRefVar(THISCLASS__, v)
#define ClassRefSetVar(c, v)        struct c **v
#define ThisClassRefSetVar(v)       ClassRefSetVar(THISCLASS__, v)
#define ClassRefConstSetVar(c, v)   struct c * const *v
#define ThisClassRefConstSetVar(v)  ClassRefConstSetVar(THISCLASS__, v)
#define ClassConstRefSetVar(c, v)   struct c const * const *v
#define ThisClassConstRefSetVar(v)  ClassConstRefSetVar(THISCLASS__, v)
#define SubCodeMember(r)            r ## __code
#define SubCodeValue(c, r, s)       c ## _ ## r ## _ ## s ## _CODE
#define SubTypesMember(r, s)        r . r ## _ ## s
#define RefCountMember(r)           r ## __count
#define SMName__(c, e, t)           c ## _ ## e ## t
#define EventNumber(c, e)           SMName__(c, e, _EVENT)
#define ThisClassEventNumber(e)     EventNumber(THISCLASS__, e)
#define PolyEventNumber(c, e)       SMName__(c, e, _POLYEVENT)
#define StateNumber(c, s)           SMName__(c, s, _STATE)
#define ThisClassStateNumber(s)     StateNumber(THISCLASS__, s)
#define SelfStateNumber             StateNumber(THISCLASS__, THISSTATE__)
#define ISName__(c)                 c ## _INITIAL_STATE
#define InitialStateNumber(c)       ISName__(c)
#define ThisClassInitialStateNumber InitialStateNumber(THISCLASS__)
#define EPName__(c, e)              struct c ## _ ## e ## _rcvd_evt
#define EventParamType(c, e)        EPName__(c, e)
#define EventParamDecl(c, e)        EPName__(c, e)
#define ThisClassEventParamDecl(e)  EventParamDecl(THISCLASS__, e)
#define CName__(c)                  (&c ## _class)
#define ClassData(c)                CName__(c)
#define ThisClassData               ClassData(THISCLASS__)
#define ExtStName__(d, c)           d ## _ ## c ## _storage
#define StName__(c)                 c ## _storage
#define BeginStorage(c)            StName__(c)
#define ThisClassBeginStorage       BeginStorage(THISCLASS__)
#define EndStorage(c)               (BeginStorage(c) + (sizeof(BeginStorage(c)) / sizeof(BeginStorage(c)[0])))
#define ThisClassEndStorage         EndStorage(THISCLASS__)
#define ExtIName__(d, c, n)         (ExtStName__(d, c, n) + c ## _ ## n ## _INSTANCE)
#define IName__(c, n)               (StName__(c) + c ## _ ## n ## _INSTANCE)
#define Instance(c, n)     IName__(c, n)
#define ThisClassInstance(n)     Instance(THISCLASS__, n)
#define IsInstInUse(i)      ((i)->common_.alloc != 0)
#define DomainName          launch
#define OpName(p, s)        p ## _ ## s
#define DomainOp(d, o)      OpName(d, o)
#define ExternalOp(o)       OpName(eop_ ## launch, o)
#define ClassOp(c, o)       OpName(c, o)
#define ThisClassOp(o)      ClassOp(THISCLASS__, o)
#define InstOp(c, o)        OpName(c, o)
#define ThisClassInstOp(o)  InstOp(THISCLASS__, o)

/*
 * Some convenience macros.
 */
#define PYCCA_generate(e, c, i, s) mechEventGenerate(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_generateSelf(e, c) PYCCA_generate(e, c, (MechInstance)self, (MechInstance)self)

#define PYCCA_generateToSelf(e) PYCCA_generateSelf(e, THISCLASS__)

#define PYCCA_generatePolymorphic(e, c, i, s) mechEventGeneratePolymorphic(PolyEventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_generateCreation(e, c, s) mechEventGenerateCreation(EventNumber(c, e), ClassData(c), (MechInstance)s)

#define PYCCA_generateDelayed(e, c, i, s, d) mechEventGenerateDelayed(EventNumber(c, e), (MechInstance)i, (MechInstance)s, d)

#define PYCCA_generateDelayedSelf(e, c, d) PYCCA_generateDelayed(e, c, (MechInstance)self, (MechInstance)self, d)

#define PYCCA_generateDelayedToSelf(e, d) PYCCA_generateDelayedSelf(e, THISCLASS__, d)

#define PYCCA_cancelDelayed(e, c, i, s) mechEventDelayCancel(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_cancelDelayedSelf(e, c) mechEventDelayCancel(EventNumber(c, e), (MechInstance)self, (MechInstance)self)

#define PYCCA_cancelDelayedToSelf(e) PYCCA_cancelDelayedSelf(e, THISCLASS__)

#define PYCCA_remainDelayed(e, c, i, s) mechEventDelayRemaining(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_remainDelayedSelf(e, c) PYCCA_remainDelayed(e, c, (MechInstance)self, (MechInstance)self)

#define PYCCA_remainDelayedToSelf(e) PYCCA_remainDelayedSelf(e, THISCLASS__)

#define PYCCA_newEvent(e, c, i, s) mechEventNew(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_newSelfEvent(e, c) mechEventNew(EventNumber(c, e), (MechInstance)self, (MechInstance)self)

#define PYCCA_newEventToSelf(e) PYCCA_newSelfEvent(e, THISCLASS__)

#define PYCCA_newPolymorphicEvent(e, c, i, s) mechPolyEventNew(PolyEventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_newCreationEvent(e, c, s) mechCreationEventNew(EventNumber(c, e), ClassData(c), (MechInstance)s)

#define PYCCA_newCreationEventForThisClass(e, s) PYCCA_newCreationEvent(e, THISCLASS__, s)

#define PYCCA_eventParam(ecb, c, e, p) ((EventParamDecl(c, e) *)(&(ecb)->eventParameters))->p

#define PYCCA_eventParamOfThisClass(ecb, e, p) PYCCA_eventParam(ecb, THISCLASS__, e, p)

#define PYCCA_postEvent(ecb) mechEventPost(ecb)

#define PYCCA_postSelfEvent(ecb) mechEventPostSelf(ecb)

#define PYCCA_postDelayedEvent(ecb, d) mechEventPostDelay(ecb, d)

#define PYCCA_createInstance(c, s) ((struct c *)mechInstCreate(ClassData(c), s))

#define PYCCA_newInstance(c)    PYCCA_createInstance(c, InitialStateNumber(c))

#define PYCCA_newInstanceOfThisClass     PYCCA_newInstance(THISCLASS__)

#define PYCCA_destroyInstance(i) (mechInstDestroy((MechInstance)i))

#define PYCCA_setToInitialState(i, c)   ((i)->common_.currentState = InitialStateNumber(c))

#define PYCCA_setToInitialStateForThisClass(i)    PYCCA_setToInitialState(i, THISCLASS__)

#define PYCCA_isSubtypeRelated(i, supc, r, subc) ((i)->SubCodeMember(r) == SubCodeValue(supc, r, subc))

#define PYCCA_unionSupertype(i, supc, r) ((struct supc *)((char *)(i) - offsetof(struct supc, r)))

#define PYCCA_unionSubtype(i, r, sub) (&((i)->SubTypesMember(r, sub)))

#define PYCCA_referenceSubtype(i, r, subc) ((struct subc *)((i)->r))

#define PYCCA_migrateSubtype(i, supc, r, subc) (i->SubCodeMember(r) = SubCodeValue(supc, r, subc))

#define PYCCA_initUnionInstance(sup, r, subc) sup->SubTypesMember(r, subc).common_.alloc = 1 ; sup->SubTypesMember(r, subc).common_.currentState = InitialStateNumber(subc) ; sup->SubTypesMember(r, subc).common_.instClass = ClassData(subc) ;

#define PYCCA_initUnionInstanceToState(sup, r, subc, st) sup->SubTypesMember(r, subc).common_.alloc = 1 ; sup->SubTypesMember(r, subc).common_.currentState = StateNumber(subc, st) ; sup->SubTypesMember(r, subc).common_.instClass = ClassData(subc) ;

#define PYCCA_forAllInst(i, c) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i)

#define PYCCA_forAllInstOfThisClass(i)   PYCCA_forAllInst(i, THISCLASS__)

#define PYCCA_forAllRelated(v, i, r) for (v = i->r ; v < i->r + i->RefCountMember(r) ; ++v)

#define PYCCA_forAllRelatedTerm(v, i, r) for (v = i->r ; *v ; ++v)

#define PYCCA_selectOneInstWhere(i, c, expr) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i) { if (IsInstInUse(i) && (expr)) {break ;}}

#define PYCCA_selectOneInstOfThisClassWhere(i, expr) PYCCA_selectOneInstWhere(i, THISCLASS__, expr) 
#define PYCCA_selectOneStaticInstWhere(i, c, expr) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i) { if ((expr)) {break ;}}

#define PYCCA_selectOneStaticInstOfThisClassWhere(i, expr) PYCCA_selectOneStaticInstWhere(i, THISCLASS__, expr)

#define PYCCA_relateSubtypeByRef(s, supc, r, t, subc) s->r = (MechInstance)t ; PYCCA_migrateSubtype(s, supc, r, subc)

#define PYCCA_relateToMany(n, o, r, m) for (n = o->r ; n < o->r + COUNTOF(o->r) ; ++n) { if (*n == NULL) { *n = m ; break ; } } assert(n < o->r + COUNTOF(o->r))

#define PYCCA_unrelateFromMany(n, o, r, m) for (n = o->r ; n < o->r + COUNTOF(o->r) ; ++n) { if (*n == m) { *n = NULL ; break ; } } assert(n < o->r + COUNTOF(o->r))

#define PYCCA_linkToMany(o, r, m) rlinkInsert(&m->r##__links, &o->r)

#define PYCCA_unlinkFromMany(m, r) rlinkRemove(&m->r##__links)

#define PYCCA_linkToInstRef(l, c, r) ((struct c *)((char *)(l) - offsetof(struct c, r##__links)))

#define PYCCA_linkToInstRefOfThisClass(l, r) PYCCA_linkToInstRef(l, THISCLASS__, r)

#define PYCCA_forAllLinkedInst(i, r, l) for (l = rlinkBegin(&i->r) ; l != rlinkEnd(&i->r) ; l = l->next)

#define PYCCA_isLinkEmpty(i, r) rlinkEmpty(&i->r)

#define PYCCA_isLinkNotEmpty(i, r) rlinkNotEmpty(&i->r)

#define PYCCA_idOfSelf              (self - ThisClassBeginStorage)

#define PYCCA_idOfRef(c, r)         ((r) - BeginStorage(c))

#define PYCCA_idOfInst(c, n)        (Instance(c, n) - BeginStorage(c))

#define PYCCA_refOfId(c, i)         (BeginStorage(c) + (i))

#define PYCCA_refOfThisClassId(i)   (ThisClassBeginStorage + (i))

#define PYCCA_checkId(c, i)         assert((i) < COUNTOF(BeginStorage(c)))

#define PYCCA_checkThisClassId(i)   assert((i) < COUNTOF(ThisClassBeginStorage))

#ifndef COUNTOF
#define COUNTOF(a)  (sizeof(a) / sizeof(a[0]))
#endif /* COUNTOF */

/*
 * Code for Domain, "launch"
 */

#define INSTRUMENT 1

/*
 * implementation prolog code
 */

#include "launch.h"
// Any additional implementation includes, etc.
typedef enum {
    Passive,
    Active
} L_type ;
typedef uint8_t Tube_number ;


#ifdef INSTRUMENT
#   ifndef INSTR_FUNC
#       ifdef TACK
#           include "harness.h"
#           define INSTR_FUNC(s) harness_stub_printf("instrument", "func %s file %s line %u", (s), __FILE__, __LINE__)
#       else
#           define INSTR_FUNC(s) printf("%s: %s %d\n", (s), __FILE__, __LINE__)
#       endif /* TACK */
#   endif /* INSTR_FUNC */
#endif /* INSTRUMENT */

/*
 * External Operations Declarations
 */
extern void eop_launch_MOTOR_start(Torpedo_ID torpedo) ;


/*
 * State Numbering
 */
/*
 * State Numbers for Class, "Stored_Torpedo"
 */
#define Stored_Torpedo_Installing_in_Rack_STATE 1
#define Stored_Torpedo_INITIAL_STATE 1
#define Stored_Torpedo_STORED_STATE 2
#define Stored_Torpedo_MAINTENANCE_STATE 3
#define Stored_Torpedo_Removing_STATE 4
#define Stored_Torpedo_Migrating_to_Loaded_STATE 5
#define Stored_Torpedo_Cancel_maintenance_interval_STATE 6
/*
 * State Numbers for Class, "Fired_Torpedo"
 */
#define Fired_Torpedo_CLEARING_SUB_STATE 0
#define Fired_Torpedo_INITIAL_STATE 0
#define Fired_Torpedo_Arming_STATE 1
#define Fired_Torpedo_SEEKING_TARGET_STATE 2
#define Fired_Torpedo_TARGET_ACQUIRED_STATE 3
#define Fired_Torpedo_Disarming_STATE 4
#define Fired_Torpedo_Exploded_STATE 5
#define Fired_Torpedo_Lost_STATE 6
/*
 * State Numbers for Class, "Passive_Launch_Torpedo"
 */
#define Passive_Launch_Torpedo_LOADED_STATE 0
#define Passive_Launch_Torpedo_INITIAL_STATE 0
#define Passive_Launch_Torpedo_LAUNCH_LOCK_STATE 1
#define Passive_Launch_Torpedo_Deleting_STATE 2
#define Passive_Launch_Torpedo_EXPELLING_STATE 3
#define Passive_Launch_Torpedo_Migrating_to_Fired_STATE 4
/*
 * State Numbers for Class, "Active_Launch_Torpedo"
 */
#define Active_Launch_Torpedo_LOADED_STATE 0
#define Active_Launch_Torpedo_INITIAL_STATE 0
#define Active_Launch_Torpedo_LAUNCH_LOCK_STATE 1
#define Active_Launch_Torpedo_Deleting_STATE 2
#define Active_Launch_Torpedo_ESCAPING_TUBE_STATE 3
#define Active_Launch_Torpedo_Migrating_to_Fired_STATE 4
/*
 * Pseudo initial states for inactive classes.
 */
#define Torpedo_INITIAL_STATE 0
#define Torpedo_Spec_INITIAL_STATE 0
#define Storage_Rack_INITIAL_STATE 0
#define Loaded_Torpedo_INITIAL_STATE 0
#define Tube_INITIAL_STATE 0

/*
 * Event Numbering
 */
/*
 * Event Numbers for Class, "Torpedo"
 */
#define Torpedo_Recall_POLYEVENT 0
/*
 * Event Numbers for Class, "Stored_Torpedo"
 */
#define Stored_Torpedo_Assigned_EVENT 0
#define Stored_Torpedo_Checks_out_ok_EVENT 1
#define Stored_Torpedo_Failed_maintenance_EVENT 2
#define Stored_Torpedo_Installed_EVENT 3
#define Stored_Torpedo_Load_EVENT 4
#define Stored_Torpedo_Maintence_canceled_EVENT 5
#define Stored_Torpedo_Recall_EVENT 6
#define Stored_Torpedo_Request_maintenance_check_EVENT 7
/*
 * Event Numbers for Class, "Loaded_Torpedo"
 */
#define Loaded_Torpedo_Cleared_tube_POLYEVENT 0
#define Loaded_Torpedo_Fire_POLYEVENT 1
#define Loaded_Torpedo_Recall_POLYEVENT 2
/*
 * Event Numbers for Class, "Fired_Torpedo"
 */
#define Fired_Torpedo_Armed_EVENT 0
#define Fired_Torpedo_Cleared_tube_EVENT 1
#define Fired_Torpedo_Contact_EVENT 2
#define Fired_Torpedo_Disarmed_EVENT 3
#define Fired_Torpedo_Lost_track_EVENT 4
#define Fired_Torpedo_Missed_EVENT 5
#define Fired_Torpedo_Recall_EVENT 6
#define Fired_Torpedo_Recall_requested_EVENT 7
#define Fired_Torpedo_Tracking_EVENT 8
/*
 * Event Numbers for Class, "Passive_Launch_Torpedo"
 */
#define Passive_Launch_Torpedo_Cleared_tube_EVENT 0
#define Passive_Launch_Torpedo_Fire_EVENT 1
#define Passive_Launch_Torpedo_Recall_EVENT 2
#define Passive_Launch_Torpedo_Unloaded_EVENT 3
/*
 * Event Numbers for Class, "Active_Launch_Torpedo"
 */
#define Active_Launch_Torpedo_Cleared_tube_EVENT 0
#define Active_Launch_Torpedo_Fire_EVENT 1
#define Active_Launch_Torpedo_Recall_EVENT 2
#define Active_Launch_Torpedo_Unloaded_EVENT 3

/*
 * Subtype Numbering
 */
/*
 * Subtype Numbers for Torpedo / R1
 */
#define Torpedo_R1_Stored_Torpedo_CODE 0
#define Torpedo_R1_Loaded_Torpedo_CODE 1
#define Torpedo_R1_Fired_Torpedo_CODE 2
/*
 * Subtype Numbers for Loaded_Torpedo / R2
 */
#define Loaded_Torpedo_R2_Passive_Launch_Torpedo_CODE 0
#define Loaded_Torpedo_R2_Active_Launch_Torpedo_CODE 1

/*
 * Offsets to named instances
 */
#define Torpedo_Spec_active_INSTANCE 0
#define Torpedo_Spec_passive_INSTANCE 1
#define Storage_Rack_sr1_INSTANCE 0
#define Storage_Rack_sr2_INSTANCE 1
#define Storage_Rack_sr3_INSTANCE 2
#define Storage_Rack_sr4_INSTANCE 3
#define Storage_Rack_sr5_INSTANCE 4
#define Storage_Rack_sr6_INSTANCE 5
#define Storage_Rack_sr7_INSTANCE 6
#define Storage_Rack_sr8_INSTANCE 7
#define Tube_tb1_INSTANCE 0
#define Tube_tb2_INSTANCE 1
#define Tube_tb3_INSTANCE 2
#define Tube_tb4_INSTANCE 3

/*
 * Forward class structure declarations
 */
struct Torpedo ;
struct Torpedo_Spec ;
struct Stored_Torpedo ;
struct Storage_Rack ;
struct Loaded_Torpedo ;
struct Tube ;
struct Fired_Torpedo ;
struct Passive_Launch_Torpedo ;
struct Active_Launch_Torpedo ;

/*
 * Class structure definitions
 */
struct Passive_Launch_Torpedo {
    struct mechinstance common_ ; // must be first !
    struct Loaded_Torpedo *R2 ;
} ;
struct Active_Launch_Torpedo {
    struct mechinstance common_ ; // must be first !
    struct Loaded_Torpedo *R2 ;
} ;
struct Stored_Torpedo {
    struct mechinstance common_ ; // must be first !
    struct Torpedo *R1 ;
    struct Storage_Rack *R3 ;
} ;
struct Loaded_Torpedo {
    struct mechinstance common_ ; // must be first !
    struct Torpedo *R1 ;
    struct Tube *R4 ;
    SubtypeCode R2__code ;
    MechInstance R2 ;
} ;
struct Fired_Torpedo {
    struct mechinstance common_ ; // must be first !
    struct Torpedo *R1 ;
} ;
struct Torpedo {
    struct mechinstance common_ ; // must be first !
    Torpedo_ID ID ;
    bool Recalled ;
    struct Torpedo_Spec *R5 ;
    SubtypeCode R1__code ;
    MechInstance R1 ;
} ;
struct Torpedo_Spec {
    char const * Name ;
    L_type Launch_type ;
} ;
struct Storage_Rack {
    unsigned Number ;
} ;
struct Tube {
    Tube_number Number ;
    bool Flooded ;
} ;

/*
 * Event Parameter Structure Definitions
 */
struct Stored_Torpedo_Assigned_rcvd_evt {
    uint8_t rack ;
} ;
struct Stored_Torpedo_Load_rcvd_evt {
    Tube_number Number ;
} ;


/*
 * Forward Operation Function Declarations
 */
static void Torpedo_Recall(struct Torpedo *self) ;

/*
 * Forward Declarations of Class Constructors
 */

/*
 * Forward Declarations of Class Destructors
 */

/*
 * Forward Declarations of State Action Functions
 */
static void Active_Launch_Torpedo_Deleting(void *const s_, void *const p_) ;
static void Active_Launch_Torpedo_ESCAPING_TUBE(void *const s_, void *const p_) ;
static void Active_Launch_Torpedo_LAUNCH_LOCK(void *const s_, void *const p_) ;
static void Active_Launch_Torpedo_LOADED(void *const s_, void *const p_) ;
static void Active_Launch_Torpedo_Migrating_to_Fired(void *const s_, void *const p_) ;
static void Fired_Torpedo_Arming(void *const s_, void *const p_) ;
static void Fired_Torpedo_CLEARING_SUB(void *const s_, void *const p_) ;
static void Fired_Torpedo_Disarming(void *const s_, void *const p_) ;
static void Fired_Torpedo_Exploded(void *const s_, void *const p_) ;
static void Fired_Torpedo_Lost(void *const s_, void *const p_) ;
static void Fired_Torpedo_SEEKING_TARGET(void *const s_, void *const p_) ;
static void Fired_Torpedo_TARGET_ACQUIRED(void *const s_, void *const p_) ;
static void Passive_Launch_Torpedo_Deleting(void *const s_, void *const p_) ;
static void Passive_Launch_Torpedo_EXPELLING(void *const s_, void *const p_) ;
static void Passive_Launch_Torpedo_LAUNCH_LOCK(void *const s_, void *const p_) ;
static void Passive_Launch_Torpedo_LOADED(void *const s_, void *const p_) ;
static void Passive_Launch_Torpedo_Migrating_to_Fired(void *const s_, void *const p_) ;
static void Stored_Torpedo_Installing_in_Rack(void *const s_, void *const p_) ;
static void Stored_Torpedo_Migrating_to_Loaded(void *const s_, void *const p_) ;
static void Stored_Torpedo_Cancel_maintenance_interval(void *const s_, void *const p_) ;
static void Stored_Torpedo_MAINTENANCE(void *const s_, void *const p_) ;
static void Stored_Torpedo_Removing(void *const s_, void *const p_) ;
static void Stored_Torpedo_STORED(void *const s_, void *const p_) ;

/*
 * Domain Operations External Declarations
 */

/*
 * Declaration of Function to Construct Initial Instances
 */

/*
 * Forward Instance Storage Declarations
 */
static struct Torpedo Torpedo_storage[] ;
static struct Torpedo_Spec Torpedo_Spec_storage[] ;
static struct Stored_Torpedo Stored_Torpedo_storage[] ;
static struct Storage_Rack Storage_Rack_storage[] ;
static struct Loaded_Torpedo Loaded_Torpedo_storage[] ;
static struct Tube Tube_storage[] ;
static struct Fired_Torpedo Fired_Torpedo_storage[] ;
static struct Passive_Launch_Torpedo Passive_Launch_Torpedo_storage[] ;
static struct Active_Launch_Torpedo Active_Launch_Torpedo_storage[] ;


/*
 * Instance Allocation Block Definitions
 */
static struct installocblock Torpedo_iab = {
    .storageStart = Torpedo_storage,
    .storageFinish = Torpedo_storage + 20,
    .storageLast = Torpedo_storage + 0,
    .allocCounter = 0,
    .instanceSize = sizeof(struct Torpedo),
    .construct = NULL,
    .destruct = NULL
} ;
static struct installocblock Stored_Torpedo_iab = {
    .storageStart = Stored_Torpedo_storage,
    .storageFinish = Stored_Torpedo_storage + 20,
    .storageLast = Stored_Torpedo_storage + 0,
    .allocCounter = 0,
    .instanceSize = sizeof(struct Stored_Torpedo),
    .construct = NULL,
    .destruct = NULL
} ;
static struct installocblock Loaded_Torpedo_iab = {
    .storageStart = Loaded_Torpedo_storage,
    .storageFinish = Loaded_Torpedo_storage + 8,
    .storageLast = Loaded_Torpedo_storage + 0,
    .allocCounter = 0,
    .instanceSize = sizeof(struct Loaded_Torpedo),
    .construct = NULL,
    .destruct = NULL
} ;
static struct installocblock Fired_Torpedo_iab = {
    .storageStart = Fired_Torpedo_storage,
    .storageFinish = Fired_Torpedo_storage + 20,
    .storageLast = Fired_Torpedo_storage + 0,
    .allocCounter = 0,
    .instanceSize = sizeof(struct Fired_Torpedo),
    .construct = NULL,
    .destruct = NULL
} ;
static struct installocblock Passive_Launch_Torpedo_iab = {
    .storageStart = Passive_Launch_Torpedo_storage,
    .storageFinish = Passive_Launch_Torpedo_storage + 8,
    .storageLast = Passive_Launch_Torpedo_storage + 0,
    .allocCounter = 0,
    .instanceSize = sizeof(struct Passive_Launch_Torpedo),
    .construct = NULL,
    .destruct = NULL
} ;
static struct installocblock Active_Launch_Torpedo_iab = {
    .storageStart = Active_Launch_Torpedo_storage,
    .storageFinish = Active_Launch_Torpedo_storage + 8,
    .storageLast = Active_Launch_Torpedo_storage + 0,
    .allocCounter = 0,
    .instanceSize = sizeof(struct Active_Launch_Torpedo),
    .construct = NULL,
    .destruct = NULL
} ;

/*
 * AODB for Class, "Stored_Torpedo"
 */
static bool const Stored_Torpedo_fs[] = {0, 0, 0, 0, 1, 1, 0, } ;
static PtrActionFunction const Stored_Torpedo_acttbl[] = {
    NULL,
    Stored_Torpedo_Installing_in_Rack,
    Stored_Torpedo_STORED,
    Stored_Torpedo_MAINTENANCE,
    Stored_Torpedo_Removing,
    Stored_Torpedo_Migrating_to_Loaded,
    Stored_Torpedo_Cancel_maintenance_interval,
} ;
static StateCode const Stored_Torpedo_transtbl[] = {
    1, // . - Assigned -> Installing_in_Rack
    MECH_STATECODE_CH, // . - Checks_out_ok -> CH
    MECH_STATECODE_CH, // . - Failed_maintenance -> CH
    MECH_STATECODE_CH, // . - Installed -> CH
    MECH_STATECODE_CH, // . - Load -> CH
    MECH_STATECODE_CH, // . - Maintence_canceled -> CH
    MECH_STATECODE_CH, // . - Recall -> CH
    MECH_STATECODE_CH, // . - Request_maintenance_check -> CH
    MECH_STATECODE_CH, // Installing_in_Rack - Assigned -> CH
    MECH_STATECODE_CH, // Installing_in_Rack - Checks_out_ok -> CH
    MECH_STATECODE_CH, // Installing_in_Rack - Failed_maintenance -> CH
    2, // Installing_in_Rack - Installed -> STORED
    MECH_STATECODE_CH, // Installing_in_Rack - Load -> CH
    MECH_STATECODE_CH, // Installing_in_Rack - Maintence_canceled -> CH
    MECH_STATECODE_CH, // Installing_in_Rack - Recall -> CH
    MECH_STATECODE_CH, // Installing_in_Rack - Request_maintenance_check -> CH
    MECH_STATECODE_CH, // STORED - Assigned -> CH
    MECH_STATECODE_CH, // STORED - Checks_out_ok -> CH
    MECH_STATECODE_CH, // STORED - Failed_maintenance -> CH
    MECH_STATECODE_CH, // STORED - Installed -> CH
    5, // STORED - Load -> Migrating_to_Loaded
    MECH_STATECODE_CH, // STORED - Maintence_canceled -> CH
    6, // STORED - Recall -> Cancel_maintenance_interval
    3, // STORED - Request_maintenance_check -> MAINTENANCE
    MECH_STATECODE_CH, // MAINTENANCE - Assigned -> CH
    2, // MAINTENANCE - Checks_out_ok -> STORED
    4, // MAINTENANCE - Failed_maintenance -> Removing
    MECH_STATECODE_CH, // MAINTENANCE - Installed -> CH
    MECH_STATECODE_CH, // MAINTENANCE - Load -> CH
    MECH_STATECODE_CH, // MAINTENANCE - Maintence_canceled -> CH
    4, // MAINTENANCE - Recall -> Removing
    MECH_STATECODE_CH, // MAINTENANCE - Request_maintenance_check -> CH
    MECH_STATECODE_CH, // Removing - Assigned -> CH
    MECH_STATECODE_CH, // Removing - Checks_out_ok -> CH
    MECH_STATECODE_CH, // Removing - Failed_maintenance -> CH
    MECH_STATECODE_CH, // Removing - Installed -> CH
    MECH_STATECODE_CH, // Removing - Load -> CH
    MECH_STATECODE_CH, // Removing - Maintence_canceled -> CH
    MECH_STATECODE_CH, // Removing - Recall -> CH
    MECH_STATECODE_CH, // Removing - Request_maintenance_check -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Assigned -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Checks_out_ok -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Failed_maintenance -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Installed -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Load -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Maintence_canceled -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Recall -> CH
    MECH_STATECODE_CH, // Migrating_to_Loaded - Request_maintenance_check -> CH
    MECH_STATECODE_CH, // Cancel_maintenance_interval - Assigned -> CH
    MECH_STATECODE_CH, // Cancel_maintenance_interval - Checks_out_ok -> CH
    MECH_STATECODE_CH, // Cancel_maintenance_interval - Failed_maintenance -> CH
    MECH_STATECODE_CH, // Cancel_maintenance_interval - Installed -> CH
    MECH_STATECODE_CH, // Cancel_maintenance_interval - Load -> CH
    4, // Cancel_maintenance_interval - Maintence_canceled -> Removing
    MECH_STATECODE_CH, // Cancel_maintenance_interval - Recall -> CH
    MECH_STATECODE_CH, // Cancel_maintenance_interval - Request_maintenance_check -> CH
} ;
static struct objectdispatchblock const Stored_Torpedo_odb = {
    .stateCount = 7,
    .eventCount = 8,
    .transitionTable = Stored_Torpedo_transtbl,
    .actionTable = Stored_Torpedo_acttbl,
    .finalStates = Stored_Torpedo_fs
} ;
/*
 * AODB for Class, "Fired_Torpedo"
 */
static bool const Fired_Torpedo_fs[] = {0, 0, 0, 0, 0, 1, 1, } ;
static PtrActionFunction const Fired_Torpedo_acttbl[] = {
    Fired_Torpedo_CLEARING_SUB,
    Fired_Torpedo_Arming,
    Fired_Torpedo_SEEKING_TARGET,
    Fired_Torpedo_TARGET_ACQUIRED,
    Fired_Torpedo_Disarming,
    Fired_Torpedo_Exploded,
    Fired_Torpedo_Lost,
} ;
static StateCode const Fired_Torpedo_transtbl[] = {
    MECH_STATECODE_CH, // CLEARING_SUB - Armed -> CH
    1, // CLEARING_SUB - Cleared_tube -> Arming
    MECH_STATECODE_CH, // CLEARING_SUB - Contact -> CH
    MECH_STATECODE_CH, // CLEARING_SUB - Disarmed -> CH
    MECH_STATECODE_CH, // CLEARING_SUB - Lost_track -> CH
    MECH_STATECODE_CH, // CLEARING_SUB - Missed -> CH
    6, // CLEARING_SUB - Recall -> Lost
    MECH_STATECODE_CH, // CLEARING_SUB - Recall_requested -> CH
    MECH_STATECODE_CH, // CLEARING_SUB - Tracking -> CH
    2, // Arming - Armed -> SEEKING_TARGET
    MECH_STATECODE_CH, // Arming - Cleared_tube -> CH
    MECH_STATECODE_CH, // Arming - Contact -> CH
    MECH_STATECODE_CH, // Arming - Disarmed -> CH
    MECH_STATECODE_CH, // Arming - Lost_track -> CH
    MECH_STATECODE_CH, // Arming - Missed -> CH
    MECH_STATECODE_CH, // Arming - Recall -> CH
    6, // Arming - Recall_requested -> Lost
    MECH_STATECODE_CH, // Arming - Tracking -> CH
    MECH_STATECODE_CH, // SEEKING_TARGET - Armed -> CH
    MECH_STATECODE_CH, // SEEKING_TARGET - Cleared_tube -> CH
    MECH_STATECODE_CH, // SEEKING_TARGET - Contact -> CH
    MECH_STATECODE_CH, // SEEKING_TARGET - Disarmed -> CH
    MECH_STATECODE_CH, // SEEKING_TARGET - Lost_track -> CH
    MECH_STATECODE_CH, // SEEKING_TARGET - Missed -> CH
    4, // SEEKING_TARGET - Recall -> Disarming
    MECH_STATECODE_CH, // SEEKING_TARGET - Recall_requested -> CH
    3, // SEEKING_TARGET - Tracking -> TARGET_ACQUIRED
    MECH_STATECODE_CH, // TARGET_ACQUIRED - Armed -> CH
    MECH_STATECODE_CH, // TARGET_ACQUIRED - Cleared_tube -> CH
    5, // TARGET_ACQUIRED - Contact -> Exploded
    MECH_STATECODE_CH, // TARGET_ACQUIRED - Disarmed -> CH
    2, // TARGET_ACQUIRED - Lost_track -> SEEKING_TARGET
    4, // TARGET_ACQUIRED - Missed -> Disarming
    4, // TARGET_ACQUIRED - Recall -> Disarming
    MECH_STATECODE_CH, // TARGET_ACQUIRED - Recall_requested -> CH
    MECH_STATECODE_CH, // TARGET_ACQUIRED - Tracking -> CH
    MECH_STATECODE_CH, // Disarming - Armed -> CH
    MECH_STATECODE_CH, // Disarming - Cleared_tube -> CH
    MECH_STATECODE_CH, // Disarming - Contact -> CH
    6, // Disarming - Disarmed -> Lost
    MECH_STATECODE_CH, // Disarming - Lost_track -> CH
    MECH_STATECODE_CH, // Disarming - Missed -> CH
    MECH_STATECODE_CH, // Disarming - Recall -> CH
    MECH_STATECODE_CH, // Disarming - Recall_requested -> CH
    MECH_STATECODE_CH, // Disarming - Tracking -> CH
    MECH_STATECODE_CH, // Exploded - Armed -> CH
    MECH_STATECODE_CH, // Exploded - Cleared_tube -> CH
    MECH_STATECODE_CH, // Exploded - Contact -> CH
    MECH_STATECODE_CH, // Exploded - Disarmed -> CH
    MECH_STATECODE_CH, // Exploded - Lost_track -> CH
    MECH_STATECODE_CH, // Exploded - Missed -> CH
    MECH_STATECODE_CH, // Exploded - Recall -> CH
    MECH_STATECODE_CH, // Exploded - Recall_requested -> CH
    MECH_STATECODE_CH, // Exploded - Tracking -> CH
    MECH_STATECODE_CH, // Lost - Armed -> CH
    MECH_STATECODE_CH, // Lost - Cleared_tube -> CH
    MECH_STATECODE_CH, // Lost - Contact -> CH
    MECH_STATECODE_CH, // Lost - Disarmed -> CH
    MECH_STATECODE_CH, // Lost - Lost_track -> CH
    MECH_STATECODE_CH, // Lost - Missed -> CH
    MECH_STATECODE_CH, // Lost - Recall -> CH
    MECH_STATECODE_CH, // Lost - Recall_requested -> CH
    MECH_STATECODE_CH, // Lost - Tracking -> CH
} ;
static struct objectdispatchblock const Fired_Torpedo_odb = {
    .stateCount = 7,
    .eventCount = 9,
    .transitionTable = Fired_Torpedo_transtbl,
    .actionTable = Fired_Torpedo_acttbl,
    .finalStates = Fired_Torpedo_fs
} ;
/*
 * AODB for Class, "Passive_Launch_Torpedo"
 */
static bool const Passive_Launch_Torpedo_fs[] = {0, 0, 1, 0, 1, } ;
static PtrActionFunction const Passive_Launch_Torpedo_acttbl[] = {
    Passive_Launch_Torpedo_LOADED,
    Passive_Launch_Torpedo_LAUNCH_LOCK,
    Passive_Launch_Torpedo_Deleting,
    Passive_Launch_Torpedo_EXPELLING,
    Passive_Launch_Torpedo_Migrating_to_Fired,
} ;
static StateCode const Passive_Launch_Torpedo_transtbl[] = {
    MECH_STATECODE_CH, // LOADED - Cleared_tube -> CH
    3, // LOADED - Fire -> EXPELLING
    1, // LOADED - Recall -> LAUNCH_LOCK
    MECH_STATECODE_CH, // LOADED - Unloaded -> CH
    MECH_STATECODE_CH, // LAUNCH_LOCK - Cleared_tube -> CH
    MECH_STATECODE_CH, // LAUNCH_LOCK - Fire -> CH
    MECH_STATECODE_CH, // LAUNCH_LOCK - Recall -> CH
    2, // LAUNCH_LOCK - Unloaded -> Deleting
    MECH_STATECODE_CH, // Deleting - Cleared_tube -> CH
    MECH_STATECODE_CH, // Deleting - Fire -> CH
    MECH_STATECODE_CH, // Deleting - Recall -> CH
    MECH_STATECODE_CH, // Deleting - Unloaded -> CH
    4, // EXPELLING - Cleared_tube -> Migrating_to_Fired
    MECH_STATECODE_CH, // EXPELLING - Fire -> CH
    MECH_STATECODE_CH, // EXPELLING - Recall -> CH
    MECH_STATECODE_CH, // EXPELLING - Unloaded -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Cleared_tube -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Fire -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Recall -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Unloaded -> CH
} ;
static struct objectdispatchblock const Passive_Launch_Torpedo_odb = {
    .stateCount = 5,
    .eventCount = 4,
    .transitionTable = Passive_Launch_Torpedo_transtbl,
    .actionTable = Passive_Launch_Torpedo_acttbl,
    .finalStates = Passive_Launch_Torpedo_fs
} ;
/*
 * AODB for Class, "Active_Launch_Torpedo"
 */
static bool const Active_Launch_Torpedo_fs[] = {0, 0, 1, 0, 1, } ;
static PtrActionFunction const Active_Launch_Torpedo_acttbl[] = {
    Active_Launch_Torpedo_LOADED,
    Active_Launch_Torpedo_LAUNCH_LOCK,
    Active_Launch_Torpedo_Deleting,
    Active_Launch_Torpedo_ESCAPING_TUBE,
    Active_Launch_Torpedo_Migrating_to_Fired,
} ;
static StateCode const Active_Launch_Torpedo_transtbl[] = {
    MECH_STATECODE_CH, // LOADED - Cleared_tube -> CH
    3, // LOADED - Fire -> ESCAPING_TUBE
    1, // LOADED - Recall -> LAUNCH_LOCK
    MECH_STATECODE_CH, // LOADED - Unloaded -> CH
    MECH_STATECODE_CH, // LAUNCH_LOCK - Cleared_tube -> CH
    MECH_STATECODE_CH, // LAUNCH_LOCK - Fire -> CH
    MECH_STATECODE_CH, // LAUNCH_LOCK - Recall -> CH
    2, // LAUNCH_LOCK - Unloaded -> Deleting
    MECH_STATECODE_CH, // Deleting - Cleared_tube -> CH
    MECH_STATECODE_CH, // Deleting - Fire -> CH
    MECH_STATECODE_CH, // Deleting - Recall -> CH
    MECH_STATECODE_CH, // Deleting - Unloaded -> CH
    4, // ESCAPING_TUBE - Cleared_tube -> Migrating_to_Fired
    MECH_STATECODE_CH, // ESCAPING_TUBE - Fire -> CH
    MECH_STATECODE_CH, // ESCAPING_TUBE - Recall -> CH
    MECH_STATECODE_CH, // ESCAPING_TUBE - Unloaded -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Cleared_tube -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Fire -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Recall -> CH
    MECH_STATECODE_CH, // Migrating_to_Fired - Unloaded -> CH
} ;
static struct objectdispatchblock const Active_Launch_Torpedo_odb = {
    .stateCount = 5,
    .eventCount = 4,
    .transitionTable = Active_Launch_Torpedo_transtbl,
    .actionTable = Active_Launch_Torpedo_acttbl,
    .finalStates = Active_Launch_Torpedo_fs
} ;

/*
 * PDB for Class, "Torpedo"
 */
static struct polyeventmap const Torpedo_R1_pem[] = {
    {.event = 6, .eventType = NormalEvent},
    {.event = 2, .eventType = PolymorphicEvent},
    {.event = 6, .eventType = NormalEvent}
} ;
static struct hierarchydispatch const Torpedo_hdb[] = {
    {.refStorage = PolyReference,
    .subCodeOffset = offsetof(struct Torpedo, R1__code),
    .subInstOffset = offsetof(struct Torpedo, R1),
    .subtypeCount = 3,
    .eventMap = Torpedo_R1_pem}
} ;
static struct polydispatchblock const Torpedo_pdb = {
    .eventCount = 1,
    .hierCount = 1,
    .hierarchy = Torpedo_hdb
} ;
/*
 * PDB for Class, "Loaded_Torpedo"
 */
static struct polyeventmap const Loaded_Torpedo_R2_pem[] = {
    {.event = 0, .eventType = NormalEvent},
    {.event = 1, .eventType = NormalEvent},
    {.event = 2, .eventType = NormalEvent},
    {.event = 0, .eventType = NormalEvent},
    {.event = 1, .eventType = NormalEvent},
    {.event = 2, .eventType = NormalEvent}
} ;
static struct hierarchydispatch const Loaded_Torpedo_hdb[] = {
    {.refStorage = PolyReference,
    .subCodeOffset = offsetof(struct Loaded_Torpedo, R2__code),
    .subInstOffset = offsetof(struct Loaded_Torpedo, R2),
    .subtypeCount = 2,
    .eventMap = Loaded_Torpedo_R2_pem}
} ;
static struct polydispatchblock const Loaded_Torpedo_pdb = {
    .eventCount = 3,
    .hierCount = 1,
    .hierarchy = Loaded_Torpedo_hdb
} ;

/*
 * Class Structure for, "Torpedo"
 */
static struct mechclass const Torpedo_class = {
    .iab = &Torpedo_iab,
    .odb = NULL,
    .pdb = &Torpedo_pdb
} ;
/*
 * Class Structure for, "Stored_Torpedo"
 */
static struct mechclass const Stored_Torpedo_class = {
    .iab = &Stored_Torpedo_iab,
    .odb = &Stored_Torpedo_odb,
    .pdb = NULL
} ;
/*
 * Class Structure for, "Loaded_Torpedo"
 */
static struct mechclass const Loaded_Torpedo_class = {
    .iab = &Loaded_Torpedo_iab,
    .odb = NULL,
    .pdb = &Loaded_Torpedo_pdb
} ;
/*
 * Class Structure for, "Fired_Torpedo"
 */
static struct mechclass const Fired_Torpedo_class = {
    .iab = &Fired_Torpedo_iab,
    .odb = &Fired_Torpedo_odb,
    .pdb = NULL
} ;
/*
 * Class Structure for, "Passive_Launch_Torpedo"
 */
static struct mechclass const Passive_Launch_Torpedo_class = {
    .iab = &Passive_Launch_Torpedo_iab,
    .odb = &Passive_Launch_Torpedo_odb,
    .pdb = NULL
} ;
/*
 * Class Structure for, "Active_Launch_Torpedo"
 */
static struct mechclass const Active_Launch_Torpedo_class = {
    .iab = &Active_Launch_Torpedo_iab,
    .odb = &Active_Launch_Torpedo_odb,
    .pdb = NULL
} ;


/*
 * Data Portal data structures
 */
#include "pycca_portal.h"
static struct pycca_attr_portal const Torpedo_attr_portal[3] = {
    {.offset = offsetof(struct Torpedo, ID), .size = sizeof(Torpedo_storage->ID)},
    {.offset = offsetof(struct Torpedo, Recalled), .size = sizeof(Torpedo_storage->Recalled)},
    {.offset = offsetof(struct Torpedo, R1__code), .size = sizeof(Torpedo_storage->R1__code)},
} ;
static struct pycca_attr_portal const Torpedo_Spec_attr_portal[2] = {
    {.offset = offsetof(struct Torpedo_Spec, Name), .size = sizeof(Torpedo_Spec_storage->Name)},
    {.offset = offsetof(struct Torpedo_Spec, Launch_type), .size = sizeof(Torpedo_Spec_storage->Launch_type)},
} ;
static struct pycca_attr_portal const Storage_Rack_attr_portal[1] = {
    {.offset = offsetof(struct Storage_Rack, Number), .size = sizeof(Storage_Rack_storage->Number)},
} ;
static struct pycca_attr_portal const Loaded_Torpedo_attr_portal[1] = {
    {.offset = offsetof(struct Loaded_Torpedo, R2__code), .size = sizeof(Loaded_Torpedo_storage->R2__code)},
} ;
static struct pycca_attr_portal const Tube_attr_portal[2] = {
    {.offset = offsetof(struct Tube, Number), .size = sizeof(Tube_storage->Number)},
    {.offset = offsetof(struct Tube, Flooded), .size = sizeof(Tube_storage->Flooded)},
} ;
static struct pycca_class_portal const launch_class_portal[] = {
    {.storage = Torpedo_storage, .attrs = Torpedo_attr_portal, .mechClass = &Torpedo_class, .numAttrs = 3, .numInsts = 20, .instSize = sizeof(struct Torpedo), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Torpedo_INITIAL_STATE},
    {.storage = Torpedo_Spec_storage, .attrs = Torpedo_Spec_attr_portal, .mechClass = NULL, .numAttrs = 2, .numInsts = 2, .instSize = sizeof(struct Torpedo_Spec), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Torpedo_Spec_INITIAL_STATE},
    {.storage = Stored_Torpedo_storage, .attrs = NULL, .mechClass = &Stored_Torpedo_class, .numAttrs = 0, .numInsts = 20, .instSize = sizeof(struct Stored_Torpedo), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Stored_Torpedo_INITIAL_STATE},
    {.storage = Storage_Rack_storage, .attrs = Storage_Rack_attr_portal, .mechClass = NULL, .numAttrs = 1, .numInsts = 8, .instSize = sizeof(struct Storage_Rack), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Storage_Rack_INITIAL_STATE},
    {.storage = Loaded_Torpedo_storage, .attrs = Loaded_Torpedo_attr_portal, .mechClass = &Loaded_Torpedo_class, .numAttrs = 1, .numInsts = 8, .instSize = sizeof(struct Loaded_Torpedo), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Loaded_Torpedo_INITIAL_STATE},
    {.storage = Tube_storage, .attrs = Tube_attr_portal, .mechClass = NULL, .numAttrs = 2, .numInsts = 4, .instSize = sizeof(struct Tube), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Tube_INITIAL_STATE},
    {.storage = Fired_Torpedo_storage, .attrs = NULL, .mechClass = &Fired_Torpedo_class, .numAttrs = 0, .numInsts = 20, .instSize = sizeof(struct Fired_Torpedo), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Fired_Torpedo_INITIAL_STATE},
    {.storage = Passive_Launch_Torpedo_storage, .attrs = NULL, .mechClass = &Passive_Launch_Torpedo_class, .numAttrs = 0, .numInsts = 8, .instSize = sizeof(struct Passive_Launch_Torpedo), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Passive_Launch_Torpedo_INITIAL_STATE},
    {.storage = Active_Launch_Torpedo_storage, .attrs = NULL, .mechClass = &Active_Launch_Torpedo_class, .numAttrs = 0, .numInsts = 8, .instSize = sizeof(struct Active_Launch_Torpedo), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Active_Launch_Torpedo_INITIAL_STATE},
} ;
struct pycca_domain_portal const launch_portal = {
    .classes = launch_class_portal,
    .numClasses = 9
} ;

/*
 * Multi-ref pointer arrays
 */

/*
 * Initial Instance Storage for, "Torpedo"
 */
static struct Torpedo Torpedo_storage[20] ;
/*
 * Initial Instance Storage for, "Torpedo_Spec"
 */
static struct Torpedo_Spec Torpedo_Spec_storage[2] = {
    {"Active", Active},
    {"Passive", Passive}
} ;
/*
 * Initial Instance Storage for, "Stored_Torpedo"
 */
static struct Stored_Torpedo Stored_Torpedo_storage[20] ;
/*
 * Initial Instance Storage for, "Storage_Rack"
 */
static struct Storage_Rack Storage_Rack_storage[8] = {
    {1},
    {2},
    {3},
    {4},
    {5},
    {6},
    {7},
    {8}
} ;
/*
 * Initial Instance Storage for, "Loaded_Torpedo"
 */
static struct Loaded_Torpedo Loaded_Torpedo_storage[8] ;
/*
 * Initial Instance Storage for, "Tube"
 */
static struct Tube Tube_storage[4] = {
    {1, false},
    {2, false},
    {3, false},
    {4, false}
} ;
/*
 * Initial Instance Storage for, "Fired_Torpedo"
 */
static struct Fired_Torpedo Fired_Torpedo_storage[20] ;
/*
 * Initial Instance Storage for, "Passive_Launch_Torpedo"
 */
static struct Passive_Launch_Torpedo Passive_Launch_Torpedo_storage[8] ;
/*
 * Initial Instance Storage for, "Active_Launch_Torpedo"
 */
static struct Active_Launch_Torpedo Active_Launch_Torpedo_storage[8] ;

/*
 * Operation Function Definitions
 */
#define THISCLASS__ Torpedo
static void Torpedo_Recall(struct Torpedo *self)
{
    INSTR_FUNC("launch.Torpedo.Recall") ;

    self->Recalled = true ;
    PYCCA_generatePolymorphic(Recall, Torpedo, self, self) ;
}
#undef THISCLASS__

/*
 * Constructor Function Definitions
 */

/*
 * Destructor Function Definitions
 */

/*
 * State Action Function Definitions
 */
#define THISCLASS__ Active_Launch_Torpedo
static void Active_Launch_Torpedo_LOADED(void *const s_, void *const p_)
{
#define THISSTATE__ LOADED
    INSTR_FUNC("launch.Active_Launch_Torpedo.LOADED") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Active_Launch_Torpedo_LAUNCH_LOCK(void *const s_, void *const p_)
{
#define THISSTATE__ LAUNCH_LOCK
    INSTR_FUNC("launch.Active_Launch_Torpedo.LAUNCH_LOCK") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Active_Launch_Torpedo_Deleting(void *const s_, void *const p_)
{
#define THISSTATE__ Deleting
    INSTR_FUNC("launch.Active_Launch_Torpedo.Deleting") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Active_Launch_Torpedo_ESCAPING_TUBE(void *const s_, void *const p_)
{
#define THISSTATE__ ESCAPING_TUBE
    INSTR_FUNC("launch.Active_Launch_Torpedo.ESCAPING_TUBE") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Active_Launch_Torpedo_Migrating_to_Fired(void *const s_, void *const p_)
{
#define THISSTATE__ Migrating_to_Fired
    INSTR_FUNC("launch.Active_Launch_Torpedo.Migrating_to_Fired") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Fired_Torpedo
static void Fired_Torpedo_CLEARING_SUB(void *const s_, void *const p_)
{
#define THISSTATE__ CLEARING_SUB
    INSTR_FUNC("launch.Fired_Torpedo.CLEARING_SUB") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Fired_Torpedo_Arming(void *const s_, void *const p_)
{
#define THISSTATE__ Arming
    INSTR_FUNC("launch.Fired_Torpedo.Arming") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Fired_Torpedo_SEEKING_TARGET(void *const s_, void *const p_)
{
#define THISSTATE__ SEEKING_TARGET
    INSTR_FUNC("launch.Fired_Torpedo.SEEKING_TARGET") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Fired_Torpedo_TARGET_ACQUIRED(void *const s_, void *const p_)
{
#define THISSTATE__ TARGET_ACQUIRED
    INSTR_FUNC("launch.Fired_Torpedo.TARGET_ACQUIRED") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Fired_Torpedo_Disarming(void *const s_, void *const p_)
{
#define THISSTATE__ Disarming
    INSTR_FUNC("launch.Fired_Torpedo.Disarming") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Fired_Torpedo_Exploded(void *const s_, void *const p_)
{
#define THISSTATE__ Exploded
    INSTR_FUNC("launch.Fired_Torpedo.Exploded") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Fired_Torpedo_Lost(void *const s_, void *const p_)
{
#define THISSTATE__ Lost
    INSTR_FUNC("launch.Fired_Torpedo.Lost") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Passive_Launch_Torpedo
static void Passive_Launch_Torpedo_LOADED(void *const s_, void *const p_)
{
#define THISSTATE__ LOADED
    INSTR_FUNC("launch.Passive_Launch_Torpedo.LOADED") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Passive_Launch_Torpedo_LAUNCH_LOCK(void *const s_, void *const p_)
{
#define THISSTATE__ LAUNCH_LOCK
    INSTR_FUNC("launch.Passive_Launch_Torpedo.LAUNCH_LOCK") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Passive_Launch_Torpedo_Deleting(void *const s_, void *const p_)
{
#define THISSTATE__ Deleting
    INSTR_FUNC("launch.Passive_Launch_Torpedo.Deleting") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Passive_Launch_Torpedo_EXPELLING(void *const s_, void *const p_)
{
#define THISSTATE__ EXPELLING
    INSTR_FUNC("launch.Passive_Launch_Torpedo.EXPELLING") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Passive_Launch_Torpedo_Migrating_to_Fired(void *const s_, void *const p_)
{
#define THISSTATE__ Migrating_to_Fired
    INSTR_FUNC("launch.Passive_Launch_Torpedo.Migrating_to_Fired") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Stored_Torpedo
static void Stored_Torpedo_Installing_in_Rack(void *const s_, void *const p_)
{
#define THISSTATE__ Installing_in_Rack
    INSTR_FUNC("launch.Stored_Torpedo.Installing_in_Rack") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Stored_Torpedo
static void Stored_Torpedo_Migrating_to_Loaded(void *const s_, void *const p_)
{
#define THISSTATE__ Migrating_to_Loaded
    INSTR_FUNC("launch.Stored_Torpedo.Migrating_to_Loaded") ;
    struct Stored_Torpedo *const self = (struct Stored_Torpedo *)s_ ;
    struct Stored_Torpedo_Migrating_to_Loaded_rcvd_evt {
        Tube_number Number ;
    } const *const rcvd_evt = (struct Stored_Torpedo_Migrating_to_Loaded_rcvd_evt const *)p_ ;


        // Get a reference to the superclass instance.
    ClassRefVar(Torpedo, torp) = self->R1 ;
        // Create an instance of Loaded Torpedo
    ClassRefVar(Loaded_Torpedo, ltorp) = PYCCA_newInstance(Loaded_Torpedo) ;
        // Relate the Loaded Torpedo to the Torpedo across R1.
    PYCCA_relateSubtypeByRef(torp, Torpedo, R1, ltorp, Loaded_Torpedo) ;
    ltorp->R1 = torp ;
        // Relate the Loaded Torpedo to the Tube.
    ltorp->R4 = PYCCA_refOfId(Tube, rcvd_evt->Number) ;

        // Now handle R2
    switch (torp->R5->Launch_type) {
        case Active: {
                // For Active Launch Torpedos, create a new instance.
            ClassRefVar(Active_Launch_Torpedo, altorp) =
                PYCCA_newInstance(Active_Launch_Torpedo) ;
                // Relate the Active Launch Torpedo across R2.
            PYCCA_relateSubtypeByRef(ltorp, Loaded_Torpedo, R2, altorp,
                    Active_Launch_Torpedo) ;
            altorp->R2 = ltorp ;
        }
        break ;
        case Passive: {
                // For Passive Launch Torpedos, create a new instance.
            ClassRefVar(Passive_Launch_Torpedo, pltorp) =
                PYCCA_newInstance(Passive_Launch_Torpedo) ;
                // Relate the Passive Launch Torpedo across R2.
            PYCCA_relateSubtypeByRef(ltorp, Loaded_Torpedo, R2, pltorp,
                    Passive_Launch_Torpedo) ;
            pltorp->R2 = ltorp ;
        }
        break ;
    }

    // Since this is final state, the Stored Torpedo instance is
    // deleted and since there were no references in Storage Rack back
    // to the Stored Torpedo, we don't have to destroy the instance
    // of the R3 association.
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Stored_Torpedo
static void Stored_Torpedo_STORED(void *const s_, void *const p_)
{
#define THISSTATE__ STORED
    INSTR_FUNC("launch.Stored_Torpedo.STORED") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Stored_Torpedo_MAINTENANCE(void *const s_, void *const p_)
{
#define THISSTATE__ MAINTENANCE
    INSTR_FUNC("launch.Stored_Torpedo.MAINTENANCE") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Stored_Torpedo_Removing(void *const s_, void *const p_)
{
#define THISSTATE__ Removing
    INSTR_FUNC("launch.Stored_Torpedo.Removing") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
static void Stored_Torpedo_Cancel_maintenance_interval(void *const s_, void *const p_)
{
#define THISSTATE__ Cancel_maintenance_interval
    INSTR_FUNC("launch.Stored_Torpedo.Cancel_maintenance_interval") ;

    // Include your C code for the state here.
#undef THISSTATE__
}
#undef THISCLASS__

/*
 * Domain Operation Definitions
 */

/*
 * Definition of Function to Construct Initial Instances
 */




