/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: C:/Users/andrewm/Working/modelrealization/modelstocode/mtc_source/tools/windows/tack.exe/lib/application/main.tcl, Revision: 3.6
 * Generated on: Sun Apr 16 10:49:09 PDT 2017
 */

#ifndef LUBEHARNESS_H_
#define LUBEHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void lube_harness_init(void) ;


#endif /* LUBEHARNESS_H_ */
