/*
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
 * Created by: C:/Users/andrewm/Working/modelrealization/modelstocode/mtc_source/tools/windows/pycca.exe/lib/application/pycca.tcl 
 * Created on: Sun Apr 16 10:49:08 PDT 2017
 * This is pycca version 4.3
 * ---------------------------------------------------------------
 */

#include <stdio.h>

#include <stddef.h>
#include <stdbool.h>
#include "mechs.h"

/*
 * The following macros may be used in the code to insulate the naming
 * conventions of "pycca" from the code.
 */
#define ClassRefType(c)             struct c *
#define ThisClassRefType            ClassRefType(THISCLASS__)
#define ClassRefVar(c, v)           struct c *v
#define ThisClassRefVar(v)          ClassRefVar(THISCLASS__, v)
#define ClassConstRefVar(c, v)      struct c const *v
#define ThisClassConstRefVar(v)     ClassConstRefVar(THISCLASS__, v)
#define ClassRefSetVar(c, v)        struct c **v
#define ThisClassRefSetVar(v)       ClassRefSetVar(THISCLASS__, v)
#define ClassRefConstSetVar(c, v)   struct c * const *v
#define ThisClassRefConstSetVar(v)  ClassRefConstSetVar(THISCLASS__, v)
#define ClassConstRefSetVar(c, v)   struct c const * const *v
#define ThisClassConstRefSetVar(v)  ClassConstRefSetVar(THISCLASS__, v)
#define SubCodeMember(r)            r ## __code
#define SubCodeValue(c, r, s)       c ## _ ## r ## _ ## s ## _CODE
#define SubTypesMember(r, s)        r . r ## _ ## s
#define RefCountMember(r)           r ## __count
#define SMName__(c, e, t)           c ## _ ## e ## t
#define EventNumber(c, e)           SMName__(c, e, _EVENT)
#define ThisClassEventNumber(e)     EventNumber(THISCLASS__, e)
#define PolyEventNumber(c, e)       SMName__(c, e, _POLYEVENT)
#define StateNumber(c, s)           SMName__(c, s, _STATE)
#define ThisClassStateNumber(s)     StateNumber(THISCLASS__, s)
#define SelfStateNumber             StateNumber(THISCLASS__, THISSTATE__)
#define ISName__(c)                 c ## _INITIAL_STATE
#define InitialStateNumber(c)       ISName__(c)
#define ThisClassInitialStateNumber InitialStateNumber(THISCLASS__)
#define EPName__(c, e)              struct c ## _ ## e ## _rcvd_evt
#define EventParamType(c, e)        EPName__(c, e)
#define EventParamDecl(c, e)        EPName__(c, e)
#define ThisClassEventParamDecl(e)  EventParamDecl(THISCLASS__, e)
#define CName__(c)                  (&c ## _class)
#define ClassData(c)                CName__(c)
#define ThisClassData               ClassData(THISCLASS__)
#define ExtStName__(d, c)           d ## _ ## c ## _storage
#define StName__(c)                 c ## _storage
#define BeginStorage(c)            StName__(c)
#define ThisClassBeginStorage       BeginStorage(THISCLASS__)
#define EndStorage(c)               (BeginStorage(c) + (sizeof(BeginStorage(c)) / sizeof(BeginStorage(c)[0])))
#define ThisClassEndStorage         EndStorage(THISCLASS__)
#define ExtIName__(d, c, n)         (ExtStName__(d, c, n) + c ## _ ## n ## _INSTANCE)
#define IName__(c, n)               (StName__(c) + c ## _ ## n ## _INSTANCE)
#define Instance(c, n)     IName__(c, n)
#define ThisClassInstance(n)     Instance(THISCLASS__, n)
#define IsInstInUse(i)      ((i)->common_.alloc != 0)
#define DomainName          lube
#define OpName(p, s)        p ## _ ## s
#define DomainOp(d, o)      OpName(d, o)
#define ExternalOp(o)       OpName(eop_ ## lube, o)
#define ClassOp(c, o)       OpName(c, o)
#define ThisClassOp(o)      ClassOp(THISCLASS__, o)
#define InstOp(c, o)        OpName(c, o)
#define ThisClassInstOp(o)  InstOp(THISCLASS__, o)

/*
 * Some convenience macros.
 */
#define PYCCA_generate(e, c, i, s) mechEventGenerate(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_generateSelf(e, c) PYCCA_generate(e, c, (MechInstance)self, (MechInstance)self)

#define PYCCA_generateToSelf(e) PYCCA_generateSelf(e, THISCLASS__)

#define PYCCA_generatePolymorphic(e, c, i, s) mechEventGeneratePolymorphic(PolyEventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_generateCreation(e, c, s) mechEventGenerateCreation(EventNumber(c, e), ClassData(c), (MechInstance)s)

#define PYCCA_generateDelayed(e, c, i, s, d) mechEventGenerateDelayed(EventNumber(c, e), (MechInstance)i, (MechInstance)s, d)

#define PYCCA_generateDelayedSelf(e, c, d) PYCCA_generateDelayed(e, c, (MechInstance)self, (MechInstance)self, d)

#define PYCCA_generateDelayedToSelf(e, d) PYCCA_generateDelayedSelf(e, THISCLASS__, d)

#define PYCCA_cancelDelayed(e, c, i, s) mechEventDelayCancel(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_cancelDelayedSelf(e, c) mechEventDelayCancel(EventNumber(c, e), (MechInstance)self, (MechInstance)self)

#define PYCCA_cancelDelayedToSelf(e) PYCCA_cancelDelayedSelf(e, THISCLASS__)

#define PYCCA_remainDelayed(e, c, i, s) mechEventDelayRemaining(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_remainDelayedSelf(e, c) PYCCA_remainDelayed(e, c, (MechInstance)self, (MechInstance)self)

#define PYCCA_remainDelayedToSelf(e) PYCCA_remainDelayedSelf(e, THISCLASS__)

#define PYCCA_newEvent(e, c, i, s) mechEventNew(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_newSelfEvent(e, c) mechEventNew(EventNumber(c, e), (MechInstance)self, (MechInstance)self)

#define PYCCA_newEventToSelf(e) PYCCA_newSelfEvent(e, THISCLASS__)

#define PYCCA_newPolymorphicEvent(e, c, i, s) mechPolyEventNew(PolyEventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_newCreationEvent(e, c, s) mechCreationEventNew(EventNumber(c, e), ClassData(c), (MechInstance)s)

#define PYCCA_newCreationEventForThisClass(e, s) PYCCA_newCreationEvent(e, THISCLASS__, s)

#define PYCCA_eventParam(ecb, c, e, p) ((EventParamDecl(c, e) *)(&(ecb)->eventParameters))->p

#define PYCCA_eventParamOfThisClass(ecb, e, p) PYCCA_eventParam(ecb, THISCLASS__, e, p)

#define PYCCA_postEvent(ecb) mechEventPost(ecb)

#define PYCCA_postSelfEvent(ecb) mechEventPostSelf(ecb)

#define PYCCA_postDelayedEvent(ecb, d) mechEventPostDelay(ecb, d)

#define PYCCA_createInstance(c, s) ((struct c *)mechInstCreate(ClassData(c), s))

#define PYCCA_newInstance(c)    PYCCA_createInstance(c, InitialStateNumber(c))

#define PYCCA_newInstanceOfThisClass     PYCCA_newInstance(THISCLASS__)

#define PYCCA_destroyInstance(i) (mechInstDestroy((MechInstance)i))

#define PYCCA_setToInitialState(i, c)   ((i)->common_.currentState = InitialStateNumber(c))

#define PYCCA_setToInitialStateForThisClass(i)    PYCCA_setToInitialState(i, THISCLASS__)

#define PYCCA_isSubtypeRelated(i, supc, r, subc) ((i)->SubCodeMember(r) == SubCodeValue(supc, r, subc))

#define PYCCA_unionSupertype(i, supc, r) ((struct supc *)((char *)(i) - offsetof(struct supc, r)))

#define PYCCA_unionSubtype(i, r, sub) (&((i)->SubTypesMember(r, sub)))

#define PYCCA_referenceSubtype(i, r, subc) ((struct subc *)((i)->r))

#define PYCCA_migrateSubtype(i, supc, r, subc) (i->SubCodeMember(r) = SubCodeValue(supc, r, subc))

#define PYCCA_initUnionInstance(sup, r, subc) sup->SubTypesMember(r, subc).common_.alloc = 1 ; sup->SubTypesMember(r, subc).common_.currentState = InitialStateNumber(subc) ; sup->SubTypesMember(r, subc).common_.instClass = ClassData(subc) ;

#define PYCCA_initUnionInstanceToState(sup, r, subc, st) sup->SubTypesMember(r, subc).common_.alloc = 1 ; sup->SubTypesMember(r, subc).common_.currentState = StateNumber(subc, st) ; sup->SubTypesMember(r, subc).common_.instClass = ClassData(subc) ;

#define PYCCA_forAllInst(i, c) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i)

#define PYCCA_forAllInstOfThisClass(i)   PYCCA_forAllInst(i, THISCLASS__)

#define PYCCA_forAllRelated(v, i, r) for (v = i->r ; v < i->r + i->RefCountMember(r) ; ++v)

#define PYCCA_forAllRelatedTerm(v, i, r) for (v = i->r ; *v ; ++v)

#define PYCCA_selectOneInstWhere(i, c, expr) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i) { if (IsInstInUse(i) && (expr)) {break ;}}

#define PYCCA_selectOneInstOfThisClassWhere(i, expr) PYCCA_selectOneInstWhere(i, THISCLASS__, expr) 
#define PYCCA_selectOneStaticInstWhere(i, c, expr) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i) { if ((expr)) {break ;}}

#define PYCCA_selectOneStaticInstOfThisClassWhere(i, expr) PYCCA_selectOneStaticInstWhere(i, THISCLASS__, expr)

#define PYCCA_relateSubtypeByRef(s, supc, r, t, subc) s->r = (MechInstance)t ; PYCCA_migrateSubtype(s, supc, r, subc)

#define PYCCA_relateToMany(n, o, r, m) for (n = o->r ; n < o->r + COUNTOF(o->r) ; ++n) { if (*n == NULL) { *n = m ; break ; } } assert(n < o->r + COUNTOF(o->r))

#define PYCCA_unrelateFromMany(n, o, r, m) for (n = o->r ; n < o->r + COUNTOF(o->r) ; ++n) { if (*n == m) { *n = NULL ; break ; } } assert(n < o->r + COUNTOF(o->r))

#define PYCCA_linkToMany(o, r, m) rlinkInsert(&m->r##__links, &o->r)

#define PYCCA_unlinkFromMany(m, r) rlinkRemove(&m->r##__links)

#define PYCCA_linkToInstRef(l, c, r) ((struct c *)((char *)(l) - offsetof(struct c, r##__links)))

#define PYCCA_linkToInstRefOfThisClass(l, r) PYCCA_linkToInstRef(l, THISCLASS__, r)

#define PYCCA_forAllLinkedInst(i, r, l) for (l = rlinkBegin(&i->r) ; l != rlinkEnd(&i->r) ; l = l->next)

#define PYCCA_isLinkEmpty(i, r) rlinkEmpty(&i->r)

#define PYCCA_isLinkNotEmpty(i, r) rlinkNotEmpty(&i->r)

#define PYCCA_idOfSelf              (self - ThisClassBeginStorage)

#define PYCCA_idOfRef(c, r)         ((r) - BeginStorage(c))

#define PYCCA_idOfInst(c, n)        (Instance(c, n) - BeginStorage(c))

#define PYCCA_refOfId(c, i)         (BeginStorage(c) + (i))

#define PYCCA_refOfThisClassId(i)   (ThisClassBeginStorage + (i))

#define PYCCA_checkId(c, i)         assert((i) < COUNTOF(BeginStorage(c)))

#define PYCCA_checkThisClassId(i)   assert((i) < COUNTOF(ThisClassBeginStorage))

#ifndef COUNTOF
#define COUNTOF(a)  (sizeof(a) / sizeof(a[0]))
#endif /* COUNTOF */

/*
 * Code for Domain, "lube"
 */

#define INSTRUMENT 1

/*
 * implementation prolog code
 */

    // Any additional implementation includes, etc.
    #include <assert.h>
    #include <time.h>
    #include <string.h>
    #include "lube.h"
    typedef uint32_t Seconds ;
    typedef uint32_t Duration ;
    typedef uint32_t MPa ;
    typedef char const *Name_t ;
    typedef char const *Model_Name ;
    typedef enum {
        FS_normal,
        FS_low,
        FS_verylow,
        FS_empty
    } Fluid_State ;
    /*
     * To speed testing along, we will scale the time. When converting from
     * seconds to milliseconds in dealing with delayed events, we will us a
     * factor to allow us to scale real time. By default we will cause things
     * to run 4 times faster than real time.
     */
#ifdef INSTRUMENT
#   ifndef RUNFACTOR
#       define  RUNFACTOR 4UL
#   endif /* RUNFACTOR */
#   define SecsToDelayTime(s)   ((s) * (1000UL / RUNFACTOR))
#   define DelayTimeToSecs(d)   ((d) / (1000UL / RUNFACTOR))
#   else
#   define SecsToDelayTime(s)   ((s) * 1000UL)
#   define DelayTimeToSecs(d)   ((d) / 1000UL)
#endif /* INSTRUMENT */


#ifdef INSTRUMENT
#   ifndef INSTR_FUNC
#       ifdef TACK
#           include "harness.h"
#           define INSTR_FUNC(s) harness_stub_printf("instrument", "func %s file %s line %u", (s), __FILE__, __LINE__)
#       else
#           define INSTR_FUNC(s) printf("%s: %s %d\n", (s), __FILE__, __LINE__)
#       endif /* TACK */
#   endif /* INSTR_FUNC */
#endif /* INSTRUMENT */

/*
 * External Operations Declarations
 */
extern void eop_lube_UI_Deactivated(InstId_t sessionId) ;
extern void eop_lube_App_Error(char const *Msg) ;
extern void eop_lube_SIO_Inject(InstId_t injectorId) ;
extern void eop_lube_SIO_Stop_injecting(InstId_t injectorId) ;
extern void eop_lube_SIO_Start_monitoring(InstId_t injectorId) ;
extern void eop_lube_SIO_Stop_monitoring(InstId_t injectorId) ;
extern void eop_lube_ALARM_Set_pressure_error(InstId_t injectorId) ;
extern void eop_lube_ALARM_Set_dissipation_error(InstId_t injectorId) ;
extern void eop_lube_ALARM_Clear_dissipation_error(InstId_t injectorId) ;
extern void eop_lube_ALARM_Set_lube_level_very_low(InstId_t reservoirId) ;
extern void eop_lube_ALARM_Clear_lube_level_very_low(InstId_t reservoirId) ;
extern void eop_lube_ALARM_Set_lube_level_low(InstId_t reservoirId) ;
extern void eop_lube_ALARM_Clear_lube_level_low(InstId_t reservoirId) ;
extern void eop_lube_ALARM_Set_lube_level_empty(InstId_t reservoirId) ;
extern void eop_lube_ALARM_Clear_lube_level_empty(InstId_t reservoirId) ;


/*
 * State Numbering
 */
/*
 * State Numbers for Class, "Injector"
 */
#define Injector_Start_injection_STATE 0
#define Injector_BUILDING_PRESSURE_STATE 1
#define Injector_INJECTING_AT_PRESSURE_STATE 2
#define Injector_Not_enough_pressure_STATE 3
#define Injector_Cancel_injection_STATE 4
#define Injector_Completed_good_injection_STATE 5
#define Injector_Quit_low_pressure_injection_STATE 6
#define Injector_Clear_error_and_check_interlock_STATE 7
#define Injector_SLEEPING_STATE 8
#define Injector_INITIAL_STATE 8
#define Injector_Initiate_monitoring_STATE 9
#define Injector_MONITORING_STATE 10
#define Injector_Set_dissipation_error_STATE 11
/*
 * State Numbers for Class, "Autocycle_Session"
 */
#define Autocycle_Session_Creating_STATE 1
#define Autocycle_Session_INITIAL_STATE 1
#define Autocycle_Session_NOT_ACTIVE_STATE 2
#define Autocycle_Session_Initialize_STATE 3
#define Autocycle_Session_WAIT_INTERVAL_STATE 4
#define Autocycle_Session_Cancel_wait_interval_STATE 5
#define Autocycle_Session_WAIT_SUSPENDED_STATE 6
#define Autocycle_Session_MONITOR_INTERVAL_STATE 7
#define Autocycle_Session_Cancel_monitor_interval_STATE 8
#define Autocycle_Session_MONITOR_SUSPENDED_STATE 9
#define Autocycle_Session_LUBE_INTERVAL_STATE 10
#define Autocycle_Session_CANCELING_LUBRICATION_STATE 11
#define Autocycle_Session_Normal_lubrication_STATE 12
#define Autocycle_Session_LOW_PRESSURE_LUBRICATION_STATE 13
#define Autocycle_Session_Count_cycle_STATE 14
#define Autocycle_Session_Interrupted_cycle_count_STATE 15
#define Autocycle_Session_Spawn_new_session_STATE 16
/*
 * State Numbers for Class, "Reservoir"
 */
#define Reservoir_NORMAL_STATE 0
#define Reservoir_INITIAL_STATE 0
#define Reservoir_LOW_STATE 1
#define Reservoir_VERY_LOW_STATE 2
#define Reservoir_EMPTY_STATE 3
/*
 * Pseudo initial states for inactive classes.
 */
#define Lubrication_Schedule_INITIAL_STATE 0
#define Injector_Design_INITIAL_STATE 0
#define Machinery_INITIAL_STATE 0

/*
 * Event Numbering
 */
/*
 * Event Numbers for Class, "Injector"
 */
#define Injector_Above_dissipation_pressure_EVENT 0
#define Injector_Above_inject_pressure_EVENT 1
#define Injector_Below_inject_pressure_EVENT 2
#define Injector_Good_injection_EVENT 3
#define Injector_Injection_canceled_EVENT 4
#define Injector_Keep_monitoring_EVENT 5
#define Injector_Locked_out_EVENT 6
#define Injector_Monitor_EVENT 7
#define Injector_OK_to_start_EVENT 8
#define Injector_Start_EVENT 9
#define Injector_Stop_EVENT 10
#define Injector_Stopped_EVENT 11
#define Injector_Wait_for_inject_pressure_EVENT 12
#define Injector_Wakeup_EVENT 13
/*
 * Event Numbers for Class, "Autocycle_Session"
 */
#define Autocycle_Session_Activate_EVENT 0
#define Autocycle_Session_Activated_EVENT 1
#define Autocycle_Session_Change_schedule_EVENT 2
#define Autocycle_Session_Count_as_normal_EVENT 3
#define Autocycle_Session_Created_EVENT 4
#define Autocycle_Session_Cycle_interrupted_EVENT 5
#define Autocycle_Session_Deactivate_EVENT 6
#define Autocycle_Session_Get_ready_to_lubricate_EVENT 7
#define Autocycle_Session_Good_injection_EVENT 8
#define Autocycle_Session_Locked_out_EVENT 9
#define Autocycle_Session_Low_pressure_injection_EVENT 10
#define Autocycle_Session_Lube_interval_ended_EVENT 11
#define Autocycle_Session_Lubricate_EVENT 12
#define Autocycle_Session_Monitor_interval_canceled_EVENT 13
#define Autocycle_Session_New_session_EVENT 14
#define Autocycle_Session_Next_cycle_EVENT 15
#define Autocycle_Session_Resume_EVENT 16
#define Autocycle_Session_Stop_EVENT 17
#define Autocycle_Session_Suspend_EVENT 18
#define Autocycle_Session_Wait_interval_canceled_EVENT 19
/*
 * Event Numbers for Class, "Reservoir"
 */
#define Reservoir_Low_injection_pressure_EVENT 0
#define Reservoir_Low_lube_level_EVENT 1
#define Reservoir_Normal_lube_level_EVENT 2
#define Reservoir_Too_many_low_lube_cycles_EVENT 3

/*
 * Subtype Numbering
 */

/*
 * Offsets to named instances
 */
#define Lubrication_Schedule_gearbox_INSTANCE 0
#define Lubrication_Schedule_generator_INSTANCE 1
#define Lubrication_Schedule_shaft_INSTANCE 2
#define Lubrication_Schedule_test2_INSTANCE 3
#define Injector_Design_ihn4_INSTANCE 0
#define Injector_Design_ix77b_INSTANCE 1
#define Injector_in1_INSTANCE 0
#define Injector_in2_INSTANCE 1
#define Injector_in3_INSTANCE 2
#define Autocycle_Session_acs1_INSTANCE 0
#define Autocycle_Session_acs2_INSTANCE 1
#define Autocycle_Session_acs3_INSTANCE 2
#define Machinery_m1_INSTANCE 0
#define Machinery_m2_INSTANCE 1
#define Machinery_m3_INSTANCE 2
#define Reservoir_res1_INSTANCE 0
#define Reservoir_res2_INSTANCE 1

/*
 * Forward class structure declarations
 */
struct Lubrication_Schedule ;
struct Injector_Design ;
struct Injector ;
struct Autocycle_Session ;
struct Machinery ;
struct Reservoir ;

/*
 * Class structure definitions
 */
struct Lubrication_Schedule {
    Name_t Name ;
    Duration Wait_interval ;
    Duration Monitor_interval ;
    Count Max_low_lube_cycles ;
    bool Default_continuous_operation ;
    Count Default_max_cycles ;
} ;
struct Injector_Design {
    Model_Name Model ;
    MPa Min_delivery_pressure ;
    MPa Max_system_pressure ;
    MPa Max_dissipation_pressure ;
    Seconds Delivery_window ;
    Seconds Good_injection_duration ;
} ;
struct Injector {
    struct mechinstance common_ ; // must be first !
    MPa Pressure ;
    bool Dissipation_error ;
    bool Injecting ;
    struct Injector_Design *R4 ;
    struct Machinery *R5 ;
    struct Lubrication_Schedule *R1 ;
    struct Autocycle_Session *R2 ;
    struct Reservoir *R3 ;
} ;
struct Autocycle_Session {
    struct mechinstance common_ ; // must be first !
    Count Cycles_requested ;
    bool Continuous_operation ;
    Count Failed_cycles ;
    Count Cycles_since_activation ;
    bool Lubricating ;
    bool Active ;
    bool Deactivate ;
    bool Suspend_requested ;
    Seconds Wait_time_remaining ;
    struct Injector *R2_INJ ;
    struct Lubrication_Schedule *R2_LBS ;
} ;
struct Machinery {
    bool Locked_out ;
    struct Injector *const*const R5 ;
    unsigned R5__count ;
} ;
struct Reservoir {
    struct mechinstance common_ ; // must be first !
    Fluid_State Level ;
    struct Injector *const*const R3 ;
    unsigned R3__count ;
} ;

/*
 * Event Parameter Structure Definitions
 */
struct Autocycle_Session_Activate_rcvd_evt {
    bool continuous ;
    Count count ;
} ;
struct Autocycle_Session_Change_schedule_rcvd_evt {
    char const *schedule ;
} ;
struct Autocycle_Session_New_session_rcvd_evt {
    char const *schedule ;
    unsigned injector ;
} ;


/*
 * Forward Operation Function Declarations
 */
static struct Lubrication_Schedule * Lubrication_Schedule_findByName(char const *name) ;
static void Injector_Max_system_pressure(struct Injector *self) ;
static void Autocycle_Session_Deactivate(struct Autocycle_Session *self) ;
static void Autocycle_Session_Suspend(struct Autocycle_Session *self) ;
static void Machinery_Unlock(struct Machinery *self) ;
static void Machinery_Lock(struct Machinery *self) ;

/*
 * Forward Declarations of Class Constructors
 */

/*
 * Forward Declarations of Class Destructors
 */

/*
 * Forward Declarations of State Action Functions
 */
static void Autocycle_Session_Creating(void *const s_, void *const p_) ;
static void Autocycle_Session_Spawn_new_session(void *const s_, void *const p_) ;
static void Autocycle_Session_Initialize(void *const s_, void *const p_) ;
static void Autocycle_Session_CANCELING_LUBRICATION(void *const s_, void *const p_) ;
static void Autocycle_Session_Cancel_monitor_interval(void *const s_, void *const p_) ;
static void Autocycle_Session_Cancel_wait_interval(void *const s_, void *const p_) ;
static void Autocycle_Session_Count_cycle(void *const s_, void *const p_) ;
static void Autocycle_Session_Interrupted_cycle_count(void *const s_, void *const p_) ;
static void Autocycle_Session_LOW_PRESSURE_LUBRICATION(void *const s_, void *const p_) ;
static void Autocycle_Session_LUBE_INTERVAL(void *const s_, void *const p_) ;
static void Autocycle_Session_MONITOR_INTERVAL(void *const s_, void *const p_) ;
static void Autocycle_Session_MONITOR_SUSPENDED(void *const s_, void *const p_) ;
static void Autocycle_Session_NOT_ACTIVE(void *const s_, void *const p_) ;
static void Autocycle_Session_Normal_lubrication(void *const s_, void *const p_) ;
static void Autocycle_Session_WAIT_INTERVAL(void *const s_, void *const p_) ;
static void Autocycle_Session_WAIT_SUSPENDED(void *const s_, void *const p_) ;
static void Injector_BUILDING_PRESSURE(void *const s_, void *const p_) ;
static void Injector_Cancel_injection(void *const s_, void *const p_) ;
static void Injector_Clear_error_and_check_interlock(void *const s_, void *const p_) ;
static void Injector_Completed_good_injection(void *const s_, void *const p_) ;
static void Injector_INJECTING_AT_PRESSURE(void *const s_, void *const p_) ;
static void Injector_Initiate_monitoring(void *const s_, void *const p_) ;
static void Injector_MONITORING(void *const s_, void *const p_) ;
static void Injector_Not_enough_pressure(void *const s_, void *const p_) ;
static void Injector_Quit_low_pressure_injection(void *const s_, void *const p_) ;
static void Injector_SLEEPING(void *const s_, void *const p_) ;
static void Injector_Set_dissipation_error(void *const s_, void *const p_) ;
static void Injector_Start_injection(void *const s_, void *const p_) ;
static void Reservoir_EMPTY(void *const s_, void *const p_) ;
static void Reservoir_LOW(void *const s_, void *const p_) ;
static void Reservoir_NORMAL(void *const s_, void *const p_) ;
static void Reservoir_VERY_LOW(void *const s_, void *const p_) ;

/*
 * Domain Operations External Declarations
 */
extern void lube_init(void) ;
extern void lube_Suspend_Autocycle_Session(InstId_t sessionId) ;
extern void lube_Injector_max_pressure(InstId_t injId) ;
extern void lube_Lock_Machinery(InstId_t machineId) ;
extern void lube_Unlock_Machinery(InstId_t machineId) ;

/*
 * Declaration of Function to Construct Initial Instances
 */

/*
 * Forward Instance Storage Declarations
 */
static struct Lubrication_Schedule Lubrication_Schedule_storage[] ;
static struct Injector_Design Injector_Design_storage[] ;
static struct Injector Injector_storage[] ;
static struct Autocycle_Session Autocycle_Session_storage[] ;
static struct Machinery Machinery_storage[] ;
static struct Reservoir Reservoir_storage[] ;


/*
 * Instance Allocation Block Definitions
 */
static struct installocblock Autocycle_Session_iab = {
    .storageStart = Autocycle_Session_storage,
    .storageFinish = Autocycle_Session_storage + 3,
    .storageLast = Autocycle_Session_storage + 2,
    .allocCounter = 3,
    .instanceSize = sizeof(struct Autocycle_Session),
    .construct = NULL,
    .destruct = NULL
} ;

/*
 * AODB for Class, "Injector"
 */
static PtrActionFunction const Injector_acttbl[] = {
    Injector_Start_injection,
    Injector_BUILDING_PRESSURE,
    Injector_INJECTING_AT_PRESSURE,
    Injector_Not_enough_pressure,
    Injector_Cancel_injection,
    Injector_Completed_good_injection,
    Injector_Quit_low_pressure_injection,
    Injector_Clear_error_and_check_interlock,
    Injector_SLEEPING,
    Injector_Initiate_monitoring,
    Injector_MONITORING,
    Injector_Set_dissipation_error,
} ;
static StateCode const Injector_transtbl[] = {
    MECH_STATECODE_CH, // Start_injection - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Start_injection - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Start_injection - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Start_injection - Good_injection -> CH
    MECH_STATECODE_CH, // Start_injection - Injection_canceled -> CH
    MECH_STATECODE_CH, // Start_injection - Keep_monitoring -> CH
    MECH_STATECODE_CH, // Start_injection - Locked_out -> CH
    MECH_STATECODE_CH, // Start_injection - Monitor -> CH
    MECH_STATECODE_CH, // Start_injection - OK_to_start -> CH
    MECH_STATECODE_CH, // Start_injection - Start -> CH
    MECH_STATECODE_CH, // Start_injection - Stop -> CH
    MECH_STATECODE_CH, // Start_injection - Stopped -> CH
    1, // Start_injection - Wait_for_inject_pressure -> BUILDING_PRESSURE
    MECH_STATECODE_CH, // Start_injection - Wakeup -> CH
    MECH_STATECODE_IG, // BUILDING_PRESSURE - Above_dissipation_pressure -> IG
    2, // BUILDING_PRESSURE - Above_inject_pressure -> INJECTING_AT_PRESSURE
    MECH_STATECODE_IG, // BUILDING_PRESSURE - Below_inject_pressure -> IG
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Good_injection -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Injection_canceled -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Keep_monitoring -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Locked_out -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Monitor -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - OK_to_start -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Start -> CH
    6, // BUILDING_PRESSURE - Stop -> Quit_low_pressure_injection
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Stopped -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // BUILDING_PRESSURE - Wakeup -> CH
    MECH_STATECODE_IG, // INJECTING_AT_PRESSURE - Above_dissipation_pressure -> IG
    MECH_STATECODE_IG, // INJECTING_AT_PRESSURE - Above_inject_pressure -> IG
    3, // INJECTING_AT_PRESSURE - Below_inject_pressure -> Not_enough_pressure
    5, // INJECTING_AT_PRESSURE - Good_injection -> Completed_good_injection
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Injection_canceled -> CH
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Keep_monitoring -> CH
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Locked_out -> CH
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Monitor -> CH
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - OK_to_start -> CH
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Start -> CH
    4, // INJECTING_AT_PRESSURE - Stop -> Cancel_injection
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Stopped -> CH
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // INJECTING_AT_PRESSURE - Wakeup -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Good_injection -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Injection_canceled -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Keep_monitoring -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Locked_out -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Monitor -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - OK_to_start -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Start -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Stop -> CH
    MECH_STATECODE_CH, // Not_enough_pressure - Stopped -> CH
    1, // Not_enough_pressure - Wait_for_inject_pressure -> BUILDING_PRESSURE
    MECH_STATECODE_CH, // Not_enough_pressure - Wakeup -> CH
    MECH_STATECODE_CH, // Cancel_injection - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Cancel_injection - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Cancel_injection - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Cancel_injection - Good_injection -> CH
    6, // Cancel_injection - Injection_canceled -> Quit_low_pressure_injection
    MECH_STATECODE_CH, // Cancel_injection - Keep_monitoring -> CH
    MECH_STATECODE_CH, // Cancel_injection - Locked_out -> CH
    MECH_STATECODE_CH, // Cancel_injection - Monitor -> CH
    MECH_STATECODE_CH, // Cancel_injection - OK_to_start -> CH
    MECH_STATECODE_CH, // Cancel_injection - Start -> CH
    MECH_STATECODE_CH, // Cancel_injection - Stop -> CH
    MECH_STATECODE_CH, // Cancel_injection - Stopped -> CH
    MECH_STATECODE_CH, // Cancel_injection - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // Cancel_injection - Wakeup -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Good_injection -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Injection_canceled -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Keep_monitoring -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Locked_out -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Monitor -> CH
    MECH_STATECODE_CH, // Completed_good_injection - OK_to_start -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Start -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Stop -> CH
    8, // Completed_good_injection - Stopped -> SLEEPING
    MECH_STATECODE_CH, // Completed_good_injection - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // Completed_good_injection - Wakeup -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Good_injection -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Injection_canceled -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Keep_monitoring -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Locked_out -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Monitor -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - OK_to_start -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Start -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Stop -> CH
    8, // Quit_low_pressure_injection - Stopped -> SLEEPING
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // Quit_low_pressure_injection - Wakeup -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Good_injection -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Injection_canceled -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Keep_monitoring -> CH
    8, // Clear_error_and_check_interlock - Locked_out -> SLEEPING
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Monitor -> CH
    0, // Clear_error_and_check_interlock - OK_to_start -> Start_injection
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Start -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Stop -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Stopped -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // Clear_error_and_check_interlock - Wakeup -> CH
    MECH_STATECODE_IG, // SLEEPING - Above_dissipation_pressure -> IG
    MECH_STATECODE_IG, // SLEEPING - Above_inject_pressure -> IG
    MECH_STATECODE_IG, // SLEEPING - Below_inject_pressure -> IG
    MECH_STATECODE_CH, // SLEEPING - Good_injection -> CH
    MECH_STATECODE_CH, // SLEEPING - Injection_canceled -> CH
    MECH_STATECODE_CH, // SLEEPING - Keep_monitoring -> CH
    MECH_STATECODE_CH, // SLEEPING - Locked_out -> CH
    MECH_STATECODE_CH, // SLEEPING - Monitor -> CH
    MECH_STATECODE_CH, // SLEEPING - OK_to_start -> CH
    MECH_STATECODE_CH, // SLEEPING - Start -> CH
    MECH_STATECODE_IG, // SLEEPING - Stop -> IG
    MECH_STATECODE_CH, // SLEEPING - Stopped -> CH
    MECH_STATECODE_CH, // SLEEPING - Wait_for_inject_pressure -> CH
    9, // SLEEPING - Wakeup -> Initiate_monitoring
    MECH_STATECODE_CH, // Initiate_monitoring - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Good_injection -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Injection_canceled -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Keep_monitoring -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Locked_out -> CH
    10, // Initiate_monitoring - Monitor -> MONITORING
    MECH_STATECODE_CH, // Initiate_monitoring - OK_to_start -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Start -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Stop -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Stopped -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // Initiate_monitoring - Wakeup -> CH
    11, // MONITORING - Above_dissipation_pressure -> Set_dissipation_error
    MECH_STATECODE_IG, // MONITORING - Above_inject_pressure -> IG
    MECH_STATECODE_IG, // MONITORING - Below_inject_pressure -> IG
    MECH_STATECODE_CH, // MONITORING - Good_injection -> CH
    MECH_STATECODE_CH, // MONITORING - Injection_canceled -> CH
    MECH_STATECODE_CH, // MONITORING - Keep_monitoring -> CH
    MECH_STATECODE_CH, // MONITORING - Locked_out -> CH
    MECH_STATECODE_CH, // MONITORING - Monitor -> CH
    MECH_STATECODE_CH, // MONITORING - OK_to_start -> CH
    7, // MONITORING - Start -> Clear_error_and_check_interlock
    8, // MONITORING - Stop -> SLEEPING
    MECH_STATECODE_CH, // MONITORING - Stopped -> CH
    MECH_STATECODE_CH, // MONITORING - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // MONITORING - Wakeup -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Above_dissipation_pressure -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Above_inject_pressure -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Below_inject_pressure -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Good_injection -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Injection_canceled -> CH
    10, // Set_dissipation_error - Keep_monitoring -> MONITORING
    MECH_STATECODE_CH, // Set_dissipation_error - Locked_out -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Monitor -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - OK_to_start -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Start -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Stop -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Stopped -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Wait_for_inject_pressure -> CH
    MECH_STATECODE_CH, // Set_dissipation_error - Wakeup -> CH
} ;
static struct objectdispatchblock const Injector_odb = {
    .stateCount = 12,
    .eventCount = 14,
    .transitionTable = Injector_transtbl,
    .actionTable = Injector_acttbl,
    .finalStates = NULL
} ;
/*
 * AODB for Class, "Autocycle_Session"
 */
static bool const Autocycle_Session_fs[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, } ;
static PtrActionFunction const Autocycle_Session_acttbl[] = {
    NULL,
    Autocycle_Session_Creating,
    Autocycle_Session_NOT_ACTIVE,
    Autocycle_Session_Initialize,
    Autocycle_Session_WAIT_INTERVAL,
    Autocycle_Session_Cancel_wait_interval,
    Autocycle_Session_WAIT_SUSPENDED,
    Autocycle_Session_MONITOR_INTERVAL,
    Autocycle_Session_Cancel_monitor_interval,
    Autocycle_Session_MONITOR_SUSPENDED,
    Autocycle_Session_LUBE_INTERVAL,
    Autocycle_Session_CANCELING_LUBRICATION,
    Autocycle_Session_Normal_lubrication,
    Autocycle_Session_LOW_PRESSURE_LUBRICATION,
    Autocycle_Session_Count_cycle,
    Autocycle_Session_Interrupted_cycle_count,
    Autocycle_Session_Spawn_new_session,
} ;
static StateCode const Autocycle_Session_transtbl[] = {
    MECH_STATECODE_CH, // . - Activate -> CH
    MECH_STATECODE_CH, // . - Activated -> CH
    MECH_STATECODE_CH, // . - Change_schedule -> CH
    MECH_STATECODE_CH, // . - Count_as_normal -> CH
    MECH_STATECODE_CH, // . - Created -> CH
    MECH_STATECODE_CH, // . - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // . - Deactivate -> CH
    MECH_STATECODE_CH, // . - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // . - Good_injection -> CH
    MECH_STATECODE_CH, // . - Locked_out -> CH
    MECH_STATECODE_CH, // . - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // . - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // . - Lubricate -> CH
    MECH_STATECODE_CH, // . - Monitor_interval_canceled -> CH
    1, // . - New_session -> Creating
    MECH_STATECODE_CH, // . - Next_cycle -> CH
    MECH_STATECODE_CH, // . - Resume -> CH
    MECH_STATECODE_CH, // . - Stop -> CH
    MECH_STATECODE_CH, // . - Suspend -> CH
    MECH_STATECODE_CH, // . - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Creating - Activate -> CH
    MECH_STATECODE_CH, // Creating - Activated -> CH
    MECH_STATECODE_CH, // Creating - Change_schedule -> CH
    MECH_STATECODE_CH, // Creating - Count_as_normal -> CH
    2, // Creating - Created -> NOT_ACTIVE
    MECH_STATECODE_CH, // Creating - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // Creating - Deactivate -> CH
    MECH_STATECODE_CH, // Creating - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Creating - Good_injection -> CH
    MECH_STATECODE_CH, // Creating - Locked_out -> CH
    MECH_STATECODE_CH, // Creating - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Creating - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Creating - Lubricate -> CH
    MECH_STATECODE_CH, // Creating - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // Creating - New_session -> CH
    MECH_STATECODE_CH, // Creating - Next_cycle -> CH
    MECH_STATECODE_CH, // Creating - Resume -> CH
    MECH_STATECODE_CH, // Creating - Stop -> CH
    MECH_STATECODE_CH, // Creating - Suspend -> CH
    MECH_STATECODE_CH, // Creating - Wait_interval_canceled -> CH
    3, // NOT_ACTIVE - Activate -> Initialize
    MECH_STATECODE_CH, // NOT_ACTIVE - Activated -> CH
    16, // NOT_ACTIVE - Change_schedule -> Spawn_new_session
    MECH_STATECODE_CH, // NOT_ACTIVE - Count_as_normal -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Created -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Cycle_interrupted -> CH
    MECH_STATECODE_IG, // NOT_ACTIVE - Deactivate -> IG
    MECH_STATECODE_CH, // NOT_ACTIVE - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Good_injection -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Locked_out -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Lubricate -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - New_session -> CH
    MECH_STATECODE_CH, // NOT_ACTIVE - Next_cycle -> CH
    MECH_STATECODE_IG, // NOT_ACTIVE - Resume -> IG
    MECH_STATECODE_CH, // NOT_ACTIVE - Stop -> CH
    MECH_STATECODE_IG, // NOT_ACTIVE - Suspend -> IG
    MECH_STATECODE_CH, // NOT_ACTIVE - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Initialize - Activate -> CH
    4, // Initialize - Activated -> WAIT_INTERVAL
    MECH_STATECODE_CH, // Initialize - Change_schedule -> CH
    MECH_STATECODE_CH, // Initialize - Count_as_normal -> CH
    MECH_STATECODE_CH, // Initialize - Created -> CH
    MECH_STATECODE_CH, // Initialize - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // Initialize - Deactivate -> CH
    MECH_STATECODE_CH, // Initialize - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Initialize - Good_injection -> CH
    2, // Initialize - Locked_out -> NOT_ACTIVE
    MECH_STATECODE_CH, // Initialize - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Initialize - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Initialize - Lubricate -> CH
    MECH_STATECODE_CH, // Initialize - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // Initialize - New_session -> CH
    MECH_STATECODE_CH, // Initialize - Next_cycle -> CH
    MECH_STATECODE_CH, // Initialize - Resume -> CH
    MECH_STATECODE_CH, // Initialize - Stop -> CH
    MECH_STATECODE_CH, // Initialize - Suspend -> CH
    MECH_STATECODE_CH, // Initialize - Wait_interval_canceled -> CH
    MECH_STATECODE_IG, // WAIT_INTERVAL - Activate -> IG
    MECH_STATECODE_CH, // WAIT_INTERVAL - Activated -> CH
    MECH_STATECODE_IG, // WAIT_INTERVAL - Change_schedule -> IG
    MECH_STATECODE_CH, // WAIT_INTERVAL - Count_as_normal -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Created -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Cycle_interrupted -> CH
    5, // WAIT_INTERVAL - Deactivate -> Cancel_wait_interval
    7, // WAIT_INTERVAL - Get_ready_to_lubricate -> MONITOR_INTERVAL
    MECH_STATECODE_CH, // WAIT_INTERVAL - Good_injection -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Locked_out -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Lubricate -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - New_session -> CH
    MECH_STATECODE_CH, // WAIT_INTERVAL - Next_cycle -> CH
    MECH_STATECODE_IG, // WAIT_INTERVAL - Resume -> IG
    MECH_STATECODE_CH, // WAIT_INTERVAL - Stop -> CH
    6, // WAIT_INTERVAL - Suspend -> WAIT_SUSPENDED
    MECH_STATECODE_CH, // WAIT_INTERVAL - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Activate -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Activated -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Change_schedule -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Count_as_normal -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Created -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Deactivate -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Good_injection -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Locked_out -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Lubricate -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - New_session -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Next_cycle -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Resume -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Stop -> CH
    MECH_STATECODE_CH, // Cancel_wait_interval - Suspend -> CH
    2, // Cancel_wait_interval - Wait_interval_canceled -> NOT_ACTIVE
    MECH_STATECODE_IG, // WAIT_SUSPENDED - Activate -> IG
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Activated -> CH
    MECH_STATECODE_IG, // WAIT_SUSPENDED - Change_schedule -> IG
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Count_as_normal -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Created -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Cycle_interrupted -> CH
    2, // WAIT_SUSPENDED - Deactivate -> NOT_ACTIVE
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Good_injection -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Locked_out -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Lubricate -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - New_session -> CH
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Next_cycle -> CH
    4, // WAIT_SUSPENDED - Resume -> WAIT_INTERVAL
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Stop -> CH
    MECH_STATECODE_IG, // WAIT_SUSPENDED - Suspend -> IG
    MECH_STATECODE_CH, // WAIT_SUSPENDED - Wait_interval_canceled -> CH
    MECH_STATECODE_IG, // MONITOR_INTERVAL - Activate -> IG
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Activated -> CH
    MECH_STATECODE_IG, // MONITOR_INTERVAL - Change_schedule -> IG
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Count_as_normal -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Created -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Cycle_interrupted -> CH
    8, // MONITOR_INTERVAL - Deactivate -> Cancel_monitor_interval
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Good_injection -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Locked_out -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Lube_interval_ended -> CH
    10, // MONITOR_INTERVAL - Lubricate -> LUBE_INTERVAL
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - New_session -> CH
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Next_cycle -> CH
    MECH_STATECODE_IG, // MONITOR_INTERVAL - Resume -> IG
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Stop -> CH
    9, // MONITOR_INTERVAL - Suspend -> MONITOR_SUSPENDED
    MECH_STATECODE_CH, // MONITOR_INTERVAL - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Activate -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Activated -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Change_schedule -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Count_as_normal -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Created -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Deactivate -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Good_injection -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Locked_out -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Lubricate -> CH
    2, // Cancel_monitor_interval - Monitor_interval_canceled -> NOT_ACTIVE
    MECH_STATECODE_CH, // Cancel_monitor_interval - New_session -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Next_cycle -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Resume -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Stop -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Suspend -> CH
    MECH_STATECODE_CH, // Cancel_monitor_interval - Wait_interval_canceled -> CH
    MECH_STATECODE_IG, // MONITOR_SUSPENDED - Activate -> IG
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Activated -> CH
    MECH_STATECODE_IG, // MONITOR_SUSPENDED - Change_schedule -> IG
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Count_as_normal -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Created -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Cycle_interrupted -> CH
    2, // MONITOR_SUSPENDED - Deactivate -> NOT_ACTIVE
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Good_injection -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Locked_out -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Lubricate -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - New_session -> CH
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Next_cycle -> CH
    7, // MONITOR_SUSPENDED - Resume -> MONITOR_INTERVAL
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Stop -> CH
    MECH_STATECODE_IG, // MONITOR_SUSPENDED - Suspend -> IG
    MECH_STATECODE_CH, // MONITOR_SUSPENDED - Wait_interval_canceled -> CH
    MECH_STATECODE_IG, // LUBE_INTERVAL - Activate -> IG
    MECH_STATECODE_CH, // LUBE_INTERVAL - Activated -> CH
    MECH_STATECODE_IG, // LUBE_INTERVAL - Change_schedule -> IG
    MECH_STATECODE_CH, // LUBE_INTERVAL - Count_as_normal -> CH
    MECH_STATECODE_CH, // LUBE_INTERVAL - Created -> CH
    MECH_STATECODE_CH, // LUBE_INTERVAL - Cycle_interrupted -> CH
    11, // LUBE_INTERVAL - Deactivate -> CANCELING_LUBRICATION
    MECH_STATECODE_CH, // LUBE_INTERVAL - Get_ready_to_lubricate -> CH
    12, // LUBE_INTERVAL - Good_injection -> Normal_lubrication
    MECH_STATECODE_CH, // LUBE_INTERVAL - Locked_out -> CH
    MECH_STATECODE_CH, // LUBE_INTERVAL - Low_pressure_injection -> CH
    13, // LUBE_INTERVAL - Lube_interval_ended -> LOW_PRESSURE_LUBRICATION
    MECH_STATECODE_CH, // LUBE_INTERVAL - Lubricate -> CH
    MECH_STATECODE_CH, // LUBE_INTERVAL - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // LUBE_INTERVAL - New_session -> CH
    MECH_STATECODE_CH, // LUBE_INTERVAL - Next_cycle -> CH
    MECH_STATECODE_IG, // LUBE_INTERVAL - Resume -> IG
    MECH_STATECODE_CH, // LUBE_INTERVAL - Stop -> CH
    MECH_STATECODE_IG, // LUBE_INTERVAL - Suspend -> IG
    MECH_STATECODE_CH, // LUBE_INTERVAL - Wait_interval_canceled -> CH
    MECH_STATECODE_IG, // CANCELING_LUBRICATION - Activate -> IG
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Activated -> CH
    MECH_STATECODE_IG, // CANCELING_LUBRICATION - Change_schedule -> IG
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Count_as_normal -> CH
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Created -> CH
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Cycle_interrupted -> CH
    MECH_STATECODE_IG, // CANCELING_LUBRICATION - Deactivate -> IG
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Get_ready_to_lubricate -> CH
    14, // CANCELING_LUBRICATION - Good_injection -> Count_cycle
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Locked_out -> CH
    15, // CANCELING_LUBRICATION - Low_pressure_injection -> Interrupted_cycle_count
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Lubricate -> CH
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - New_session -> CH
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Next_cycle -> CH
    MECH_STATECODE_IG, // CANCELING_LUBRICATION - Resume -> IG
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Stop -> CH
    MECH_STATECODE_IG, // CANCELING_LUBRICATION - Suspend -> IG
    MECH_STATECODE_CH, // CANCELING_LUBRICATION - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Activate -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Activated -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Change_schedule -> CH
    14, // Normal_lubrication - Count_as_normal -> Count_cycle
    MECH_STATECODE_CH, // Normal_lubrication - Created -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Deactivate -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Good_injection -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Locked_out -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Lubricate -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // Normal_lubrication - New_session -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Next_cycle -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Resume -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Stop -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Suspend -> CH
    MECH_STATECODE_CH, // Normal_lubrication - Wait_interval_canceled -> CH
    MECH_STATECODE_IG, // LOW_PRESSURE_LUBRICATION - Activate -> IG
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Activated -> CH
    MECH_STATECODE_IG, // LOW_PRESSURE_LUBRICATION - Change_schedule -> IG
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Count_as_normal -> CH
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Created -> CH
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Cycle_interrupted -> CH
    MECH_STATECODE_IG, // LOW_PRESSURE_LUBRICATION - Deactivate -> IG
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Get_ready_to_lubricate -> CH
    14, // LOW_PRESSURE_LUBRICATION - Good_injection -> Count_cycle
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Locked_out -> CH
    14, // LOW_PRESSURE_LUBRICATION - Low_pressure_injection -> Count_cycle
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Lubricate -> CH
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - New_session -> CH
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Next_cycle -> CH
    MECH_STATECODE_IG, // LOW_PRESSURE_LUBRICATION - Resume -> IG
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Stop -> CH
    MECH_STATECODE_IG, // LOW_PRESSURE_LUBRICATION - Suspend -> IG
    MECH_STATECODE_CH, // LOW_PRESSURE_LUBRICATION - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Count_cycle - Activate -> CH
    MECH_STATECODE_CH, // Count_cycle - Activated -> CH
    MECH_STATECODE_CH, // Count_cycle - Change_schedule -> CH
    MECH_STATECODE_CH, // Count_cycle - Count_as_normal -> CH
    MECH_STATECODE_CH, // Count_cycle - Created -> CH
    MECH_STATECODE_CH, // Count_cycle - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // Count_cycle - Deactivate -> CH
    MECH_STATECODE_CH, // Count_cycle - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Count_cycle - Good_injection -> CH
    MECH_STATECODE_CH, // Count_cycle - Locked_out -> CH
    MECH_STATECODE_CH, // Count_cycle - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Count_cycle - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Count_cycle - Lubricate -> CH
    MECH_STATECODE_CH, // Count_cycle - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // Count_cycle - New_session -> CH
    4, // Count_cycle - Next_cycle -> WAIT_INTERVAL
    MECH_STATECODE_CH, // Count_cycle - Resume -> CH
    2, // Count_cycle - Stop -> NOT_ACTIVE
    MECH_STATECODE_CH, // Count_cycle - Suspend -> CH
    MECH_STATECODE_CH, // Count_cycle - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Activate -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Activated -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Change_schedule -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Count_as_normal -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Created -> CH
    14, // Interrupted_cycle_count - Cycle_interrupted -> Count_cycle
    MECH_STATECODE_CH, // Interrupted_cycle_count - Deactivate -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Good_injection -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Locked_out -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Lubricate -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - New_session -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Next_cycle -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Resume -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Stop -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Suspend -> CH
    MECH_STATECODE_CH, // Interrupted_cycle_count - Wait_interval_canceled -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Activate -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Activated -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Change_schedule -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Count_as_normal -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Created -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Cycle_interrupted -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Deactivate -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Get_ready_to_lubricate -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Good_injection -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Locked_out -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Low_pressure_injection -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Lube_interval_ended -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Lubricate -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Monitor_interval_canceled -> CH
    MECH_STATECODE_CH, // Spawn_new_session - New_session -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Next_cycle -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Resume -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Stop -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Suspend -> CH
    MECH_STATECODE_CH, // Spawn_new_session - Wait_interval_canceled -> CH
} ;
static struct objectdispatchblock const Autocycle_Session_odb = {
    .stateCount = 17,
    .eventCount = 20,
    .transitionTable = Autocycle_Session_transtbl,
    .actionTable = Autocycle_Session_acttbl,
    .finalStates = Autocycle_Session_fs
} ;
/*
 * AODB for Class, "Reservoir"
 */
static PtrActionFunction const Reservoir_acttbl[] = {
    Reservoir_NORMAL,
    Reservoir_LOW,
    Reservoir_VERY_LOW,
    Reservoir_EMPTY,
} ;
static StateCode const Reservoir_transtbl[] = {
    MECH_STATECODE_IG, // NORMAL - Low_injection_pressure -> IG
    1, // NORMAL - Low_lube_level -> LOW
    MECH_STATECODE_IG, // NORMAL - Normal_lube_level -> IG
    MECH_STATECODE_CH, // NORMAL - Too_many_low_lube_cycles -> CH
    MECH_STATECODE_IG, // LOW - Low_injection_pressure -> IG
    MECH_STATECODE_IG, // LOW - Low_lube_level -> IG
    0, // LOW - Normal_lube_level -> NORMAL
    2, // LOW - Too_many_low_lube_cycles -> VERY_LOW
    3, // VERY_LOW - Low_injection_pressure -> EMPTY
    MECH_STATECODE_IG, // VERY_LOW - Low_lube_level -> IG
    0, // VERY_LOW - Normal_lube_level -> NORMAL
    MECH_STATECODE_CH, // VERY_LOW - Too_many_low_lube_cycles -> CH
    MECH_STATECODE_IG, // EMPTY - Low_injection_pressure -> IG
    MECH_STATECODE_IG, // EMPTY - Low_lube_level -> IG
    0, // EMPTY - Normal_lube_level -> NORMAL
    MECH_STATECODE_CH, // EMPTY - Too_many_low_lube_cycles -> CH
} ;
static struct objectdispatchblock const Reservoir_odb = {
    .stateCount = 4,
    .eventCount = 4,
    .transitionTable = Reservoir_transtbl,
    .actionTable = Reservoir_acttbl,
    .finalStates = NULL
} ;


/*
 * Class Structure for, "Injector"
 */
static struct mechclass const Injector_class = {
    .iab = NULL,
    .odb = &Injector_odb,
    .pdb = NULL
} ;
/*
 * Class Structure for, "Autocycle_Session"
 */
static struct mechclass const Autocycle_Session_class = {
    .iab = &Autocycle_Session_iab,
    .odb = &Autocycle_Session_odb,
    .pdb = NULL
} ;
/*
 * Class Structure for, "Reservoir"
 */
static struct mechclass const Reservoir_class = {
    .iab = NULL,
    .odb = &Reservoir_odb,
    .pdb = NULL
} ;


/*
 * Data Portal data structures
 */
#include "pycca_portal.h"
static struct pycca_attr_portal const Lubrication_Schedule_attr_portal[6] = {
    {.offset = offsetof(struct Lubrication_Schedule, Name), .size = sizeof(Lubrication_Schedule_storage->Name)},
    {.offset = offsetof(struct Lubrication_Schedule, Wait_interval), .size = sizeof(Lubrication_Schedule_storage->Wait_interval)},
    {.offset = offsetof(struct Lubrication_Schedule, Monitor_interval), .size = sizeof(Lubrication_Schedule_storage->Monitor_interval)},
    {.offset = offsetof(struct Lubrication_Schedule, Max_low_lube_cycles), .size = sizeof(Lubrication_Schedule_storage->Max_low_lube_cycles)},
    {.offset = offsetof(struct Lubrication_Schedule, Default_continuous_operation), .size = sizeof(Lubrication_Schedule_storage->Default_continuous_operation)},
    {.offset = offsetof(struct Lubrication_Schedule, Default_max_cycles), .size = sizeof(Lubrication_Schedule_storage->Default_max_cycles)},
} ;
static struct pycca_attr_portal const Injector_Design_attr_portal[6] = {
    {.offset = offsetof(struct Injector_Design, Model), .size = sizeof(Injector_Design_storage->Model)},
    {.offset = offsetof(struct Injector_Design, Min_delivery_pressure), .size = sizeof(Injector_Design_storage->Min_delivery_pressure)},
    {.offset = offsetof(struct Injector_Design, Max_system_pressure), .size = sizeof(Injector_Design_storage->Max_system_pressure)},
    {.offset = offsetof(struct Injector_Design, Max_dissipation_pressure), .size = sizeof(Injector_Design_storage->Max_dissipation_pressure)},
    {.offset = offsetof(struct Injector_Design, Delivery_window), .size = sizeof(Injector_Design_storage->Delivery_window)},
    {.offset = offsetof(struct Injector_Design, Good_injection_duration), .size = sizeof(Injector_Design_storage->Good_injection_duration)},
} ;
static struct pycca_attr_portal const Injector_attr_portal[3] = {
    {.offset = offsetof(struct Injector, Pressure), .size = sizeof(Injector_storage->Pressure)},
    {.offset = offsetof(struct Injector, Dissipation_error), .size = sizeof(Injector_storage->Dissipation_error)},
    {.offset = offsetof(struct Injector, Injecting), .size = sizeof(Injector_storage->Injecting)},
} ;
static struct pycca_attr_portal const Autocycle_Session_attr_portal[9] = {
    {.offset = offsetof(struct Autocycle_Session, Cycles_requested), .size = sizeof(Autocycle_Session_storage->Cycles_requested)},
    {.offset = offsetof(struct Autocycle_Session, Continuous_operation), .size = sizeof(Autocycle_Session_storage->Continuous_operation)},
    {.offset = offsetof(struct Autocycle_Session, Failed_cycles), .size = sizeof(Autocycle_Session_storage->Failed_cycles)},
    {.offset = offsetof(struct Autocycle_Session, Cycles_since_activation), .size = sizeof(Autocycle_Session_storage->Cycles_since_activation)},
    {.offset = offsetof(struct Autocycle_Session, Lubricating), .size = sizeof(Autocycle_Session_storage->Lubricating)},
    {.offset = offsetof(struct Autocycle_Session, Active), .size = sizeof(Autocycle_Session_storage->Active)},
    {.offset = offsetof(struct Autocycle_Session, Deactivate), .size = sizeof(Autocycle_Session_storage->Deactivate)},
    {.offset = offsetof(struct Autocycle_Session, Suspend_requested), .size = sizeof(Autocycle_Session_storage->Suspend_requested)},
    {.offset = offsetof(struct Autocycle_Session, Wait_time_remaining), .size = sizeof(Autocycle_Session_storage->Wait_time_remaining)},
} ;
static struct pycca_attr_portal const Machinery_attr_portal[1] = {
    {.offset = offsetof(struct Machinery, Locked_out), .size = sizeof(Machinery_storage->Locked_out)},
} ;
static struct pycca_attr_portal const Reservoir_attr_portal[1] = {
    {.offset = offsetof(struct Reservoir, Level), .size = sizeof(Reservoir_storage->Level)},
} ;
static struct pycca_class_portal const lube_class_portal[] = {
    {.storage = Lubrication_Schedule_storage, .attrs = Lubrication_Schedule_attr_portal, .mechClass = NULL, .numAttrs = 6, .numInsts = 4, .instSize = sizeof(struct Lubrication_Schedule), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Lubrication_Schedule_INITIAL_STATE},
    {.storage = Injector_Design_storage, .attrs = Injector_Design_attr_portal, .mechClass = NULL, .numAttrs = 6, .numInsts = 2, .instSize = sizeof(struct Injector_Design), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Injector_Design_INITIAL_STATE},
    {.storage = Injector_storage, .attrs = Injector_attr_portal, .mechClass = &Injector_class, .numAttrs = 3, .numInsts = 3, .instSize = sizeof(struct Injector), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Injector_INITIAL_STATE},
    {.storage = Autocycle_Session_storage, .attrs = Autocycle_Session_attr_portal, .mechClass = &Autocycle_Session_class, .numAttrs = 9, .numInsts = 3, .instSize = sizeof(struct Autocycle_Session), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Autocycle_Session_INITIAL_STATE},
    {.storage = Machinery_storage, .attrs = Machinery_attr_portal, .mechClass = NULL, .numAttrs = 1, .numInsts = 3, .instSize = sizeof(struct Machinery), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Machinery_INITIAL_STATE},
    {.storage = Reservoir_storage, .attrs = Reservoir_attr_portal, .mechClass = &Reservoir_class, .numAttrs = 1, .numInsts = 2, .instSize = sizeof(struct Reservoir), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Reservoir_INITIAL_STATE},
} ;
struct pycca_domain_portal const lube_portal = {
    .classes = lube_class_portal,
    .numClasses = 6
} ;

/*
 * Multi-ref pointer arrays
 */
static struct Injector *const Machinery_R5_13_refs[] = {
    &Injector_storage[0],
} ;
static struct Injector *const Machinery_R5_14_refs[] = {
    &Injector_storage[1],
} ;
static struct Injector *const Machinery_R5_15_refs[] = {
    &Injector_storage[2],
} ;
static struct Injector *const Reservoir_R3_16_refs[] = {
    &Injector_storage[0],
    &Injector_storage[2],
} ;
static struct Injector *const Reservoir_R3_17_refs[] = {
    &Injector_storage[1],
} ;

/*
 * Initial Instance Storage for, "Lubrication_Schedule"
 */
static struct Lubrication_Schedule Lubrication_Schedule_storage[4] = {
    {"Gearbox", 210, 45, 8, true, 5000},
    {"Generator", 120, 25, 10, true, 10000},
    {"Shaft", 90, 30, 10, true, 10000},
    {"Test2", 20, 15, 1, false, 200}
} ;
/*
 * Initial Instance Storage for, "Injector_Design"
 */
static struct Injector_Design Injector_Design_storage[2] = {
    {"IHN4", 19, 35, 32, 90, 9},
    {"IX77B", 15, 26, 26, 120, 11}
} ;
/*
 * Initial Instance Storage for, "Injector"
 */
static struct Injector Injector_storage[3] = {
    {.common_ = {1, 8, &Injector_class}, 20, false, false, .R4 = &Injector_Design_storage[1], .R5 = &Machinery_storage[0], .R1 = &Lubrication_Schedule_storage[0], .R2 = &Autocycle_Session_storage[0], .R3 = &Reservoir_storage[0]},
    {.common_ = {2, 8, &Injector_class}, 0, false, false, .R4 = &Injector_Design_storage[0], .R5 = &Machinery_storage[1], .R1 = &Lubrication_Schedule_storage[2], .R2 = &Autocycle_Session_storage[1], .R3 = &Reservoir_storage[1]},
    {.common_ = {3, 8, &Injector_class}, 0, true, true, .R4 = &Injector_Design_storage[1], .R5 = &Machinery_storage[2], .R1 = &Lubrication_Schedule_storage[1], .R2 = &Autocycle_Session_storage[2], .R3 = &Reservoir_storage[0]}
} ;
/*
 * Initial Instance Storage for, "Autocycle_Session"
 */
static struct Autocycle_Session Autocycle_Session_storage[3] = {
    {.common_ = {1, 1, &Autocycle_Session_class}, 0, true, 0, 0, false, true, false, false, 90, .R2_INJ = &Injector_storage[0], .R2_LBS = &Lubrication_Schedule_storage[0]},
    {.common_ = {2, 1, &Autocycle_Session_class}, 0, true, 1, 0, true, true, true, false, 0, .R2_INJ = &Injector_storage[1], .R2_LBS = &Lubrication_Schedule_storage[2]},
    {.common_ = {3, 1, &Autocycle_Session_class}, 0, true, 0, 0, false, true, true, false, 0, .R2_INJ = &Injector_storage[2], .R2_LBS = &Lubrication_Schedule_storage[1]}
} ;
/*
 * Initial Instance Storage for, "Machinery"
 */
static struct Machinery Machinery_storage[3] = {
    {false, .R5 = Machinery_R5_13_refs, .R5__count = COUNTOF(Machinery_R5_13_refs)},
    {false, .R5 = Machinery_R5_14_refs, .R5__count = COUNTOF(Machinery_R5_14_refs)},
    {false, .R5 = Machinery_R5_15_refs, .R5__count = COUNTOF(Machinery_R5_15_refs)}
} ;
/*
 * Initial Instance Storage for, "Reservoir"
 */
static struct Reservoir Reservoir_storage[2] = {
    {.common_ = {1, 0, &Reservoir_class}, FS_normal, .R3 = Reservoir_R3_16_refs, .R3__count = COUNTOF(Reservoir_R3_16_refs)},
    {.common_ = {2, 0, &Reservoir_class}, FS_low, .R3 = Reservoir_R3_17_refs, .R3__count = COUNTOF(Reservoir_R3_17_refs)}
} ;

/*
 * Operation Function Definitions
 */
#define THISCLASS__ Autocycle_Session
static void Autocycle_Session_Deactivate(struct Autocycle_Session *self)
{
    INSTR_FUNC("lube.Autocycle_Session.Deactivate") ;

    self->Deactivate = true ;
    PYCCA_generateToSelf(Deactivate) ;
}
static void Autocycle_Session_Suspend(struct Autocycle_Session *self)
{
    INSTR_FUNC("lube.Autocycle_Session.Suspend") ;

    self->Suspend_requested = true ;
    PYCCA_generateToSelf(Suspend) ;
}
#undef THISCLASS__
#define THISCLASS__ Injector
static void Injector_Max_system_pressure(struct Injector *self)
{
    INSTR_FUNC("lube.Injector.Max_system_pressure") ;

    ExternalOp(ALARM_Set_pressure_error)(PYCCA_idOfSelf) ;
    ClassRefVar(Autocycle_Session, acs) = self->R2 ;
    InstOp(Autocycle_Session, Deactivate)(acs) ;
}
#undef THISCLASS__
#define THISCLASS__ Lubrication_Schedule
static struct Lubrication_Schedule * Lubrication_Schedule_findByName(char const *name)
{
    INSTR_FUNC("lube.Lubrication_Schedule.findByName") ;

    ThisClassRefVar(ls) ;
    PYCCA_selectOneStaticInstOfThisClassWhere(ls, strcmp(ls->Name, name) == 0)
    return ls == ThisClassEndStorage ? NULL : ls ;
}
#undef THISCLASS__
#define THISCLASS__ Machinery
static void Machinery_Lock(struct Machinery *self)
{
    INSTR_FUNC("lube.Machinery.Lock") ;

    self->Locked_out = true ;
    ClassRefConstSetVar(Injector, myinjs) ;
    PYCCA_forAllRelated(myinjs, self, R5) {
        ClassRefVar(Injector, inj) = *myinjs ;
        ClassRefVar(Autocycle_Session, acs) = inj->R2 ;
        InstOp(Autocycle_Session, Deactivate)(acs) ;
    }
}
static void Machinery_Unlock(struct Machinery *self)
{
    INSTR_FUNC("lube.Machinery.Unlock") ;

    self->Locked_out = false ;
}
#undef THISCLASS__

/*
 * Constructor Function Definitions
 */

/*
 * Destructor Function Definitions
 */

/*
 * State Action Function Definitions
 */
#define THISCLASS__ Autocycle_Session
static void Autocycle_Session_Creating(void *const s_, void *const p_)
{
#define THISSTATE__ Creating
    INSTR_FUNC("lube.Autocycle_Session.Creating") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;
    struct Autocycle_Session_Creating_rcvd_evt {
        char const *schedule ;
        unsigned injector ;
    } const *const rcvd_evt = (struct Autocycle_Session_Creating_rcvd_evt const *)p_ ;

    ClassRefVar(Lubrication_Schedule, ls) =
        ClassOp(Lubrication_Schedule, findByName)(rcvd_evt->schedule) ;
    assert(ls != NULL) ;
    ClassRefVar(Injector, inj) = PYCCA_refOfId(Injector, rcvd_evt->injector) ;
    self->R2_LBS = ls ;
    self->R2_INJ = inj ;
    inj->R2 = self ;

    PYCCA_generateToSelf(Created) ;
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Autocycle_Session
static void Autocycle_Session_Spawn_new_session(void *const s_, void *const p_)
{
#define THISSTATE__ Spawn_new_session
    INSTR_FUNC("lube.Autocycle_Session.Spawn_new_session") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;
    struct Autocycle_Session_Spawn_new_session_rcvd_evt {
        char const *schedule ;
    } const *const rcvd_evt = (struct Autocycle_Session_Spawn_new_session_rcvd_evt const *)p_ ;

    MechEcb new_session = PYCCA_newCreationEventForThisClass(New_session, self) ;
    PYCCA_eventParam(new_session, Autocycle_Session, New_session, schedule) =
            rcvd_evt->schedule ;
    PYCCA_eventParam(new_session, Autocycle_Session, New_session, injector) =
            PYCCA_idOfRef(Injector, self->R2_INJ) ;
    PYCCA_postEvent(new_session) ;

    self->R2_INJ->R2 = NULL ; // <1>
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Autocycle_Session
static void Autocycle_Session_Initialize(void *const s_, void *const p_)
{
#define THISSTATE__ Initialize
    INSTR_FUNC("lube.Autocycle_Session.Initialize") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;
    struct Autocycle_Session_Initialize_rcvd_evt {
        bool continuous ;
        Count count ;
    } const *const rcvd_evt = (struct Autocycle_Session_Initialize_rcvd_evt const *)p_ ;

    if (self->R2_INJ->R5->Locked_out) {
        ExternalOp(App_Error)("Machinery lockout active") ;
        PYCCA_generateToSelf(Locked_out) ;
    } else {
        if (rcvd_evt->count != 0) {
            self->Cycles_requested = rcvd_evt->count ;
        }
        self->Continuous_operation = rcvd_evt->continuous ;
        self->Cycles_since_activation = 0 ;
        self->Failed_cycles = 0 ;

        self->Wait_time_remaining = self->R2_LBS->Wait_interval ;
        self->Active = true ;
        PYCCA_generateToSelf(Activated) ;
    }
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Autocycle_Session
static void Autocycle_Session_NOT_ACTIVE(void *const s_, void *const p_)
{
#define THISSTATE__ NOT_ACTIVE
    INSTR_FUNC("lube.Autocycle_Session.NOT_ACTIVE") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    ExternalOp(UI_Deactivated)(PYCCA_idOfSelf) ;

    ClassRefVar(Lubrication_Schedule, ls) = self->R2_LBS ;
    self->Continuous_operation = ls->Default_continuous_operation ;
    self->Cycles_requested = ls->Default_max_cycles ;
    self->Lubricating =
    self->Active =
    self->Deactivate =
    self->Suspend_requested = false ;
#undef THISSTATE__
}
static void Autocycle_Session_WAIT_INTERVAL(void *const s_, void *const p_)
{
#define THISSTATE__ WAIT_INTERVAL
    INSTR_FUNC("lube.Autocycle_Session.WAIT_INTERVAL") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    if (self->Deactivate) {
        PYCCA_generateToSelf(Deactivate) ;
    } else {
        PYCCA_generateDelayedToSelf(Get_ready_to_lubricate,
            SecsToDelayTime(self->Wait_time_remaining)) ;
        if (self->Suspend_requested) {
            PYCCA_generateToSelf(Suspend) ;
        }
    }
#undef THISSTATE__
}
static void Autocycle_Session_Cancel_wait_interval(void *const s_, void *const p_)
{
#define THISSTATE__ Cancel_wait_interval
    INSTR_FUNC("lube.Autocycle_Session.Cancel_wait_interval") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_cancelDelayedToSelf(Get_ready_to_lubricate) ;
    PYCCA_generateToSelf(Wait_interval_canceled) ;
#undef THISSTATE__
}
static void Autocycle_Session_WAIT_SUSPENDED(void *const s_, void *const p_)
{
#define THISSTATE__ WAIT_SUSPENDED
    INSTR_FUNC("lube.Autocycle_Session.WAIT_SUSPENDED") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    self->Wait_time_remaining =
            DelayTimeToSecs(PYCCA_remainDelayedToSelf(Get_ready_to_lubricate)) ;
    PYCCA_cancelDelayedToSelf(Get_ready_to_lubricate) ;
    self->Suspend_requested = false ;
#undef THISSTATE__
}
static void Autocycle_Session_MONITOR_INTERVAL(void *const s_, void *const p_)
{
#define THISSTATE__ MONITOR_INTERVAL
    INSTR_FUNC("lube.Autocycle_Session.MONITOR_INTERVAL") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_generateDelayedToSelf(Lubricate,
        SecsToDelayTime(self->R2_LBS->Monitor_interval)) ;
    PYCCA_generate(Wakeup, Injector, self->R2_INJ, self) ;
#undef THISSTATE__
}
static void Autocycle_Session_Cancel_monitor_interval(void *const s_, void *const p_)
{
#define THISSTATE__ Cancel_monitor_interval
    INSTR_FUNC("lube.Autocycle_Session.Cancel_monitor_interval") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_cancelDelayedToSelf(Lubricate) ;
    PYCCA_generate(Stop, Injector, self->R2_INJ, self) ;
    PYCCA_generateToSelf(Monitor_interval_canceled) ;
#undef THISSTATE__
}
static void Autocycle_Session_MONITOR_SUSPENDED(void *const s_, void *const p_)
{
#define THISSTATE__ MONITOR_SUSPENDED
    INSTR_FUNC("lube.Autocycle_Session.MONITOR_SUSPENDED") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_cancelDelayedToSelf(Lubricate) ;
    PYCCA_generate(Stop, Injector, self->R2_INJ, self) ;
#undef THISSTATE__
}
static void Autocycle_Session_LUBE_INTERVAL(void *const s_, void *const p_)
{
#define THISSTATE__ LUBE_INTERVAL
    INSTR_FUNC("lube.Autocycle_Session.LUBE_INTERVAL") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_generate(Start, Injector, self->R2_INJ, self) ;
    PYCCA_generateDelayedToSelf(Lube_interval_ended,
            SecsToDelayTime(self->R2_INJ->R4->Delivery_window)) ;
    self->Lubricating = true ;
#undef THISSTATE__
}
static void Autocycle_Session_CANCELING_LUBRICATION(void *const s_, void *const p_)
{
#define THISSTATE__ CANCELING_LUBRICATION
    INSTR_FUNC("lube.Autocycle_Session.CANCELING_LUBRICATION") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_cancelDelayedToSelf(Lube_interval_ended) ;
    PYCCA_generate(Stop, Injector, self->R2_INJ, self) ;
    self->Lubricating = false ;
#undef THISSTATE__
}
static void Autocycle_Session_Normal_lubrication(void *const s_, void *const p_)
{
#define THISSTATE__ Normal_lubrication
    INSTR_FUNC("lube.Autocycle_Session.Normal_lubrication") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_cancelDelayedToSelf(Lube_interval_ended) ;
    PYCCA_generateToSelf(Count_as_normal) ;
    self->Lubricating = false ;
#undef THISSTATE__
}
static void Autocycle_Session_LOW_PRESSURE_LUBRICATION(void *const s_, void *const p_)
{
#define THISSTATE__ LOW_PRESSURE_LUBRICATION
    INSTR_FUNC("lube.Autocycle_Session.LOW_PRESSURE_LUBRICATION") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    PYCCA_generate(Stop, Injector, self->R2_INJ, self) ;
    self->Failed_cycles++ ;
    self->Lubricating = false ;
#undef THISSTATE__
}
static void Autocycle_Session_Count_cycle(void *const s_, void *const p_)
{
#define THISSTATE__ Count_cycle
    INSTR_FUNC("lube.Autocycle_Session.Count_cycle") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    self->Cycles_since_activation++ ;
    if (self->Failed_cycles >= self->R2_LBS->Max_low_lube_cycles) {
        PYCCA_generate(Too_many_low_lube_cycles, Reservoir, self->R2_INJ->R3, self) ;
    }
    if (!self->Deactivate &&
            (self->Continuous_operation ||
            self->Cycles_since_activation < self->Cycles_requested)) {
        PYCCA_generateToSelf(Next_cycle) ;
    } else {
        PYCCA_generateToSelf(Stop) ;
    }
#undef THISSTATE__
}
static void Autocycle_Session_Interrupted_cycle_count(void *const s_, void *const p_)
{
#define THISSTATE__ Interrupted_cycle_count
    INSTR_FUNC("lube.Autocycle_Session.Interrupted_cycle_count") ;
    struct Autocycle_Session *const self = (struct Autocycle_Session *)s_ ;

    self->Failed_cycles++ ;
    PYCCA_generateToSelf(Cycle_interrupted) ;
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Injector
static void Injector_Start_injection(void *const s_, void *const p_)
{
#define THISSTATE__ Start_injection
    INSTR_FUNC("lube.Injector.Start_injection") ;
    struct Injector *const self = (struct Injector *)s_ ;

    ExternalOp(SIO_Inject)(PYCCA_idOfSelf) ;
    PYCCA_generateToSelf(Wait_for_inject_pressure) ;
#undef THISSTATE__
}
static void Injector_BUILDING_PRESSURE(void *const s_, void *const p_)
{
#define THISSTATE__ BUILDING_PRESSURE
    INSTR_FUNC("lube.Injector.BUILDING_PRESSURE") ;
    struct Injector *const self = (struct Injector *)s_ ;

    if (self->Pressure > self->R4->Min_delivery_pressure) {
        PYCCA_generateToSelf(Above_inject_pressure) ;
    }
#undef THISSTATE__
}
static void Injector_INJECTING_AT_PRESSURE(void *const s_, void *const p_)
{
#define THISSTATE__ INJECTING_AT_PRESSURE
    INSTR_FUNC("lube.Injector.INJECTING_AT_PRESSURE") ;
    struct Injector *const self = (struct Injector *)s_ ;

    PYCCA_generateDelayedToSelf(Good_injection,
            SecsToDelayTime(self->R4->Good_injection_duration)) ;
    self->Injecting = true ;
#undef THISSTATE__
}
static void Injector_Not_enough_pressure(void *const s_, void *const p_)
{
#define THISSTATE__ Not_enough_pressure
    INSTR_FUNC("lube.Injector.Not_enough_pressure") ;
    struct Injector *const self = (struct Injector *)s_ ;

    PYCCA_cancelDelayedToSelf(Good_injection) ;
    PYCCA_generateToSelf(Wait_for_inject_pressure) ;

    PYCCA_generate(Low_injection_pressure, Reservoir, self->R3, self) ;
    self->Injecting = false ;
#undef THISSTATE__
}
static void Injector_Cancel_injection(void *const s_, void *const p_)
{
#define THISSTATE__ Cancel_injection
    INSTR_FUNC("lube.Injector.Cancel_injection") ;
    struct Injector *const self = (struct Injector *)s_ ;

    PYCCA_cancelDelayedToSelf(Good_injection) ;
    PYCCA_generateToSelf(Injection_canceled) ;
    self->Injecting = false ;
#undef THISSTATE__
}
static void Injector_Completed_good_injection(void *const s_, void *const p_)
{
#define THISSTATE__ Completed_good_injection
    INSTR_FUNC("lube.Injector.Completed_good_injection") ;
    struct Injector *const self = (struct Injector *)s_ ;

    ExternalOp(SIO_Stop_injecting)(PYCCA_idOfSelf) ;
    PYCCA_generate(Good_injection, Autocycle_Session, self->R2, self) ;
    PYCCA_generateToSelf(Stopped) ;
    self->Injecting = false ;
#undef THISSTATE__
}
static void Injector_Quit_low_pressure_injection(void *const s_, void *const p_)
{
#define THISSTATE__ Quit_low_pressure_injection
    INSTR_FUNC("lube.Injector.Quit_low_pressure_injection") ;
    struct Injector *const self = (struct Injector *)s_ ;

    ExternalOp(SIO_Stop_injecting)(PYCCA_idOfSelf) ;
    PYCCA_generate(Low_pressure_injection, Autocycle_Session, self->R2, self) ;
    PYCCA_generateToSelf(Stopped) ;
#undef THISSTATE__
}
static void Injector_Clear_error_and_check_interlock(void *const s_, void *const p_)
{
#define THISSTATE__ Clear_error_and_check_interlock
    INSTR_FUNC("lube.Injector.Clear_error_and_check_interlock") ;
    struct Injector *const self = (struct Injector *)s_ ;

    if (!self->Dissipation_error) {
        ExternalOp(ALARM_Clear_dissipation_error)(PYCCA_idOfSelf) ;
    }
    self->Dissipation_error = false ;

    if (self->R5->Locked_out) {
        PYCCA_generateToSelf(Locked_out) ;
    } else {
        PYCCA_generateToSelf(OK_to_start) ;
    }
#undef THISSTATE__
}
static void Injector_SLEEPING(void *const s_, void *const p_)
{
#define THISSTATE__ SLEEPING
    INSTR_FUNC("lube.Injector.SLEEPING") ;
    struct Injector *const self = (struct Injector *)s_ ;

    ExternalOp(SIO_Stop_monitoring)(PYCCA_idOfSelf) ;
#undef THISSTATE__
}
static void Injector_Initiate_monitoring(void *const s_, void *const p_)
{
#define THISSTATE__ Initiate_monitoring
    INSTR_FUNC("lube.Injector.Initiate_monitoring") ;
    struct Injector *const self = (struct Injector *)s_ ;

    ExternalOp(SIO_Start_monitoring)(PYCCA_idOfSelf) ;
    PYCCA_generateToSelf(Monitor) ;
#undef THISSTATE__
}
static void Injector_MONITORING(void *const s_, void *const p_)
{
#define THISSTATE__ MONITORING
    INSTR_FUNC("lube.Injector.MONITORING") ;

#undef THISSTATE__
}
static void Injector_Set_dissipation_error(void *const s_, void *const p_)
{
#define THISSTATE__ Set_dissipation_error
    INSTR_FUNC("lube.Injector.Set_dissipation_error") ;
    struct Injector *const self = (struct Injector *)s_ ;

    if (!self->Dissipation_error) {
        self->Dissipation_error = true ;
        ExternalOp(ALARM_Set_dissipation_error)(PYCCA_idOfSelf) ;
    }
    PYCCA_generateToSelf(Keep_monitoring) ;
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Reservoir
static void Reservoir_NORMAL(void *const s_, void *const p_)
{
#define THISSTATE__ NORMAL
    INSTR_FUNC("lube.Reservoir.NORMAL") ;
    struct Reservoir *const self = (struct Reservoir *)s_ ;

    self->Level = FS_normal ;
    ClassRefConstSetVar(Injector, myinjs) ;
    PYCCA_forAllRelated(myinjs, self, R3) {
        ClassRefVar(Injector, inj) = *myinjs ;
        ClassRefVar(Autocycle_Session, acs) = inj->R2 ;
        acs->Failed_cycles = 0 ;
    }
    ExternalOp(ALARM_Clear_lube_level_very_low)(PYCCA_idOfSelf) ;
    ExternalOp(ALARM_Clear_lube_level_low)(PYCCA_idOfSelf) ;
    ExternalOp(ALARM_Clear_lube_level_empty)(PYCCA_idOfSelf) ;
#undef THISSTATE__
}
static void Reservoir_LOW(void *const s_, void *const p_)
{
#define THISSTATE__ LOW
    INSTR_FUNC("lube.Reservoir.LOW") ;
    struct Reservoir *const self = (struct Reservoir *)s_ ;

    self->Level = FS_low ;
    ExternalOp(ALARM_Set_lube_level_low)(PYCCA_idOfSelf) ;
#undef THISSTATE__
}
static void Reservoir_VERY_LOW(void *const s_, void *const p_)
{
#define THISSTATE__ VERY_LOW
    INSTR_FUNC("lube.Reservoir.VERY_LOW") ;
    struct Reservoir *const self = (struct Reservoir *)s_ ;

    self->Level = FS_verylow ;
    ExternalOp(ALARM_Set_lube_level_very_low)(PYCCA_idOfSelf) ;
#undef THISSTATE__
}
static void Reservoir_EMPTY(void *const s_, void *const p_)
{
#define THISSTATE__ EMPTY
    INSTR_FUNC("lube.Reservoir.EMPTY") ;
    struct Reservoir *const self = (struct Reservoir *)s_ ;

    self->Level = FS_empty ;
    ExternalOp(ALARM_Set_lube_level_empty)(PYCCA_idOfSelf) ;
    ClassRefConstSetVar(Injector, myinjs) ;
    PYCCA_forAllRelated(myinjs, self, R3) {
        ClassRefVar(Injector, inj) = *myinjs ;
        ClassRefVar(Autocycle_Session, acs) = inj->R2 ;
        InstOp(Autocycle_Session, Deactivate)(acs) ;
    }
#undef THISSTATE__
}
#undef THISCLASS__

/*
 * Domain Operation Definitions
 */
void lube_init(void)
{
    INSTR_FUNC("lube.init") ;

    ClassRefVar(Autocycle_Session, acs) ;
    PYCCA_forAllInst(acs, Autocycle_Session) {
        if (IsInstInUse(acs)) {
            PYCCA_generate(Created, Autocycle_Session, acs, NULL) ;
        }
    }
}
void lube_Suspend_Autocycle_Session(InstId_t sessionId)
{
    INSTR_FUNC("lube.Suspend_Autocycle_Session") ;

    PYCCA_checkId(Autocycle_Session, sessionId) ;
    ClassRefVar(Autocycle_Session, session) =
            PYCCA_refOfId(Autocycle_Session, sessionId) ;
    if (IsInstInUse(session)) {
        InstOp(Autocycle_Session, Suspend)(session) ;
    }
}
void lube_Injector_max_pressure(InstId_t injId)
{
    INSTR_FUNC("lube.Injector_max_pressure") ;

    PYCCA_checkId(Injector, injId) ;
    ClassRefVar(Injector, inj) = PYCCA_refOfId(Injector, injId) ;
    if (IsInstInUse(inj)) {
        InstOp(Injector, Max_system_pressure)(inj) ;
    }
}
void lube_Lock_Machinery(InstId_t machineId)
{
    INSTR_FUNC("lube.Lock_Machinery") ;

    PYCCA_checkId(Machinery, machineId) ;
    ClassRefVar(Machinery, machine) = PYCCA_refOfId(Machinery, machineId) ;
    /*
     * Since the Machinery class has a static population, there is no
     * need to check if the instance is in use. All Machinery instances
     * defined in the initial instance population are always in use.
     */
    InstOp(Machinery, Lock)(machine) ;
}
void lube_Unlock_Machinery(InstId_t machineId)
{
    INSTR_FUNC("lube.Unlock_Machinery") ;

    PYCCA_checkId(Machinery, machineId) ;
    ClassRefVar(Machinery, machine) = PYCCA_refOfId(Machinery, machineId) ;
    InstOp(Machinery, Unlock)(machine) ;
}

/*
 * Definition of Function to Construct Initial Instances
 */




