/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: /home/andrewm/working/modelstocode/mtc_source/tools/linux/tack/lib/application/main.tcl, Revision: 3.8.1
 * Generated on: Fri Jun 23 15:17:13 PDT 2017
 */

#ifndef ALSHARNESS_H_
#define ALSHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void lube_harness_init(void) ;


extern void sio_harness_init(void) ;


#endif /* ALSHARNESS_H_ */
