/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: /Users/andrewm/develop/modelstocode/mtc_source/tools/macosx/tack/lib/application/main.tcl, Revision: 3.8.1
 * Generated on: Sun Apr 16 11:22:36 PDT 2017
 */

#ifndef LUBEHARNESS_H_
#define LUBEHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void lube_harness_init(void) ;


#endif /* LUBEHARNESS_H_ */
