/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: C:/Users/andrewm/Working/modelrealization/modelstocode/mtc_source/tools/windows/tack.exe/lib/application/main.tcl, Revision: 3.6
 * Generated on: Fri Jun 23 15:13:24 PDT 2017
 */

#ifndef ALSHARNESS_H_
#define ALSHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void lube_harness_init(void) ;


extern void sio_harness_init(void) ;


#endif /* ALSHARNESS_H_ */
