/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: /home/andrewm/working/modelstocode/mtc_source/tools/linux/tack/lib/application/main.tcl, Revision: 3.8.1
 * Generated on: Sat Apr 15 14:52:38 PDT 2017
 */

#ifndef ATCHARNESS_H_
#define ATCHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void atctrl_harness_init(void) ;


#endif /* ATCHARNESS_H_ */
