/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: C:/Users/andrewm/Working/modelrealization/modelstocode/mtc_source/tools/windows/tack.exe/lib/application/main.tcl, Revision: 3.6
 * Generated on: Sun Apr 16 10:47:23 PDT 2017
 */

#ifndef ATCHARNESS_H_
#define ATCHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void atctrl_harness_init(void) ;


#endif /* ATCHARNESS_H_ */
