/*
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
 * Created by: C:/Users/andrewm/Working/modelrealization/modelstocode/mtc_source/tools/windows/pycca.exe/lib/application/pycca.tcl 
 * Created on: Sun Apr 16 10:47:23 PDT 2017
 * This is pycca version 4.3
 * ---------------------------------------------------------------
 */

#include <stdio.h>

#include <stddef.h>
#include <stdbool.h>
#include "mechs.h"

/*
 * The following macros may be used in the code to insulate the naming
 * conventions of "pycca" from the code.
 */
#define ClassRefType(c)             struct c *
#define ThisClassRefType            ClassRefType(THISCLASS__)
#define ClassRefVar(c, v)           struct c *v
#define ThisClassRefVar(v)          ClassRefVar(THISCLASS__, v)
#define ClassConstRefVar(c, v)      struct c const *v
#define ThisClassConstRefVar(v)     ClassConstRefVar(THISCLASS__, v)
#define ClassRefSetVar(c, v)        struct c **v
#define ThisClassRefSetVar(v)       ClassRefSetVar(THISCLASS__, v)
#define ClassRefConstSetVar(c, v)   struct c * const *v
#define ThisClassRefConstSetVar(v)  ClassRefConstSetVar(THISCLASS__, v)
#define ClassConstRefSetVar(c, v)   struct c const * const *v
#define ThisClassConstRefSetVar(v)  ClassConstRefSetVar(THISCLASS__, v)
#define SubCodeMember(r)            r ## __code
#define SubCodeValue(c, r, s)       c ## _ ## r ## _ ## s ## _CODE
#define SubTypesMember(r, s)        r . r ## _ ## s
#define RefCountMember(r)           r ## __count
#define SMName__(c, e, t)           c ## _ ## e ## t
#define EventNumber(c, e)           SMName__(c, e, _EVENT)
#define ThisClassEventNumber(e)     EventNumber(THISCLASS__, e)
#define PolyEventNumber(c, e)       SMName__(c, e, _POLYEVENT)
#define StateNumber(c, s)           SMName__(c, s, _STATE)
#define ThisClassStateNumber(s)     StateNumber(THISCLASS__, s)
#define SelfStateNumber             StateNumber(THISCLASS__, THISSTATE__)
#define ISName__(c)                 c ## _INITIAL_STATE
#define InitialStateNumber(c)       ISName__(c)
#define ThisClassInitialStateNumber InitialStateNumber(THISCLASS__)
#define EPName__(c, e)              struct c ## _ ## e ## _rcvd_evt
#define EventParamType(c, e)        EPName__(c, e)
#define EventParamDecl(c, e)        EPName__(c, e)
#define ThisClassEventParamDecl(e)  EventParamDecl(THISCLASS__, e)
#define CName__(c)                  (&c ## _class)
#define ClassData(c)                CName__(c)
#define ThisClassData               ClassData(THISCLASS__)
#define ExtStName__(d, c)           d ## _ ## c ## _storage
#define StName__(c)                 c ## _storage
#define BeginStorage(c)            StName__(c)
#define ThisClassBeginStorage       BeginStorage(THISCLASS__)
#define EndStorage(c)               (BeginStorage(c) + (sizeof(BeginStorage(c)) / sizeof(BeginStorage(c)[0])))
#define ThisClassEndStorage         EndStorage(THISCLASS__)
#define ExtIName__(d, c, n)         (ExtStName__(d, c, n) + c ## _ ## n ## _INSTANCE)
#define IName__(c, n)               (StName__(c) + c ## _ ## n ## _INSTANCE)
#define Instance(c, n)     IName__(c, n)
#define ThisClassInstance(n)     Instance(THISCLASS__, n)
#define IsInstInUse(i)      ((i)->common_.alloc != 0)
#define DomainName          atctrl
#define OpName(p, s)        p ## _ ## s
#define DomainOp(d, o)      OpName(d, o)
#define ExternalOp(o)       OpName(eop_ ## atctrl, o)
#define ClassOp(c, o)       OpName(c, o)
#define ThisClassOp(o)      ClassOp(THISCLASS__, o)
#define InstOp(c, o)        OpName(c, o)
#define ThisClassInstOp(o)  InstOp(THISCLASS__, o)

/*
 * Some convenience macros.
 */
#define PYCCA_generate(e, c, i, s) mechEventGenerate(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_generateSelf(e, c) PYCCA_generate(e, c, (MechInstance)self, (MechInstance)self)

#define PYCCA_generateToSelf(e) PYCCA_generateSelf(e, THISCLASS__)

#define PYCCA_generatePolymorphic(e, c, i, s) mechEventGeneratePolymorphic(PolyEventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_generateCreation(e, c, s) mechEventGenerateCreation(EventNumber(c, e), ClassData(c), (MechInstance)s)

#define PYCCA_generateDelayed(e, c, i, s, d) mechEventGenerateDelayed(EventNumber(c, e), (MechInstance)i, (MechInstance)s, d)

#define PYCCA_generateDelayedSelf(e, c, d) PYCCA_generateDelayed(e, c, (MechInstance)self, (MechInstance)self, d)

#define PYCCA_generateDelayedToSelf(e, d) PYCCA_generateDelayedSelf(e, THISCLASS__, d)

#define PYCCA_cancelDelayed(e, c, i, s) mechEventDelayCancel(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_cancelDelayedSelf(e, c) mechEventDelayCancel(EventNumber(c, e), (MechInstance)self, (MechInstance)self)

#define PYCCA_cancelDelayedToSelf(e) PYCCA_cancelDelayedSelf(e, THISCLASS__)

#define PYCCA_remainDelayed(e, c, i, s) mechEventDelayRemaining(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_remainDelayedSelf(e, c) PYCCA_remainDelayed(e, c, (MechInstance)self, (MechInstance)self)

#define PYCCA_remainDelayedToSelf(e) PYCCA_remainDelayedSelf(e, THISCLASS__)

#define PYCCA_newEvent(e, c, i, s) mechEventNew(EventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_newSelfEvent(e, c) mechEventNew(EventNumber(c, e), (MechInstance)self, (MechInstance)self)

#define PYCCA_newEventToSelf(e) PYCCA_newSelfEvent(e, THISCLASS__)

#define PYCCA_newPolymorphicEvent(e, c, i, s) mechPolyEventNew(PolyEventNumber(c, e), (MechInstance)i, (MechInstance)s)

#define PYCCA_newCreationEvent(e, c, s) mechCreationEventNew(EventNumber(c, e), ClassData(c), (MechInstance)s)

#define PYCCA_newCreationEventForThisClass(e, s) PYCCA_newCreationEvent(e, THISCLASS__, s)

#define PYCCA_eventParam(ecb, c, e, p) ((EventParamDecl(c, e) *)(&(ecb)->eventParameters))->p

#define PYCCA_eventParamOfThisClass(ecb, e, p) PYCCA_eventParam(ecb, THISCLASS__, e, p)

#define PYCCA_postEvent(ecb) mechEventPost(ecb)

#define PYCCA_postSelfEvent(ecb) mechEventPostSelf(ecb)

#define PYCCA_postDelayedEvent(ecb, d) mechEventPostDelay(ecb, d)

#define PYCCA_createInstance(c, s) ((struct c *)mechInstCreate(ClassData(c), s))

#define PYCCA_newInstance(c)    PYCCA_createInstance(c, InitialStateNumber(c))

#define PYCCA_newInstanceOfThisClass     PYCCA_newInstance(THISCLASS__)

#define PYCCA_destroyInstance(i) (mechInstDestroy((MechInstance)i))

#define PYCCA_setToInitialState(i, c)   ((i)->common_.currentState = InitialStateNumber(c))

#define PYCCA_setToInitialStateForThisClass(i)    PYCCA_setToInitialState(i, THISCLASS__)

#define PYCCA_isSubtypeRelated(i, supc, r, subc) ((i)->SubCodeMember(r) == SubCodeValue(supc, r, subc))

#define PYCCA_unionSupertype(i, supc, r) ((struct supc *)((char *)(i) - offsetof(struct supc, r)))

#define PYCCA_unionSubtype(i, r, sub) (&((i)->SubTypesMember(r, sub)))

#define PYCCA_referenceSubtype(i, r, subc) ((struct subc *)((i)->r))

#define PYCCA_migrateSubtype(i, supc, r, subc) (i->SubCodeMember(r) = SubCodeValue(supc, r, subc))

#define PYCCA_initUnionInstance(sup, r, subc) sup->SubTypesMember(r, subc).common_.alloc = 1 ; sup->SubTypesMember(r, subc).common_.currentState = InitialStateNumber(subc) ; sup->SubTypesMember(r, subc).common_.instClass = ClassData(subc) ;

#define PYCCA_initUnionInstanceToState(sup, r, subc, st) sup->SubTypesMember(r, subc).common_.alloc = 1 ; sup->SubTypesMember(r, subc).common_.currentState = StateNumber(subc, st) ; sup->SubTypesMember(r, subc).common_.instClass = ClassData(subc) ;

#define PYCCA_forAllInst(i, c) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i)

#define PYCCA_forAllInstOfThisClass(i)   PYCCA_forAllInst(i, THISCLASS__)

#define PYCCA_forAllRelated(v, i, r) for (v = i->r ; v < i->r + i->RefCountMember(r) ; ++v)

#define PYCCA_forAllRelatedTerm(v, i, r) for (v = i->r ; *v ; ++v)

#define PYCCA_selectOneInstWhere(i, c, expr) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i) { if (IsInstInUse(i) && (expr)) {break ;}}

#define PYCCA_selectOneInstOfThisClassWhere(i, expr) PYCCA_selectOneInstWhere(i, THISCLASS__, expr) 
#define PYCCA_selectOneStaticInstWhere(i, c, expr) for (i = BeginStorage(c) ; i != EndStorage(c) ; ++i) { if ((expr)) {break ;}}

#define PYCCA_selectOneStaticInstOfThisClassWhere(i, expr) PYCCA_selectOneStaticInstWhere(i, THISCLASS__, expr)

#define PYCCA_relateSubtypeByRef(s, supc, r, t, subc) s->r = (MechInstance)t ; PYCCA_migrateSubtype(s, supc, r, subc)

#define PYCCA_relateToMany(n, o, r, m) for (n = o->r ; n < o->r + COUNTOF(o->r) ; ++n) { if (*n == NULL) { *n = m ; break ; } } assert(n < o->r + COUNTOF(o->r))

#define PYCCA_unrelateFromMany(n, o, r, m) for (n = o->r ; n < o->r + COUNTOF(o->r) ; ++n) { if (*n == m) { *n = NULL ; break ; } } assert(n < o->r + COUNTOF(o->r))

#define PYCCA_linkToMany(o, r, m) rlinkInsert(&m->r##__links, &o->r)

#define PYCCA_unlinkFromMany(m, r) rlinkRemove(&m->r##__links)

#define PYCCA_linkToInstRef(l, c, r) ((struct c *)((char *)(l) - offsetof(struct c, r##__links)))

#define PYCCA_linkToInstRefOfThisClass(l, r) PYCCA_linkToInstRef(l, THISCLASS__, r)

#define PYCCA_forAllLinkedInst(i, r, l) for (l = rlinkBegin(&i->r) ; l != rlinkEnd(&i->r) ; l = l->next)

#define PYCCA_isLinkEmpty(i, r) rlinkEmpty(&i->r)

#define PYCCA_isLinkNotEmpty(i, r) rlinkNotEmpty(&i->r)

#define PYCCA_idOfSelf              (self - ThisClassBeginStorage)

#define PYCCA_idOfRef(c, r)         ((r) - BeginStorage(c))

#define PYCCA_idOfInst(c, n)        (Instance(c, n) - BeginStorage(c))

#define PYCCA_refOfId(c, i)         (BeginStorage(c) + (i))

#define PYCCA_refOfThisClassId(i)   (ThisClassBeginStorage + (i))

#define PYCCA_checkId(c, i)         assert((i) < COUNTOF(BeginStorage(c)))

#define PYCCA_checkThisClassId(i)   assert((i) < COUNTOF(ThisClassBeginStorage))

#ifndef COUNTOF
#define COUNTOF(a)  (sizeof(a) / sizeof(a[0]))
#endif /* COUNTOF */

/*
 * Code for Domain, "atctrl"
 */

#define INSTRUMENT 1

/*
 * implementation prolog code
 */

// Any additional implementation includes, etc.
#include <assert.h>
#include <time.h>
#include <string.h>
#include "atctrl.h"
typedef char const *Name_T ;
typedef time_t Date_T ;
typedef unsigned Aircraft_Quantity ;
typedef unsigned Aircraft_Maximum ;
typedef unsigned Duration ;
typedef char const *Experience_Level ;


#ifdef INSTRUMENT
#   ifndef INSTR_FUNC
#       ifdef TACK
#           include "harness.h"
#           define INSTR_FUNC(s) harness_stub_printf("instrument", "func %s file %s line %u", (s), __FILE__, __LINE__)
#       else
#           define INSTR_FUNC(s) printf("%s: %s %d\n", (s), __FILE__, __LINE__)
#       endif /* TACK */
#   endif /* INSTR_FUNC */
#endif /* INSTRUMENT */

/*
 * External Operations Declarations
 */
extern void eop_atctrl_Cannot_handoff_to_self(Employee_ID controller) ;
extern void eop_atctrl_Unknown_controller(Employee_ID controller) ;
extern void eop_atctrl_Zone_not_handled_by_controller(Employee_ID controller) ;
extern void eop_atctrl_Control_Zones_Active(Employee_ID atc) ;
extern void eop_atctrl_Break_required(Station_Number station) ;


typedef struct rlink {
    struct rlink *next ;
    struct rlink *prev ;
} rlink_t ;

static inline
rlink_t *
rlinkBegin(
    rlink_t *iter)
{
    return iter->next ;
}
static inline
rlink_t *
rlinkEnd(
    rlink_t *iter)
{
    return iter ;
}
static inline
bool
rlinkEmpty(
    rlink_t *iter)
{
    return iter->next == iter ;
}
static inline
bool
rlinkNotEmpty(
    rlink_t *iter)
{
    return iter->next != iter ;
}
static inline
void
rlinkInsert(
    rlink_t *item,
    rlink_t *at)
{
    item->prev = at->prev ;
    item->next = at ;
    at->prev->next = item ;
    at->prev = item ;
}
static inline
void
rlinkRemove(
    rlink_t *item)
{
    item->prev->next = item->next ;
    item->next->prev = item->prev ;
    item->next = item->prev = NULL ;
}
    
/*
 * State Numbering
 */
/*
 * State Numbers for Class, "Air_Traffic_Controller"
 */
#define Air_Traffic_Controller_OFF_DUTY_STATE 0
#define Air_Traffic_Controller_INITIAL_STATE 0
#define Air_Traffic_Controller_Verifying_Adequate_Break_STATE 1
#define Air_Traffic_Controller_Logging_In_STATE 2
#define Air_Traffic_Controller_ON_DUTY_STATE 3
#define Air_Traffic_Controller_Handing_off_Control_Zone_STATE 4
#define Air_Traffic_Controller_Logging_Out_STATE 5
#define Air_Traffic_Controller_Verifying_Full_Handoff_STATE 6
/*
 * State Numbers for Class, "Duty_Station"
 */
#define Duty_Station_AVAILABLE_STATE 0
#define Duty_Station_INITIAL_STATE 0
#define Duty_Station_IN_USE_STATE 1
#define Duty_Station_MAX_SHIFT_EXCEEDED_STATE 2
#define Duty_Station_Canceling_Shift_Timeout_STATE 3
/*
 * Pseudo initial states for inactive classes.
 */
#define Off_Duty_Controller_INITIAL_STATE 0
#define On_Duty_Controller_INITIAL_STATE 0
#define Control_Zone_INITIAL_STATE 0
#define Shift_Specification_INITIAL_STATE 0

/*
 * Event Numbering
 */
/*
 * Event Numbers for Class, "Air_Traffic_Controller"
 */
#define Air_Traffic_Controller_Cannot_go_on_duty_EVENT 0
#define Air_Traffic_Controller_Handoff_EVENT 1
#define Air_Traffic_Controller_Handoff_complete_EVENT 2
#define Air_Traffic_Controller_Log_in_EVENT 3
#define Air_Traffic_Controller_Log_out_EVENT 4
#define Air_Traffic_Controller_Logged_in_EVENT 5
#define Air_Traffic_Controller_Must_hand_off_zones_EVENT 6
#define Air_Traffic_Controller_Off_duty_EVENT 7
#define Air_Traffic_Controller_Ready_for_a_break_EVENT 8
#define Air_Traffic_Controller_Ready_for_duty_EVENT 9
/*
 * Event Numbers for Class, "Duty_Station"
 */
#define Duty_Station_Available_EVENT 0
#define Duty_Station_In_use_EVENT 1
#define Duty_Station_Max_shift_exceeded_EVENT 2
#define Duty_Station_User_leaving_EVENT 3

/*
 * Subtype Numbering
 */
/*
 * Subtype Numbers for Air_Traffic_Controller / R1
 */
#define Air_Traffic_Controller_R1_Off_Duty_Controller_CODE 0
#define Air_Traffic_Controller_R1_On_Duty_Controller_CODE 1

/*
 * Offsets to named instances
 */
#define Air_Traffic_Controller_atc53_INSTANCE 0
#define Air_Traffic_Controller_atc67_INSTANCE 1
#define Air_Traffic_Controller_atc51_INSTANCE 2
#define On_Duty_Controller_atc53_INSTANCE 0
#define On_Duty_Controller_atc67_INSTANCE 1
#define On_Duty_Controller_atc51_INSTANCE 2
#define Control_Zone_sfo_INSTANCE 0
#define Control_Zone_oak_INSTANCE 1
#define Control_Zone_sjc_INSTANCE 2
#define Duty_Station_s1_INSTANCE 0
#define Duty_Station_s2_INSTANCE 1
#define Duty_Station_s3_INSTANCE 2
#define Shift_Specification_singleton_INSTANCE 0

/*
 * Forward class structure declarations
 */
struct Air_Traffic_Controller ;
struct Off_Duty_Controller ;
struct On_Duty_Controller ;
struct Control_Zone ;
struct Duty_Station ;
struct Shift_Specification ;

/*
 * Class structure definitions
 */
struct Off_Duty_Controller {
    Date_T Last_shift_ended ;
} ;
struct On_Duty_Controller {
    Date_T Time_logged_in ;
    struct Duty_Station *R3 ;
    rlink_t R2 ;
} ;
struct Air_Traffic_Controller {
    struct mechinstance common_ ; // must be first !
    Employee_ID ID ;
    Name_T Name ;
    Experience_Level Rating ;
    SubtypeCode R1__code ;
    union {
        struct Off_Duty_Controller R1_Off_Duty_Controller ;
        struct On_Duty_Controller R1_On_Duty_Controller ;
    } R1 ;
} ;
struct Control_Zone {
    Czone_Name Name ;
    Aircraft_Quantity Traffic ;
    struct On_Duty_Controller *R2 ;
    rlink_t R2__links ;
} ;
struct Duty_Station {
    struct mechinstance common_ ; // must be first !
    Station_Number Number ;
    Name_T Location ;
    Aircraft_Maximum Capacity ;
    struct On_Duty_Controller *R3 ;
} ;
struct Shift_Specification {
    Duration Min_break ;
    Duration Max_shift ;
} ;

/*
 * Event Parameter Structure Definitions
 */
struct Air_Traffic_Controller_Handoff_rcvd_evt {
    Czone_Name zone ;
    Employee_ID controller ;
} ;
struct Air_Traffic_Controller_Log_in_rcvd_evt {
    Station_Number Station ;
} ;
struct Air_Traffic_Controller_Ready_for_duty_rcvd_evt {
    Station_Number Station ;
} ;


/*
 * Forward Operation Function Declarations
 */

/*
 * Forward Declarations of Class Constructors
 */

/*
 * Forward Declarations of Class Destructors
 */

/*
 * Forward Declarations of State Action Functions
 */
static void Air_Traffic_Controller_Logging_Out(void *const s_, void *const p_) ;
static void Air_Traffic_Controller_OFF_DUTY(void *const s_, void *const p_) ;
static void Air_Traffic_Controller_ON_DUTY(void *const s_, void *const p_) ;
static void Air_Traffic_Controller_Verifying_Full_Handoff(void *const s_, void *const p_) ;
static void Air_Traffic_Controller_Handing_off_Control_Zone(void *const s_, void *const p_) ;
static void Air_Traffic_Controller_Logging_In(void *const s_, void *const p_) ;
static void Air_Traffic_Controller_Verifying_Adequate_Break(void *const s_, void *const p_) ;
static void Duty_Station_AVAILABLE(void *const s_, void *const p_) ;
static void Duty_Station_Canceling_Shift_Timeout(void *const s_, void *const p_) ;
static void Duty_Station_IN_USE(void *const s_, void *const p_) ;
static void Duty_Station_MAX_SHIFT_EXCEEDED(void *const s_, void *const p_) ;

/*
 * Domain Operations External Declarations
 */
extern void atctrl_init(void) ;

/*
 * Declaration of Function to Construct Initial Instances
 */

/*
 * Forward Instance Storage Declarations
 */
static struct Air_Traffic_Controller Air_Traffic_Controller_storage[] ;
static struct Control_Zone Control_Zone_storage[] ;
static struct Duty_Station Duty_Station_storage[] ;
static struct Shift_Specification Shift_Specification_storage[] ;


/*
 * Instance Allocation Block Definitions
 */

/*
 * AODB for Class, "Air_Traffic_Controller"
 */
static PtrActionFunction const Air_Traffic_Controller_acttbl[] = {
    Air_Traffic_Controller_OFF_DUTY,
    Air_Traffic_Controller_Verifying_Adequate_Break,
    Air_Traffic_Controller_Logging_In,
    Air_Traffic_Controller_ON_DUTY,
    Air_Traffic_Controller_Handing_off_Control_Zone,
    Air_Traffic_Controller_Logging_Out,
    Air_Traffic_Controller_Verifying_Full_Handoff,
} ;
static StateCode const Air_Traffic_Controller_transtbl[] = {
    MECH_STATECODE_CH, // OFF_DUTY - Cannot_go_on_duty -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Handoff -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Handoff_complete -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Log_in -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Log_out -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Logged_in -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Must_hand_off_zones -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Off_duty -> CH
    MECH_STATECODE_CH, // OFF_DUTY - Ready_for_a_break -> CH
    1, // OFF_DUTY - Ready_for_duty -> Verifying_Adequate_Break
    0, // Verifying_Adequate_Break - Cannot_go_on_duty -> OFF_DUTY
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Handoff -> CH
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Handoff_complete -> CH
    2, // Verifying_Adequate_Break - Log_in -> Logging_In
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Log_out -> CH
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Logged_in -> CH
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Must_hand_off_zones -> CH
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Off_duty -> CH
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Ready_for_a_break -> CH
    MECH_STATECODE_CH, // Verifying_Adequate_Break - Ready_for_duty -> CH
    MECH_STATECODE_CH, // Logging_In - Cannot_go_on_duty -> CH
    MECH_STATECODE_CH, // Logging_In - Handoff -> CH
    MECH_STATECODE_CH, // Logging_In - Handoff_complete -> CH
    MECH_STATECODE_CH, // Logging_In - Log_in -> CH
    MECH_STATECODE_CH, // Logging_In - Log_out -> CH
    3, // Logging_In - Logged_in -> ON_DUTY
    MECH_STATECODE_CH, // Logging_In - Must_hand_off_zones -> CH
    MECH_STATECODE_CH, // Logging_In - Off_duty -> CH
    MECH_STATECODE_CH, // Logging_In - Ready_for_a_break -> CH
    MECH_STATECODE_CH, // Logging_In - Ready_for_duty -> CH
    MECH_STATECODE_CH, // ON_DUTY - Cannot_go_on_duty -> CH
    4, // ON_DUTY - Handoff -> Handing_off_Control_Zone
    MECH_STATECODE_CH, // ON_DUTY - Handoff_complete -> CH
    MECH_STATECODE_CH, // ON_DUTY - Log_in -> CH
    MECH_STATECODE_CH, // ON_DUTY - Log_out -> CH
    MECH_STATECODE_CH, // ON_DUTY - Logged_in -> CH
    MECH_STATECODE_CH, // ON_DUTY - Must_hand_off_zones -> CH
    MECH_STATECODE_CH, // ON_DUTY - Off_duty -> CH
    6, // ON_DUTY - Ready_for_a_break -> Verifying_Full_Handoff
    MECH_STATECODE_CH, // ON_DUTY - Ready_for_duty -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Cannot_go_on_duty -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Handoff -> CH
    3, // Handing_off_Control_Zone - Handoff_complete -> ON_DUTY
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Log_in -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Log_out -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Logged_in -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Must_hand_off_zones -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Off_duty -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Ready_for_a_break -> CH
    MECH_STATECODE_CH, // Handing_off_Control_Zone - Ready_for_duty -> CH
    MECH_STATECODE_CH, // Logging_Out - Cannot_go_on_duty -> CH
    MECH_STATECODE_CH, // Logging_Out - Handoff -> CH
    MECH_STATECODE_CH, // Logging_Out - Handoff_complete -> CH
    MECH_STATECODE_CH, // Logging_Out - Log_in -> CH
    MECH_STATECODE_CH, // Logging_Out - Log_out -> CH
    MECH_STATECODE_CH, // Logging_Out - Logged_in -> CH
    MECH_STATECODE_CH, // Logging_Out - Must_hand_off_zones -> CH
    0, // Logging_Out - Off_duty -> OFF_DUTY
    MECH_STATECODE_CH, // Logging_Out - Ready_for_a_break -> CH
    MECH_STATECODE_CH, // Logging_Out - Ready_for_duty -> CH
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Cannot_go_on_duty -> CH
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Handoff -> CH
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Handoff_complete -> CH
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Log_in -> CH
    5, // Verifying_Full_Handoff - Log_out -> Logging_Out
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Logged_in -> CH
    3, // Verifying_Full_Handoff - Must_hand_off_zones -> ON_DUTY
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Off_duty -> CH
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Ready_for_a_break -> CH
    MECH_STATECODE_CH, // Verifying_Full_Handoff - Ready_for_duty -> CH
} ;
static struct objectdispatchblock const Air_Traffic_Controller_odb = {
    .stateCount = 7,
    .eventCount = 10,
    .transitionTable = Air_Traffic_Controller_transtbl,
    .actionTable = Air_Traffic_Controller_acttbl,
    .finalStates = NULL
} ;
/*
 * AODB for Class, "Duty_Station"
 */
static PtrActionFunction const Duty_Station_acttbl[] = {
    Duty_Station_AVAILABLE,
    Duty_Station_IN_USE,
    Duty_Station_MAX_SHIFT_EXCEEDED,
    Duty_Station_Canceling_Shift_Timeout,
} ;
static StateCode const Duty_Station_transtbl[] = {
    MECH_STATECODE_CH, // AVAILABLE - Available -> CH
    1, // AVAILABLE - In_use -> IN_USE
    MECH_STATECODE_CH, // AVAILABLE - Max_shift_exceeded -> CH
    MECH_STATECODE_CH, // AVAILABLE - User_leaving -> CH
    MECH_STATECODE_CH, // IN_USE - Available -> CH
    MECH_STATECODE_CH, // IN_USE - In_use -> CH
    2, // IN_USE - Max_shift_exceeded -> MAX_SHIFT_EXCEEDED
    3, // IN_USE - User_leaving -> Canceling_Shift_Timeout
    MECH_STATECODE_CH, // MAX_SHIFT_EXCEEDED - Available -> CH
    MECH_STATECODE_CH, // MAX_SHIFT_EXCEEDED - In_use -> CH
    MECH_STATECODE_CH, // MAX_SHIFT_EXCEEDED - Max_shift_exceeded -> CH
    0, // MAX_SHIFT_EXCEEDED - User_leaving -> AVAILABLE
    0, // Canceling_Shift_Timeout - Available -> AVAILABLE
    MECH_STATECODE_CH, // Canceling_Shift_Timeout - In_use -> CH
    MECH_STATECODE_CH, // Canceling_Shift_Timeout - Max_shift_exceeded -> CH
    MECH_STATECODE_CH, // Canceling_Shift_Timeout - User_leaving -> CH
} ;
static struct objectdispatchblock const Duty_Station_odb = {
    .stateCount = 4,
    .eventCount = 4,
    .transitionTable = Duty_Station_transtbl,
    .actionTable = Duty_Station_acttbl,
    .finalStates = NULL
} ;


/*
 * Class Structure for, "Air_Traffic_Controller"
 */
static struct mechclass const Air_Traffic_Controller_class = {
    .iab = NULL,
    .odb = &Air_Traffic_Controller_odb,
    .pdb = NULL
} ;
/*
 * Class Structure for, "Duty_Station"
 */
static struct mechclass const Duty_Station_class = {
    .iab = NULL,
    .odb = &Duty_Station_odb,
    .pdb = NULL
} ;


/*
 * Data Portal data structures
 */
#include "pycca_portal.h"
static struct pycca_attr_portal const Air_Traffic_Controller_attr_portal[4] = {
    {.offset = offsetof(struct Air_Traffic_Controller, ID), .size = sizeof(Air_Traffic_Controller_storage->ID)},
    {.offset = offsetof(struct Air_Traffic_Controller, Name), .size = sizeof(Air_Traffic_Controller_storage->Name)},
    {.offset = offsetof(struct Air_Traffic_Controller, Rating), .size = sizeof(Air_Traffic_Controller_storage->Rating)},
    {.offset = offsetof(struct Air_Traffic_Controller, R1__code), .size = sizeof(Air_Traffic_Controller_storage->R1__code)},
} ;
static struct pycca_attr_portal const Off_Duty_Controller_attr_portal[1] = {
    {.offset = offsetof(struct Off_Duty_Controller, Last_shift_ended), .size = sizeof(Air_Traffic_Controller_storage->R1.R1_Off_Duty_Controller.Last_shift_ended)},
} ;
static struct pycca_attr_portal const On_Duty_Controller_attr_portal[1] = {
    {.offset = offsetof(struct On_Duty_Controller, Time_logged_in), .size = sizeof(Air_Traffic_Controller_storage->R1.R1_On_Duty_Controller.Time_logged_in)},
} ;
static struct pycca_attr_portal const Control_Zone_attr_portal[2] = {
    {.offset = offsetof(struct Control_Zone, Name), .size = sizeof(Control_Zone_storage->Name)},
    {.offset = offsetof(struct Control_Zone, Traffic), .size = sizeof(Control_Zone_storage->Traffic)},
} ;
static struct pycca_attr_portal const Duty_Station_attr_portal[3] = {
    {.offset = offsetof(struct Duty_Station, Number), .size = sizeof(Duty_Station_storage->Number)},
    {.offset = offsetof(struct Duty_Station, Location), .size = sizeof(Duty_Station_storage->Location)},
    {.offset = offsetof(struct Duty_Station, Capacity), .size = sizeof(Duty_Station_storage->Capacity)},
} ;
static struct pycca_attr_portal const Shift_Specification_attr_portal[2] = {
    {.offset = offsetof(struct Shift_Specification, Min_break), .size = sizeof(Shift_Specification_storage->Min_break)},
    {.offset = offsetof(struct Shift_Specification, Max_shift), .size = sizeof(Shift_Specification_storage->Max_shift)},
} ;
static struct pycca_class_portal const atctrl_class_portal[] = {
    {.storage = Air_Traffic_Controller_storage, .attrs = Air_Traffic_Controller_attr_portal, .mechClass = &Air_Traffic_Controller_class, .numAttrs = 4, .numInsts = 3, .instSize = sizeof(struct Air_Traffic_Controller), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Air_Traffic_Controller_INITIAL_STATE},
    {.storage = Air_Traffic_Controller_storage, .attrs = Off_Duty_Controller_attr_portal, .mechClass = NULL, .numAttrs = 1, .numInsts = 3, .instSize = sizeof(struct Air_Traffic_Controller), .instOffset = offsetof(struct Air_Traffic_Controller, R1.R1_Off_Duty_Controller), .isConst = 0, .hasCommon = 0, .initialState = Off_Duty_Controller_INITIAL_STATE},
    {.storage = Air_Traffic_Controller_storage, .attrs = On_Duty_Controller_attr_portal, .mechClass = NULL, .numAttrs = 1, .numInsts = 3, .instSize = sizeof(struct Air_Traffic_Controller), .instOffset = offsetof(struct Air_Traffic_Controller, R1.R1_On_Duty_Controller), .isConst = 0, .hasCommon = 0, .initialState = On_Duty_Controller_INITIAL_STATE},
    {.storage = Control_Zone_storage, .attrs = Control_Zone_attr_portal, .mechClass = NULL, .numAttrs = 2, .numInsts = 3, .instSize = sizeof(struct Control_Zone), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Control_Zone_INITIAL_STATE},
    {.storage = Duty_Station_storage, .attrs = Duty_Station_attr_portal, .mechClass = &Duty_Station_class, .numAttrs = 3, .numInsts = 3, .instSize = sizeof(struct Duty_Station), .instOffset = 0, .isConst = 0, .hasCommon = 1, .initialState = Duty_Station_INITIAL_STATE},
    {.storage = Shift_Specification_storage, .attrs = Shift_Specification_attr_portal, .mechClass = NULL, .numAttrs = 2, .numInsts = 1, .instSize = sizeof(struct Shift_Specification), .instOffset = 0, .isConst = 0, .hasCommon = 0, .initialState = Shift_Specification_INITIAL_STATE},
} ;
struct pycca_domain_portal const atctrl_portal = {
    .classes = atctrl_class_portal,
    .numClasses = 6
} ;

/*
 * Multi-ref pointer arrays
 */

/*
 * Initial Instance Storage for, "Air_Traffic_Controller"
 */
static struct Air_Traffic_Controller Air_Traffic_Controller_storage[3] = {
    {.common_ = {1, 0, &Air_Traffic_Controller_class}, "53", "Toshiko", "A", .R1__code = 1, .R1 = {.R1_On_Duty_Controller = {0, .R3 = &Duty_Station_storage[1], .R2 = {.next = &Control_Zone_storage[0].R2__links, .prev = &Control_Zone_storage[0].R2__links}}}},
    {.common_ = {2, 0, &Air_Traffic_Controller_class}, "67", "Gwen", "B", .R1__code = 1, .R1 = {.R1_On_Duty_Controller = {0, .R3 = &Duty_Station_storage[0], .R2 = {.next = &Control_Zone_storage[1].R2__links, .prev = &Control_Zone_storage[1].R2__links}}}},
    {.common_ = {3, 0, &Air_Traffic_Controller_class}, "51", "Ianto", "C", .R1__code = 1, .R1 = {.R1_On_Duty_Controller = {0, .R3 = &Duty_Station_storage[2], .R2 = {.next = &Control_Zone_storage[2].R2__links, .prev = &Control_Zone_storage[2].R2__links}}}}
} ;
/*
 * Initial Instance Storage for, "Control_Zone"
 */
static struct Control_Zone Control_Zone_storage[3] = {
    {"SFO37B", 27, .R2 = &Air_Traffic_Controller_storage[0].R1.R1_On_Duty_Controller, .R2__links = {.next = &Air_Traffic_Controller_storage[0].R1.R1_On_Duty_Controller.R2, .prev = &Air_Traffic_Controller_storage[0].R1.R1_On_Duty_Controller.R2, }},
    {"OAK21C", 18, .R2 = &Air_Traffic_Controller_storage[1].R1.R1_On_Duty_Controller, .R2__links = {.next = &Air_Traffic_Controller_storage[1].R1.R1_On_Duty_Controller.R2, .prev = &Air_Traffic_Controller_storage[1].R1.R1_On_Duty_Controller.R2, }},
    {"SJC18C", 9, .R2 = &Air_Traffic_Controller_storage[2].R1.R1_On_Duty_Controller, .R2__links = {.next = &Air_Traffic_Controller_storage[2].R1.R1_On_Duty_Controller.R2, .prev = &Air_Traffic_Controller_storage[2].R1.R1_On_Duty_Controller.R2, }}
} ;
/*
 * Initial Instance Storage for, "Duty_Station"
 */
static struct Duty_Station Duty_Station_storage[3] = {
    {.common_ = {1, 0, &Duty_Station_class}, "S1", "Front", 20, .R3 = NULL},
    {.common_ = {2, 0, &Duty_Station_class}, "S2", "Center", 30, .R3 = NULL},
    {.common_ = {3, 0, &Duty_Station_class}, "S3", "Front", 45, .R3 = NULL}
} ;
/*
 * Initial Instance Storage for, "Shift_Specification"
 */
static struct Shift_Specification Shift_Specification_storage[1] = {
    {15 * 60, (2 * 60 + 15) * 60}
} ;

/*
 * Operation Function Definitions
 */

/*
 * Constructor Function Definitions
 */

/*
 * Destructor Function Definitions
 */

/*
 * State Action Function Definitions
 */
#define THISCLASS__ Air_Traffic_Controller
static void Air_Traffic_Controller_OFF_DUTY(void *const s_, void *const p_)
{
#define THISSTATE__ OFF_DUTY
    INSTR_FUNC("atctrl.Air_Traffic_Controller.OFF_DUTY") ;

    // no activity for this state
#undef THISSTATE__
}
static void Air_Traffic_Controller_ON_DUTY(void *const s_, void *const p_)
{
#define THISSTATE__ ON_DUTY
    INSTR_FUNC("atctrl.Air_Traffic_Controller.ON_DUTY") ;

    // no activity for this state
#undef THISSTATE__
}
static void Air_Traffic_Controller_Logging_Out(void *const s_, void *const p_)
{
#define THISSTATE__ Logging_Out
    INSTR_FUNC("atctrl.Air_Traffic_Controller.Logging_Out") ;
    struct Air_Traffic_Controller *const self = (struct Air_Traffic_Controller *)s_ ;

    //+ User leaving -> /R3/Duty Station
    assert(self->SubCodeMember(R1) ==
            SubCodeValue(Air_Traffic_Controller, R1,
            On_Duty_Controller)) ;
    ClassRefVar(On_Duty_Controller, ondc) =
            PYCCA_unionSubtype(self, R1, On_Duty_Controller) ;
    ClassRefVar(Duty_Station, ds) = ondc->R3 ;
    assert(ds != NULL) ;
    PYCCA_generate(User_leaving, Duty_Station, ds, self) ;

    //+ migrate to Off Duty Controller
    ondc->R3 = NULL ;
    ds->R3 = NULL ;
    PYCCA_migrateSubtype(self, Air_Traffic_Controller, R1,
            Off_Duty_Controller) ;

    //+ Last shift ended = _now.HMS
    ClassRefVar(Off_Duty_Controller, offdc) =
            PYCCA_unionSubtype(self, R1, Off_Duty_Controller) ;
    offdc->Last_shift_ended = time(NULL) ;

    //+ Off duty -> me
    PYCCA_generateToSelf(Off_duty) ;
#undef THISSTATE__
}
static void Air_Traffic_Controller_Verifying_Full_Handoff(void *const s_, void *const p_)
{
#define THISSTATE__ Verifying_Full_Handoff
    INSTR_FUNC("atctrl.Air_Traffic_Controller.Verifying_Full_Handoff") ;
    struct Air_Traffic_Controller *const self = (struct Air_Traffic_Controller *)s_ ;

    ClassRefVar(On_Duty_Controller, ondc) =
            PYCCA_unionSubtype(self, R1, On_Duty_Controller) ;

    //+ if /R1/On Duty Controller/R2/Control Zone {
    if (PYCCA_isLinkNotEmpty(ondc, R2)) {
        //+ Must handoff zones -> me
        PYCCA_generateToSelf(Must_hand_off_zones) ;

        //+  UI.Control Zones Active( ATC: ID )
        ExternalOp(Control_Zones_Active)(self->ID) ;
    } else {
        //+ Log out -> me
        PYCCA_generateToSelf(Log_out) ;
    }
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Air_Traffic_Controller
static void Air_Traffic_Controller_Handing_off_Control_Zone(void *const s_, void *const p_)
{
#define THISSTATE__ Handing_off_Control_Zone
    INSTR_FUNC("atctrl.Air_Traffic_Controller.Handing_off_Control_Zone") ;
    struct Air_Traffic_Controller *const self = (struct Air_Traffic_Controller *)s_ ;
    struct Air_Traffic_Controller_Handing_off_Control_Zone_rcvd_evt {
        Czone_Name zone ;
        Employee_ID controller ;
    } const *const rcvd_evt = (struct Air_Traffic_Controller_Handing_off_Control_Zone_rcvd_evt const *)p_ ;

    //+ hoff zone .= /R2/Control Zone( Name: in.Zone )
    ClassRefVar(On_Duty_Controller, ondc) =
            PYCCA_unionSubtype(self, R1, On_Duty_Controller) ;
    ClassRefVar(Control_Zone, hoff_zone) = NULL ;
    rlink_t *czlink ;
    PYCCA_forAllLinkedInst(ondc, R2, czlink) {
        ClassRefVar(Control_Zone, found) =
                PYCCA_linkToInstRef(czlink, Control_Zone, R2) ;
        if (strcmp(rcvd_evt->zone, found->Name) == 0) {
            hoff_zone = found ;
            break ;
        }
    }
    assert(hoff_zone != NULL) ;

    //+ if in.Controller == ID
    if (strcmp(rcvd_evt->controller, self->ID) == 0) {
        //+ UI.Cannot handoff to self( Controller: in.Controller )
        ExternalOp(Cannot_handoff_to_self)(rcvd_evt->controller) ;
    } else {
        //+ new controller .= On Duty Controller( ID: in.Controller )
        ClassRefVar(Air_Traffic_Controller, new_controller) ;
        PYCCA_selectOneStaticInstWhere(new_controller,
            Air_Traffic_Controller,
            strcmp(new_controller->ID, rcvd_evt->controller) == 0 &&
            new_controller->SubCodeMember(R1) ==
                SubCodeValue(Air_Traffic_Controller, R1, On_Duty_Controller)) ;

        if (new_controller == EndStorage(Air_Traffic_Controller)) {
            //+ !new missing: UI.Unknown controller( Controller: in.Controller)
            ExternalOp(Unknown_controller)(rcvd_evt->controller) ;
        } else if (hoff_zone->R2 != ondc) {
            //+ !old missing: UI.Zone not handled by( Controller: ID)
            ExternalOp(Zone_not_handled_by_controller)(self->ID) ;
        } else {
            //+ swap hoff zone/R2/On Duty Controller with new controller
            ClassRefVar(On_Duty_Controller, new_ondc) =
                PYCCA_unionSubtype(new_controller, R1,
                    On_Duty_Controller) ;
            PYCCA_unlinkFromMany(hoff_zone, R2) ;
            PYCCA_linkToMany(new_ondc, R2, hoff_zone) ;
            hoff_zone->R2 = new_ondc ;
        }
    }

    //+ Handoff complete -> me
    PYCCA_generateToSelf(Handoff_complete) ;
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Air_Traffic_Controller
static void Air_Traffic_Controller_Verifying_Adequate_Break(void *const s_, void *const p_)
{
#define THISSTATE__ Verifying_Adequate_Break
    INSTR_FUNC("atctrl.Air_Traffic_Controller.Verifying_Adequate_Break") ;
    struct Air_Traffic_Controller *const self = (struct Air_Traffic_Controller *)s_ ;
    struct Air_Traffic_Controller_Verifying_Adequate_Break_rcvd_evt {
        Station_Number Station ;
    } const *const rcvd_evt = (struct Air_Traffic_Controller_Verifying_Adequate_Break_rcvd_evt const *)p_ ;

    //+ the shift spec .= Shift Specification() // selects singleton
    ClassRefVar(Shift_Specification, the_shift_spec) =
            Instance(Shift_Specification, singleton) ;

    ClassRefVar(Off_Duty_Controller, offdc) =
        PYCCA_unionSubtype(self, R1, Off_Duty_Controller) ;

    //+ if ( _now - self.Last shift ended < the shift spec.Min break )
    if (offdc->Last_shift_ended == 0 ||
            time(NULL) - offdc->Last_shift_ended < the_shift_spec->Min_break) {
        //+ Log in( in.Station ) -> me
        MechEcb li_sig = PYCCA_newEvent(Log_in, Air_Traffic_Controller, self,
                self) ;
        PYCCA_eventParam(li_sig, Air_Traffic_Controller, Log_in, Station) =
                rcvd_evt->Station ;
        PYCCA_postSelfEvent(li_sig) ;
    } else {
        //+ Cannot go on duty -> me
        PYCCA_generateToSelf(Cannot_go_on_duty) ;
    }
#undef THISSTATE__
}
static void Air_Traffic_Controller_Logging_In(void *const s_, void *const p_)
{
#define THISSTATE__ Logging_In
    INSTR_FUNC("atctrl.Air_Traffic_Controller.Logging_In") ;
    struct Air_Traffic_Controller *const self = (struct Air_Traffic_Controller *)s_ ;
    struct Air_Traffic_Controller_Logging_In_rcvd_evt {
        Station_Number Station ;
    } const *const rcvd_evt = (struct Air_Traffic_Controller_Logging_In_rcvd_evt const *)p_ ;

    //+ migrate to On Duty Controller
    PYCCA_migrateSubtype(self, Air_Traffic_Controller, R1,
            On_Duty_Controller) ;

    //+ my station = Duty Station( Number: in.Station )
    ClassRefVar(Duty_Station, my_station) ;
    PYCCA_selectOneStaticInstWhere(my_station, Duty_Station,
            strcmp(my_station->Number, rcvd_evt->Station) == 0) ;
    assert(my_station != EndStorage(Duty_Station)) ;

    //+ & /R3/my station    // link station
    ClassRefVar(On_Duty_Controller, ondc) =
            PYCCA_unionSubtype(self, R1, On_Duty_Controller) ;
    ondc->R3 = my_station ;
    my_station->R3 = ondc ;

    //+ Time logged in = _now.HMS
    ondc->Time_logged_in = time(NULL) ;

    //+ Logged in -> me
    PYCCA_generateToSelf(Logged_in) ;

    //+ In use -> my station
    PYCCA_generate(In_use, Duty_Station, my_station, self) ;
#undef THISSTATE__
}
#undef THISCLASS__
#define THISCLASS__ Duty_Station
static void Duty_Station_AVAILABLE(void *const s_, void *const p_)
{
#define THISSTATE__ AVAILABLE
    INSTR_FUNC("atctrl.Duty_Station.AVAILABLE") ;

    // no activity in this state
#undef THISSTATE__
}
static void Duty_Station_IN_USE(void *const s_, void *const p_)
{
#define THISSTATE__ IN_USE
    INSTR_FUNC("atctrl.Duty_Station.IN_USE") ;
    struct Duty_Station *const self = (struct Duty_Station *)s_ ;

    //+ selects singleton
    ClassRefVar(Shift_Specification, ss) =
            Instance(Shift_Specification, singleton) ;

    //+ Max shift exceeded -> me after Shift Specification().Max shift
    PYCCA_generateDelayedToSelf(Max_shift_exceeded,
            ss->Max_shift * 1000UL) ; // delay times are in ms
#undef THISSTATE__
}
static void Duty_Station_MAX_SHIFT_EXCEEDED(void *const s_, void *const p_)
{
#define THISSTATE__ MAX_SHIFT_EXCEEDED
    INSTR_FUNC("atctrl.Duty_Station.MAX_SHIFT_EXCEEDED") ;
    struct Duty_Station *const self = (struct Duty_Station *)s_ ;

    //+UI.Break required( Station: Number )
    ExternalOp(Break_required)(self->Number) ;
#undef THISSTATE__
}
static void Duty_Station_Canceling_Shift_Timeout(void *const s_, void *const p_)
{
#define THISSTATE__ Canceling_Shift_Timeout
    INSTR_FUNC("atctrl.Duty_Station.Canceling_Shift_Timeout") ;
    struct Duty_Station *const self = (struct Duty_Station *)s_ ;

    //+ cancel Max shift exceeded -> me
    PYCCA_cancelDelayedToSelf(Max_shift_exceeded) ;

    //+ Available -> me
    PYCCA_generateToSelf(Available) ;
#undef THISSTATE__
}
#undef THISCLASS__

/*
 * Domain Operation Definitions
 */
void atctrl_init(void)
{
    INSTR_FUNC("atctrl.init") ;

    // Your code here.
}

/*
 * Definition of Function to Construct Initial Instances
 */




