/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: /home/andrewm/working/modelstocode/mtc_source/tools/linux/tack/lib/application/main.tcl, Revision: 3.8.1
 * Generated on: Sat Apr 15 14:54:00 PDT 2017
 */

/*
 * INCLUDE FILES
 */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <inttypes.h>
#include <string.h>

#include "./sioharness.h"
#include "harness.h"
#include "pycca_portal.h"

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL DATA DEFINITIONS
 */

/*
 * STATIC DATA DEFINITIONS
 */

static char const empty_string[] = "" ;
static char cvt_buffer[BUFSIZ] ;
static char const bad_param_msg[] = "bad parameter: %s" ;
static char const wrong_args_msg[] =
        "wrong # of arguments: got %d, expected %d" ;
static char const read_err_msg[] = "pycca_read_attr error = %d" ;
static char const write_err_msg[] = "pycca_write_attr error = %d" ;
static char const bad_attr_value_msg[] = "bad value %s" ;
static char const stubLabel[] = "stub" ;

#include "sio.h"
/*
 * FORWARD FUNCTION DECLARATIONS
 */
static bool sio_init_dop(int argc, char const *const *argv, char const **result) ;
static bool sio_Read_point_dop(int argc, char const *const *argv, char const **result) ;
static bool sio_Write_point_dop(int argc, char const *const *argv, char const **result) ;
static bool sio_Packed_Point_Length_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Packed_Point_Length_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Packed_Point_Offset_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Packed_Point_Offset_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Signalling_Point_Value_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Signalling_Point_Value_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Signalling_Point_Trigger_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Signalling_Point_Trigger_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Signalling_Point_Active_high_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Signalling_Point_Active_high_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Signalling_Point_Debounce_time_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Signalling_Point_Debounce_time_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Control_Point_Memory_model_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Control_Point_Memory_model_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Control_Point_Access_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Control_Point_Access_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Continuous_Input_Point_Value_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Continuous_Input_Point_Value_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Scaling_Multiplier_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Scaling_Multiplier_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Scaling_Divisor_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Scaling_Divisor_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Scaling_Intercept_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Scaling_Intercept_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Scaling_Mask_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Scaling_Mask_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Threshold_Limit_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Threshold_Limit_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Threshold_Direction_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Threshold_Direction_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Threshold_Over_limit_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Threshold_Over_limit_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Point_Threshold_Under_limit_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Point_Threshold_Under_limit_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Range_Limitation_Over_count_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Range_Limitation_Over_count_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Range_Limitation_Under_count_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Range_Limitation_Under_count_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Signal_Converter_Converter_available_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Signal_Converter_Converter_available_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Conversion_Group_Waiting_for_converter_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Conversion_Group_Waiting_for_converter_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;
static bool sio_Conversion_Group_Period_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result) ;
static bool sio_Conversion_Group_Period_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result) ;

static int sio_Range_Limitation_New_point_fmt(EventParamType *params, int argc, char const **argv) ;


/*
 * STATIC DATA DEFINITIONS
 */
static dop_map_t const sio_domain_op[] = {
    {"Read_point", sio_Read_point_dop},
    {"Write_point", sio_Write_point_dop},
    {"init", sio_init_dop},
} ;

static attr_map_t const sio_Continuous_Input_Point_attr_map[] = {
    {.name = "Value",
     .id = SIO_CONTINUOUS_INPUT_POINT_VALUE_ATTR_ID,
     .attr_read = sio_Continuous_Input_Point_Value_read,
     .attr_update = sio_Continuous_Input_Point_Value_update},
} ;
static inst_map_t const sio_Continuous_Input_Point_inst_map[] = {
    {.name = "iop1",
     .id = SIO_IO_POINT_IOP1_INST_ID},
    {.name = "iop2",
     .id = SIO_IO_POINT_IOP2_INST_ID},
    {.name = "iop3",
     .id = SIO_IO_POINT_IOP3_INST_ID},
} ;
static attr_map_t const sio_Control_Point_attr_map[] = {
    {.name = "Access",
     .id = SIO_CONTROL_POINT_ACCESS_ATTR_ID,
     .attr_read = sio_Control_Point_Access_read,
     .attr_update = sio_Control_Point_Access_update},
    {.name = "Memory_model",
     .id = SIO_CONTROL_POINT_MEMORY_MODEL_ATTR_ID,
     .attr_read = sio_Control_Point_Memory_model_read,
     .attr_update = sio_Control_Point_Memory_model_update},
} ;
static inst_map_t const sio_Control_Point_inst_map[] = {
    {.name = "iop4",
     .id = SIO_IO_POINT_IOP4_INST_ID},
    {.name = "iop5",
     .id = SIO_IO_POINT_IOP5_INST_ID},
    {.name = "iop6",
     .id = SIO_IO_POINT_IOP6_INST_ID},
} ;
static attr_map_t const sio_Conversion_Group_attr_map[] = {
    {.name = "Period",
     .id = SIO_CONVERSION_GROUP_PERIOD_ATTR_ID,
     .attr_read = sio_Conversion_Group_Period_read,
     .attr_update = sio_Conversion_Group_Period_update},
    {.name = "Waiting_for_converter",
     .id = SIO_CONVERSION_GROUP_WAITING_FOR_CONVERTER_ATTR_ID,
     .attr_read = sio_Conversion_Group_Waiting_for_converter_read,
     .attr_update = sio_Conversion_Group_Waiting_for_converter_update},
} ;
static inst_map_t const sio_Conversion_Group_inst_map[] = {
    {.name = "inj1_cg",
     .id = SIO_CONVERSION_GROUP_INJ1_CG_INST_ID},
    {.name = "inj2_cg",
     .id = SIO_CONVERSION_GROUP_INJ2_CG_INST_ID},
    {.name = "inj3_cg",
     .id = SIO_CONVERSION_GROUP_INJ3_CG_INST_ID},
} ;
static event_map_t const sio_Conversion_Group_event_map[] = {
    {.name = "Conversion_done",
     .id = SIO_CONVERSION_GROUP_CONVERSION_DONE_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "Sample",
     .id = SIO_CONVERSION_GROUP_SAMPLE_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "Stop",
     .id = SIO_CONVERSION_GROUP_STOP_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
} ;
static attr_map_t const sio_Packed_Point_attr_map[] = {
    {.name = "Length",
     .id = SIO_PACKED_POINT_LENGTH_ATTR_ID,
     .attr_read = sio_Packed_Point_Length_read,
     .attr_update = sio_Packed_Point_Length_update},
    {.name = "Offset",
     .id = SIO_PACKED_POINT_OFFSET_ATTR_ID,
     .attr_read = sio_Packed_Point_Offset_read,
     .attr_update = sio_Packed_Point_Offset_update},
} ;
static attr_map_t const sio_Point_Scaling_attr_map[] = {
    {.name = "Divisor",
     .id = SIO_POINT_SCALING_DIVISOR_ATTR_ID,
     .attr_read = sio_Point_Scaling_Divisor_read,
     .attr_update = sio_Point_Scaling_Divisor_update},
    {.name = "Intercept",
     .id = SIO_POINT_SCALING_INTERCEPT_ATTR_ID,
     .attr_read = sio_Point_Scaling_Intercept_read,
     .attr_update = sio_Point_Scaling_Intercept_update},
    {.name = "Mask",
     .id = SIO_POINT_SCALING_MASK_ATTR_ID,
     .attr_read = sio_Point_Scaling_Mask_read,
     .attr_update = sio_Point_Scaling_Mask_update},
    {.name = "Multiplier",
     .id = SIO_POINT_SCALING_MULTIPLIER_ATTR_ID,
     .attr_read = sio_Point_Scaling_Multiplier_read,
     .attr_update = sio_Point_Scaling_Multiplier_update},
} ;
static inst_map_t const sio_Point_Scaling_inst_map[] = {
    {.name = "ihn4_pres_scale",
     .id = SIO_POINT_SCALING_IHN4_PRES_SCALE_INST_ID},
    {.name = "ix77b_pres_scale",
     .id = SIO_POINT_SCALING_IX77B_PRES_SCALE_INST_ID},
} ;
static attr_map_t const sio_Point_Threshold_attr_map[] = {
    {.name = "Direction",
     .id = SIO_POINT_THRESHOLD_DIRECTION_ATTR_ID,
     .attr_read = sio_Point_Threshold_Direction_read,
     .attr_update = sio_Point_Threshold_Direction_update},
    {.name = "Limit",
     .id = SIO_POINT_THRESHOLD_LIMIT_ATTR_ID,
     .attr_read = sio_Point_Threshold_Limit_read,
     .attr_update = sio_Point_Threshold_Limit_update},
    {.name = "Over_limit",
     .id = SIO_POINT_THRESHOLD_OVER_LIMIT_ATTR_ID,
     .attr_read = sio_Point_Threshold_Over_limit_read,
     .attr_update = sio_Point_Threshold_Over_limit_update},
    {.name = "Under_limit",
     .id = SIO_POINT_THRESHOLD_UNDER_LIMIT_ATTR_ID,
     .attr_read = sio_Point_Threshold_Under_limit_read,
     .attr_update = sio_Point_Threshold_Under_limit_update},
} ;
static inst_map_t const sio_Point_Threshold_inst_map[] = {
    {.name = "ihn4_above_disp",
     .id = SIO_POINT_THRESHOLD_IHN4_ABOVE_DISP_INST_ID},
    {.name = "ihn4_above_inj",
     .id = SIO_POINT_THRESHOLD_IHN4_ABOVE_INJ_INST_ID},
    {.name = "ihn4_max_pres",
     .id = SIO_POINT_THRESHOLD_IHN4_MAX_PRES_INST_ID},
    {.name = "ix77b_above_disp",
     .id = SIO_POINT_THRESHOLD_IX77B_ABOVE_DISP_INST_ID},
    {.name = "ix77b_above_inj",
     .id = SIO_POINT_THRESHOLD_IX77B_ABOVE_INJ_INST_ID},
    {.name = "ix77b_max_pres",
     .id = SIO_POINT_THRESHOLD_IX77B_MAX_PRES_INST_ID},
} ;
static inst_map_t const sio_R6_Assigner_inst_map[] = {
    {.name = "r6asgn1",
     .id = SIO_R6_ASSIGNER_R6ASGN1_INST_ID},
} ;
static event_map_t const sio_R6_Assigner_event_map[] = {
    {.name = "Converter_assigned",
     .id = SIO_R6_ASSIGNER_CONVERTER_ASSIGNED_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "Converter_ready",
     .id = SIO_R6_ASSIGNER_CONVERTER_READY_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "Group_ready",
     .id = SIO_R6_ASSIGNER_GROUP_READY_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
} ;
static attr_map_t const sio_Range_Limitation_attr_map[] = {
    {.name = "Over_count",
     .id = SIO_RANGE_LIMITATION_OVER_COUNT_ATTR_ID,
     .attr_read = sio_Range_Limitation_Over_count_read,
     .attr_update = sio_Range_Limitation_Over_count_update},
    {.name = "Under_count",
     .id = SIO_RANGE_LIMITATION_UNDER_COUNT_ATTR_ID,
     .attr_read = sio_Range_Limitation_Under_count_read,
     .attr_update = sio_Range_Limitation_Under_count_update},
} ;
static inst_map_t const sio_Range_Limitation_inst_map[] = {
    {.name = "above_disp_iop1",
     .id = SIO_RANGE_LIMITATION_ABOVE_DISP_IOP1_INST_ID},
    {.name = "above_disp_iop2",
     .id = SIO_RANGE_LIMITATION_ABOVE_DISP_IOP2_INST_ID},
    {.name = "above_disp_iop3",
     .id = SIO_RANGE_LIMITATION_ABOVE_DISP_IOP3_INST_ID},
    {.name = "above_inj_iop1",
     .id = SIO_RANGE_LIMITATION_ABOVE_INJ_IOP1_INST_ID},
    {.name = "above_inj_iop2",
     .id = SIO_RANGE_LIMITATION_ABOVE_INJ_IOP2_INST_ID},
    {.name = "above_inj_iop3",
     .id = SIO_RANGE_LIMITATION_ABOVE_INJ_IOP3_INST_ID},
    {.name = "max_pres_iop1",
     .id = SIO_RANGE_LIMITATION_MAX_PRES_IOP1_INST_ID},
    {.name = "max_pres_iop2",
     .id = SIO_RANGE_LIMITATION_MAX_PRES_IOP2_INST_ID},
    {.name = "max_pres_iop3",
     .id = SIO_RANGE_LIMITATION_MAX_PRES_IOP3_INST_ID},
} ;
static event_map_t const sio_Range_Limitation_event_map[] = {
    {.name = "In_range",
     .id = SIO_RANGE_LIMITATION_IN_RANGE_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "New_point",
     .id = SIO_RANGE_LIMITATION_NEW_POINT_EVENT_ID,
     .paramFmt = sio_Range_Limitation_New_point_fmt,
     .pcount = 1},
    {.name = "Out_of_range",
     .id = SIO_RANGE_LIMITATION_OUT_OF_RANGE_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
} ;
static attr_map_t const sio_Signal_Converter_attr_map[] = {
    {.name = "Converter_available",
     .id = SIO_SIGNAL_CONVERTER_CONVERTER_AVAILABLE_ATTR_ID,
     .attr_read = sio_Signal_Converter_Converter_available_read,
     .attr_update = sio_Signal_Converter_Converter_available_update},
} ;
static inst_map_t const sio_Signal_Converter_inst_map[] = {
    {.name = "cvt1",
     .id = SIO_SIGNAL_CONVERTER_CVT1_INST_ID},
} ;
static event_map_t const sio_Signal_Converter_event_map[] = {
    {.name = "Conversion_done",
     .id = SIO_SIGNAL_CONVERTER_CONVERSION_DONE_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "Converter_assigned",
     .id = SIO_SIGNAL_CONVERTER_CONVERTER_ASSIGNED_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
} ;
static attr_map_t const sio_Signalling_Point_attr_map[] = {
    {.name = "Active_high",
     .id = SIO_SIGNALLING_POINT_ACTIVE_HIGH_ATTR_ID,
     .attr_read = sio_Signalling_Point_Active_high_read,
     .attr_update = sio_Signalling_Point_Active_high_update},
    {.name = "Debounce_time",
     .id = SIO_SIGNALLING_POINT_DEBOUNCE_TIME_ATTR_ID,
     .attr_read = sio_Signalling_Point_Debounce_time_read,
     .attr_update = sio_Signalling_Point_Debounce_time_update},
    {.name = "Trigger",
     .id = SIO_SIGNALLING_POINT_TRIGGER_ATTR_ID,
     .attr_read = sio_Signalling_Point_Trigger_read,
     .attr_update = sio_Signalling_Point_Trigger_update},
    {.name = "Value",
     .id = SIO_SIGNALLING_POINT_VALUE_ATTR_ID,
     .attr_read = sio_Signalling_Point_Value_read,
     .attr_update = sio_Signalling_Point_Value_update},
} ;
static inst_map_t const sio_Signalling_Point_inst_map[] = {
    {.name = "iop10",
     .id = SIO_IO_POINT_IOP10_INST_ID},
    {.name = "iop11",
     .id = SIO_IO_POINT_IOP11_INST_ID},
    {.name = "iop7",
     .id = SIO_IO_POINT_IOP7_INST_ID},
    {.name = "iop8",
     .id = SIO_IO_POINT_IOP8_INST_ID},
    {.name = "iop9",
     .id = SIO_IO_POINT_IOP9_INST_ID},
} ;
static event_map_t const sio_Signalling_Point_event_map[] = {
    {.name = "Confirm",
     .id = SIO_SIGNALLING_POINT_CONFIRM_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "Off",
     .id = SIO_SIGNALLING_POINT_OFF_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "On",
     .id = SIO_SIGNALLING_POINT_ON_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
    {.name = "Trigger",
     .id = SIO_SIGNALLING_POINT_TRIGGER_EVENT_ID,
     .paramFmt = NULL,
     .pcount = 0},
} ;
static class_map_t const sio_class_map[] = {
    {.name = "Continuous_Input_Point",
     .id = SIO_CONTINUOUS_INPUT_POINT_CLASS_ID,
     .attrs = sio_Continuous_Input_Point_attr_map,
     .attr_count = 1,
     .insts = sio_Continuous_Input_Point_inst_map,
     .inst_count = 3,
     .events = NULL,
     .event_count = 0,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Control_Point",
     .id = SIO_CONTROL_POINT_CLASS_ID,
     .attrs = sio_Control_Point_attr_map,
     .attr_count = 2,
     .insts = sio_Control_Point_inst_map,
     .inst_count = 3,
     .events = NULL,
     .event_count = 0,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Conversion_Group",
     .id = SIO_CONVERSION_GROUP_CLASS_ID,
     .attrs = sio_Conversion_Group_attr_map,
     .attr_count = 2,
     .insts = sio_Conversion_Group_inst_map,
     .inst_count = 3,
     .events = sio_Conversion_Group_event_map,
     .event_count = 3,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Packed_Point",
     .id = SIO_PACKED_POINT_CLASS_ID,
     .attrs = sio_Packed_Point_attr_map,
     .attr_count = 2,
     .insts = NULL,
     .inst_count = 0,
     .events = NULL,
     .event_count = 0,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Point_Scaling",
     .id = SIO_POINT_SCALING_CLASS_ID,
     .attrs = sio_Point_Scaling_attr_map,
     .attr_count = 4,
     .insts = sio_Point_Scaling_inst_map,
     .inst_count = 2,
     .events = NULL,
     .event_count = 0,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Point_Threshold",
     .id = SIO_POINT_THRESHOLD_CLASS_ID,
     .attrs = sio_Point_Threshold_attr_map,
     .attr_count = 4,
     .insts = sio_Point_Threshold_inst_map,
     .inst_count = 6,
     .events = NULL,
     .event_count = 0,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "R6_Assigner",
     .id = SIO_R6_ASSIGNER_CLASS_ID,
     .attrs = NULL,
     .attr_count = 0,
     .insts = sio_R6_Assigner_inst_map,
     .inst_count = 1,
     .events = sio_R6_Assigner_event_map,
     .event_count = 3,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Range_Limitation",
     .id = SIO_RANGE_LIMITATION_CLASS_ID,
     .attrs = sio_Range_Limitation_attr_map,
     .attr_count = 2,
     .insts = sio_Range_Limitation_inst_map,
     .inst_count = 9,
     .events = sio_Range_Limitation_event_map,
     .event_count = 3,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Signal_Converter",
     .id = SIO_SIGNAL_CONVERTER_CLASS_ID,
     .attrs = sio_Signal_Converter_attr_map,
     .attr_count = 1,
     .insts = sio_Signal_Converter_inst_map,
     .inst_count = 1,
     .events = sio_Signal_Converter_event_map,
     .event_count = 2,
     .polyevents = NULL,
     .polyevent_count = 0},
    {.name = "Signalling_Point",
     .id = SIO_SIGNALLING_POINT_CLASS_ID,
     .attrs = sio_Signalling_Point_attr_map,
     .attr_count = 4,
     .insts = sio_Signalling_Point_inst_map,
     .inst_count = 5,
     .events = sio_Signalling_Point_event_map,
     .event_count = 4,
     .polyevents = NULL,
     .polyevent_count = 0},
} ;

static dportal_t const sio_domain_portal = {
    .name = "sio",
    .dops = sio_domain_op,
    .dop_count = 3,
    .classes = sio_class_map,
    .class_count = sizeof(sio_class_map) / sizeof(sio_class_map[0]),
    .dportal = &sio_portal
} ;


/*
 * STATIC INLINE FUNCTION DEFINITIONS
 */

/*
 * INLINE FUNCTION DECLARATIONS
 */

/*
 * EXTERNAL FUNCTION DEFINITIONS
 */
void
sio_harness_init(void)
{
    harness_register(&sio_domain_portal) ;
}

void
eop_sio_NOTIFY_New_point_value(sio_Point_ID point, sio_Point_Value value)
{
    harness_stub_printf(stubLabel, "domain sio eop NOTIFY_New_point_value parameters {point %"PRIu8" value %"PRId32"}", (uint8_t)(point), (int32_t)(value)) ;
}

void
eop_sio_NOTIFY_In_range(sio_Point_ID point, sio_Threshold_ID threshold)
{
    harness_stub_printf(stubLabel, "domain sio eop NOTIFY_In_range parameters {point %"PRIu8" threshold %"PRIu8"}", (uint8_t)(point), (uint8_t)(threshold)) ;
}

void
eop_sio_NOTIFY_Out_of_range(sio_Point_ID point, sio_Threshold_ID threshold)
{
    harness_stub_printf(stubLabel, "domain sio eop NOTIFY_Out_of_range parameters {point %"PRIu8" threshold %"PRIu8"}", (uint8_t)(point), (uint8_t)(threshold)) ;
}

void
eop_sio_NOTIFY_Signal_point(sio_Point_ID point, bool isActive)
{
    harness_stub_printf(stubLabel, "domain sio eop NOTIFY_Signal_point parameters {point %"PRIu8" isActive %"PRIu8"}", (uint8_t)(point), (uint8_t)(isActive)) ;
}

void
eop_sio_DEVICE_Write_reg(sio_Point_ID pid, sio_Point_Value value)
{
    harness_stub_printf(stubLabel, "domain sio eop DEVICE_Write_reg parameters {pid %"PRIu8" value %"PRId32"}", (uint8_t)(pid), (int32_t)(value)) ;
}

void
eop_sio_DEVICE_Enable_signal(sio_Point_ID pid)
{
    harness_stub_printf(stubLabel, "domain sio eop DEVICE_Enable_signal parameters {pid %"PRIu8"}", (uint8_t)(pid)) ;
}

void
eop_sio_DEVICE_Disable_signal(sio_Point_ID pid)
{
    harness_stub_printf(stubLabel, "domain sio eop DEVICE_Disable_signal parameters {pid %"PRIu8"}", (uint8_t)(pid)) ;
}


/*
 * STATIC FUNCTION DEFINITIONS
 */
static bool sio_Read_point_dop(int argc, char const *const *argv, char const **result)
{
    if (argc != 2) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), wrong_args_msg, argc, 2) ;
        *result = cvt_buffer ;
        return false ;
    }
    uint8_t param0 ;
    if (sscanf(argv[1], "%"SCNi8, &param0) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_param_msg, argv[1]) ;
        *result = cvt_buffer ;
        return false ;
    }
    int32_t retvalue = sio_Read_point(param0) ;
    snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, retvalue) ;
    *result = cvt_buffer ;
    return true ;
}
static bool sio_Write_point_dop(int argc, char const *const *argv, char const **result)
{
    if (argc != 3) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), wrong_args_msg, argc, 3) ;
        *result = cvt_buffer ;
        return false ;
    }
    uint8_t param0 ;
    if (sscanf(argv[1], "%"SCNi8, &param0) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_param_msg, argv[1]) ;
        *result = cvt_buffer ;
        return false ;
    }
    int32_t param1 ;
    if (sscanf(argv[2], "%"SCNi32, &param1) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_param_msg, argv[2]) ;
        *result = cvt_buffer ;
        return false ;
    }
    sio_Write_point(param0, param1) ;
    *result = empty_string ;
    return true ;
}
static bool sio_init_dop(int argc, char const *const *argv, char const **result)
{
    if (argc != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), wrong_args_msg, argc, 1) ;
        *result = cvt_buffer ;
        return false ;
    }
    sio_init() ;
    *result = empty_string ;
    return true ;
}
static bool sio_Packed_Point_Length_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint8_t value = (uint8_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Packed_Point_Offset_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint8_t value = (uint8_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Signalling_Point_Value_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int32_t value = (int32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Signalling_Point_Trigger_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint8_t value = (uint8_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Signalling_Point_Active_high_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint8_t value = (uint8_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Signalling_Point_Debounce_time_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint32_t value = (uint32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Control_Point_Memory_model_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint8_t value = (uint8_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Control_Point_Access_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint8_t value = (uint8_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Continuous_Input_Point_Value_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int32_t value = (int32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Scaling_Multiplier_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int32_t value = (int32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Scaling_Divisor_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int32_t value = (int32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Scaling_Intercept_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int32_t value = (int32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Scaling_Mask_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int32_t value = (int32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Threshold_Limit_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int32_t value = (int32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Threshold_Direction_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint8_t value = (uint8_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Threshold_Over_limit_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int value = (int)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Point_Threshold_Under_limit_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int value = (int)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Range_Limitation_Over_count_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int value = (int)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Range_Limitation_Under_count_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    int value = (int)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Signal_Converter_Converter_available_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    bool value = (bool)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""u", value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Conversion_Group_Waiting_for_converter_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    bool value = (bool)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""u", value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}

static bool sio_Conversion_Group_Period_read(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const **result)
{
    bool retvalue ;

    uint32_t value = (uint32_t)0 ;
    int err = pycca_read_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, read_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu32, value) ;
        retvalue = true ;
    }
    *result = cvt_buffer ;
    return retvalue ;
}


static bool sio_Packed_Point_Length_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint8_t value ;
    if (sscanf(attr_value, "%"SCNi8, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Packed_Point_Offset_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint8_t value ;
    if (sscanf(attr_value, "%"SCNi8, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Signalling_Point_Value_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Signalling_Point_Trigger_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint8_t value ;
    if (sscanf(attr_value, "%"SCNi8, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Signalling_Point_Active_high_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint8_t value ;
    if (sscanf(attr_value, "%"SCNi8, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Signalling_Point_Debounce_time_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Control_Point_Memory_model_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint8_t value ;
    if (sscanf(attr_value, "%"SCNi8, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Control_Point_Access_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint8_t value ;
    if (sscanf(attr_value, "%"SCNi8, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Continuous_Input_Point_Value_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Scaling_Multiplier_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Scaling_Divisor_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Scaling_Intercept_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Scaling_Mask_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Threshold_Limit_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRId32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Threshold_Direction_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint8_t value ;
    if (sscanf(attr_value, "%"SCNi8, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu8, value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Threshold_Over_limit_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int value ;
    if (sscanf(attr_value, "%""i", &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Point_Threshold_Under_limit_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int value ;
    if (sscanf(attr_value, "%""i", &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Range_Limitation_Over_count_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int value ;
    if (sscanf(attr_value, "%""i", &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Range_Limitation_Under_count_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    int value ;
    if (sscanf(attr_value, "%""i", &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""d", value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Signal_Converter_Converter_available_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    bool value ;
    unsigned tmp_value ;
    if (sscanf(attr_value, "%""u", &tmp_value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    value = tmp_value ;
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""u", value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Conversion_Group_Waiting_for_converter_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    bool value ;
    unsigned tmp_value ;
    if (sscanf(attr_value, "%""u", &tmp_value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    value = tmp_value ;
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%""u", value) ;
        retvalue = true ;
    }
    return retvalue ;
}

static bool sio_Conversion_Group_Period_update(struct pycca_domain_portal const *portal, unsigned class_id, unsigned inst_id, unsigned attr_id, char const *attr_value, char const **result)
{
    bool retvalue ;
    *result = cvt_buffer ;
    uint32_t value ;
    if (sscanf(attr_value, "%"SCNi32, &value) != 1) {
        snprintf(cvt_buffer, sizeof(cvt_buffer), bad_attr_value_msg, attr_value) ;
        return false ;
    }
    int err = pycca_update_attr(portal, class_id, inst_id, attr_id, &value, sizeof(value)) ;
    if (err < 0) {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, write_err_msg, err) ;
        retvalue = false ;
    } else {
        snprintf(cvt_buffer, sizeof(cvt_buffer) - 1, "%"PRIu32, value) ;
        retvalue = true ;
    }
    return retvalue ;
}


static int sio_Range_Limitation_New_point_fmt(EventParamType *params, int argc, char const **argv)
{
    struct New_point_params {
        sio_Point_Value pointValue ;
    } *pp = (struct New_point_params *)params ;
    int pnum = 0 ;
    if (sscanf(*argv++, "%"SCNi32, &pp->pointValue) != 1) {
        return pnum ;
    } else {
        pnum++ ;
    }
    return -1 ;
}

