/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: /home/andrewm/working/modelstocode/mtc_source/tools/linux/tack/lib/application/main.tcl, Revision: 3.8.1
 * Generated on: Sat Apr 15 14:54:00 PDT 2017
 */

#ifndef SIOHARNESS_H_
#define SIOHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void sio_harness_init(void) ;


#endif /* SIOHARNESS_H_ */
