/*
 * DO NOT EDIT THIS FILE -- IT IS AUTOMATICALLY GENERATED
 * Generated by: C:/Users/andrewm/Working/modelrealization/modelstocode/mtc_source/tools/windows/tack.exe/lib/application/main.tcl, Revision: 3.6
 * Generated on: Fri Jun 23 14:16:36 PDT 2017
 */

#ifndef SIOHARNESS_H_
#define SIOHARNESS_H_

/*
 * INCLUDE FILES
 */

/*
 * MACRO DEFINITIONS
 */

/*
 * TYPE DEFINITIONS
 */

/*
 * EXTERNAL FUNCTION DECLARATIONS
 */

extern void sio_harness_init(void) ;


#endif /* SIOHARNESS_H_ */
